### ISSUE TITLE
README.md code not correct for current version

### ISSUE THREAD

**Issue by astrobleem** [gventuri/pandas-ai#1]
import pandas as pd
from pandas_ai import PandasAI
does not work

![image](https://user-images.githubusercontent.com/7433842/235205515-1c046ee0-05c8-48f2-b8fd-06df48353c18.png)

you've apparently changed it to 
from pandasai import PandasAI
![image](https://user-images.githubusercontent.com/7433842/235205438-cc849b40-ab0b-43ad-ab65-80cd59dc101d.png)

**Comment by astrobleem** [comment]
I also had to install the astor lib

**Comment by jenboland** [comment]
I'm also getting the following error even when making the corrections above. 

![image](https://user-images.githubusercontent.com/15746580/235226061-7689fcbd-271e-4d8a-8fe4-2707bce6e5af.png)

**Comment by astrobleem** [comment]
pip install langchain openai

from langchain.llms import OpenAI

**Comment by jenboland** [comment]
I still get the same error even after installing langchain openai

**Comment by gventuri** [comment]
@astrobleem thanks a lot for reporting. It was actually importing the old package.

The correct code should be:
```
import pandas as pd
from pandasai import PandasAI
```

I've updated the README, thanks a lot for reporting. Please, let me know if everything works for you!
