### ISSUE TITLE
Automate pypi release in github actions

### ISSUE THREAD

**Issue by TiansuYu** [gventuri/pandas-ai#101]
### 🚀 The feature

I noticed that currently the release process to pypi is manually triggered. This however can be automated whenever a new release is published. 

The trigger of such workflow can be found e.g. [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release).

Regarding the release job, it can either be written by utilising the [pypi-publish](https://github.com/marketplace/actions/pypi-publish) github action, or you can formulate the build steps following the [guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) from PyPA.

Please let me know if this is something we are interested, and I would also love to contribute a PR if needed. (though some helps may needed from admins regarding credentials and test runs).

### Motivation, pitch

I noticed that currently the release process to pypi is manually triggered. This however can be automated whenever a new release is published.

**Comment by HenriqueAJNB** [comment]
@gventuri, at the end of this [video](https://youtu.be/0f3moPe_bhk) there is how to publish a package with poetry.

This topic could be allocated in CI.

By the way, I'm the one who made the outline and examples for that vídeo.
