### ISSUE TITLE
Design of the CLI

### ISSUE THREAD

**Issue by victor-hugo-dc** [gventuri/pandas-ai#104]
How would you like the design of the CLI to be? That is, would you want it to be a simple Python script that can execute a chunk of pandasai code given a prompt, dataset, api token, etc. or would you want something more complex? Would you want it to be a part of this repository or would you want to make the CLI a different repository altogether?

**Comment by gventuri** [comment]
I'd say if it's not huge, we can leave it as part of this repo for the time being. Then if it becomes bigger and bigger we'd rather move it to a dedicate repo. @victor-hugo-dc what do you think?

**Comment by victor-hugo-dc** [comment]
I added the command line tool as a part of the repo in my latest PR, it's fairly a small tool that simply requires `python setup.py install` to be run.
