### ISSUE TITLE
Model didn’t understand my prompt and didn’t show me the plot that i want

### ISSUE THREAD

**Issue by seyidcemkarakas** [gventuri/pandas-ai#109]
### 🐛 Describe the bug

I want to see the histogram plot of area column with 10 bins (for area column min value : 65, max value: 300 and data count: 24665) i wrote it

``` python
pandas_ai.run(
    df,
    "Plot the histogram of area column with 10 bin, show xticks and yticks",
)
```

and it gave me result like 

<img width="1554" alt="image" src="https://github.com/gventuri/pandas-ai/assets/66181520/db71def1-9c2c-41f7-9d89-1d062dd1171e">

What should i do ?

**Comment by akespresso** [comment]
There was a regression in 0.2.9 that sometimes caused this kind of response. Can you try upgrading to 0.2.10?

**Comment by seyidcemkarakas** [comment]
> There was a regression in 0.2.9 that sometimes caused this kind of response. Can you try upgrading to 0.2.10?

Pandas-ai library that i am using already up to 0.2.10

`pandasai                  0.2.10                   pypi_0    pypi`

**Comment by Enthusiasm23** [comment]
I have also encountered a similar situation
![微信图片_20230510140750](https://github.com/gventuri/pandas-ai/assets/84498523/212a3e32-23bc-451a-aed0-40c6ad3a1767)

**Comment by gventuri** [comment]
I've just fixed the issue, thanks a lot for reporting. Please, let me know if is works for you too!
