### ISSUE TITLE
Add GPT-4 support

### ISSUE THREAD

**Issue by vpaul18** [gventuri/pandas-ai#11]
Why are 3.5 & davinci the only ones supported?

**Comment by gventuri** [comment]
@vpaul18 haven't tested with GPT-4 yet and wanted to make sure it works as expected. Adding it asap!

**Comment by gventuri** [comment]
@vpaul18 you should now be able to use also GPT-4! 🚀

**Comment by vpaul18** [comment]
Awesome work! Thanks!On 1 May 2023, at 01:14, Gabriele Venturi ***@***.***> wrote:﻿
@vpaul18 you should now be able to use also GPT-4! 🚀

**Comment by pavankumarbalijepalli** [comment]
How can one toggle between 3.5 and 4

**Comment by daniel-counto** [comment]
@gventuri  how to choose which gpt to choose? it's not found anywhere on the github
