### ISSUE TITLE
Adding more LLMs

### ISSUE THREAD

**Issue by dSupertramp** [gventuri/pandas-ai#111]
### 🚀 The feature

Add more LLMs

### Motivation, pitch

Do you know if there is a list of all possible LLMs? The idea is to add support to more LLMs as possible

**Comment by mzeidhassan** [comment]
@dSupertramp This is a much needed addition indeed.
This page could be a very good start. 
https://chat.lmsys.org/

**Comment by gventuri** [comment]
Let's move this into this existing conversation: https://github.com/gventuri/pandas-ai/discussions/58
The goal, imo, should be to figure out which LLMs we want to introduce and then create one issue for each of the LLM we plan to add so that someone can pick it up!
