### ISSUE TITLE
Minor comment; use `verbose=True` in introductory example

### ISSUE THREAD

**Issue by ArhamCMB** [gventuri/pandas-ai#113]
Hello,
Thank you for creating this library. This is fantastic! 
Wanted to point out one minor thing. The primary example of your main page (https://github.com/gventuri/pandas-ai) does not generate the results as shown. 
Running 
```
pandas_ai = PandasAI(llm)
pandas_ai.run(df, prompt='Which are the 5 happiest countries?')
```
will only generate the conversational output. 

Setting `verbose=True`, will create the data frame as shown in your example.

Thank you!

**Comment by gventuri** [comment]
Thanks a lot for reporting, nice catch indeed @ArhamCMB! Will look into it asap!

**Comment by gventuri** [comment]
Added `conversational=False`, thanks for reporting @ArhamCMB!
