### ISSUE TITLE
Add Excel Functionality

### ISSUE THREAD

**Issue by HisokaMagician101** [gventuri/pandas-ai#121]
### 🚀 The feature

Be able to read in an excel dataframe

### Motivation, pitch

I'm not a great programmer, want the ability to read in data from excel

### Alternatives

N/A

### Additional context

N/A

**Comment by aryandgandhi** [comment]
I can take this one @gventuri

**Comment by gventuri** [comment]
Assigned to you @aryandgandhi 🚀

**Comment by jonbiemond** [comment]
@aryandgandhi Are you working on this? I'd like to submit a PR.

**Comment by aryandgandhi** [comment]
Yeah I was waiting for google sheets to be approved. Feel free to submit one though

**Comment by mspronesti** [comment]
Hi @HisokaMagician101, I believe this does not require any extra feature.
One can simply use pandas 
```py
import pandas as pd
from pandasai import PandasAI, OpenAI

excel_file = '/path/to/you/excel/file'
df = pd.read_excel(excel_file)

llm = OpenAI()
pandas_ai = PandasAI(llm, verbose=True)
response = pandas_ai(df, "your-prompt-here")
print(response)
```
