### ISSUE TITLE
ERROR: No matching distribution found for pandasai

### ISSUE THREAD

**Issue by Rohitassertai** [gventuri/pandas-ai#128]
### 🐛 Describe the bug

pip install pandasai

**Comment by sandiemann** [comment]
@Rohitassertai Could you please try to install with the latest version as suggested [here](https://github.com/gventuri/pandas-ai/issues/70)

**Comment by gventuri** [comment]
@Rohitassertai where are you running the code? Is it you local env or a notebook? Please, let us know it the problem persists!

**Comment by sandiemann** [comment]
@Rohitassertai As mentioned in the [pypi](https://pypi.org/project/pandasai/), it `Requires: Python >=3.9, <4.0`

Make sure your installed python satisfies this condition.

**Comment by Rohitassertai** [comment]
Yes I am running it directly without any environment on Ubuntu, I have
python 3.8

**Comment by reenal** [comment]
@Rohitassertai  you need to have python 3..9 and above

**Comment by gventuri** [comment]
As suggested, you need to upgrade your python to >= 3.9

@Rohitassertai, here's a tutorial of how to do it, in case you need it: https://phoenixnap.com/kb/upgrade-python
