### ISSUE TITLE
No output displayed on running the sample code from the documentation. It should display final answer whether or not verbose=True | False

### ISSUE THREAD

**Issue by shyam-sreenivasan** [gventuri/pandas-ai#129]
I copy pasted the sample code from the documentation to a file called test_pandasai.py and ran it.
`python test_pandasai.py`

program terminates without printing any output. (No errors as well to debug)

**Comment by shyam-sreenivasan** [comment]
It wan't really an issue. I needed to run with verbose=True.

**Comment by sandiemann** [comment]
@shyam-sreenivasan This change was already requested. Please have a look [here](https://github.com/gventuri/pandas-ai/issues/113)

**Comment by gventuri** [comment]
@shyam-sreenivasan could you share the prompt you used and the full log when running it with `verbose=True`?

**Comment by gventuri** [comment]
Closing! @shyam-sreenivasan, feel free to re-open if you are still facing this issue
