### ISSUE TITLE
Operations with two or more datasets

### ISSUE THREAD

**Issue by margusero** [gventuri/pandas-ai#132]
### 🚀 The feature

One great feature that would skyrocket the potential of this library is the possibility to have in the run() method two inputs for two different dataframes in order to be able to do a wider ranges of activity, for examples comparisons, mathematical operations, merge. 

### Motivation, pitch

At this stage of the development there is the possibility to use only one dataframe at a time in the run() method.

**Comment by navneetdesai** [comment]
@gventuri Hello, I would like to work on this, any tips?

**Comment by gventuri** [comment]
Closing as @victor-hugo-dc has worked on this!
