### ISSUE TITLE
Incorrect output displayed on running the sample code from the documentation for ex. it shows countries outside the given dataframe.

### ISSUE THREAD

**Issue by SameerGargCMS** [gventuri/pandas-ai#133]
### 🐛 Describe the bug

I have been testing the PandasAI for multiple dataset with OPENAI. I found out that starting from today (16 May) results are not accurate anymore. Below are the issues I see :- 

1. Sometimes it is picking the data from outside the dataframe like in one of the examples, I have asked` (pandas_ai.run(df, prompt='Which are the 5 happiest countries?')` .. US is not present in the dataset,  still it shows US as one of the result. Please refer example 3 screenshot
2. Sometime It also does not show correct result based on the metrics

Same issue I have found with other dataset as well. It was working well till 15 May.

**example 1** 
![image](https://github.com/gventuri/pandas-ai/assets/51131929/a9e9ac34-76af-484f-a6c1-faff656327bb)

**example 2** 
![image](https://github.com/gventuri/pandas-ai/assets/51131929/e53bbb70-9613-4447-94da-30a5c72795e6)

**example 3** 
![image](https://github.com/gventuri/pandas-ai/assets/51131929/9f97d1ed-3391-41ab-b14e-02af87bc3af4)

Below is the sample code.

# All necessary imports at the beginning
import pandas as pd
from pandasai import PandasAI

# Sample DataFrame
df = pd.DataFrame({
    "country": ["United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI()

pandas_ai = PandasAI(llm)
pandas_ai.run(df, prompt='Which are the 2 happiest countries?')

**Comment by gventuri** [comment]
@SameerGargCMS thanks for reporting! Should have been fixed as of 0.2.13. Can you check it out?

**Comment by SameerGargCMS** [comment]
Thanks @gventuri . It fixed the issue. I have one found one more issue on the similar lines for which I am going to create a new issue.
