### ISSUE TITLE
Inconsistency in the results of the graph and normal prompt

### ISSUE THREAD

**Issue by SameerGargCMS** [gventuri/pandas-ai#136]
### 🐛 Describe the bug

I have noticed that when we ask the same question using simple prompt and prompt having graph plotting associated , it gives the different result.

For ex.  When I run the code (`pandas_ai.run(df2, prompt='list the bottom 3 marks getter?')`) with simple prompt it shows me the correct results. However when I tried to plot the graph (`pandas_ai.run(df2, prompt='plot the histogram for bottom 3 marks getter, having marks on y-axis and names on x-axis?')`) it shows incorrect result. 

Check the bars on x-axis (in the image posted under issue heading) , Ideally it should have been on 4 with frequency as 1(only Wen score lowest) and 11 with frequency 2 (as two persons have got the marks 11)

Also when I tried to make a pie chart for bottom 3 `pandas_ai.run(df2, prompt='plot the pie chart for the bottom 3 marks getter?')` it gives a wrong result (more examples screenshot).

```
df2 = pd.DataFrame({
    "names": ["Jack", "June", "Steve", "Mark", "Andy", "Grame", "Grant", "Tyler", "Shi", "Wen"],
    "marks": [24, 51, 67, 24, 22, 11, 345, 22, 11, 4]
})
```
**dataset**
![image](https://github.com/gventuri/pandas-ai/assets/51131929/b34fa99d-4c1f-478c-84ae-b9c3b1f91ccb)
 
**Issue**
![image](https://github.com/gventuri/pandas-ai/assets/51131929/81bddd85-7b7f-43c4-8340-787de059cc56)

**More examples**
![image](https://github.com/gventuri/pandas-ai/assets/51131929/0121ea8a-328c-4a1b-9e36-37c49b3399ea)

**Comment by CarLeeToes** [comment]
I've been noticing something similiar. I can run the same code over the same dataset and sometimes I get my results printed out on the terminal and sometimes I get them back packed in a dataframe. I'm using OpenAI and I was reading that theres a temperature setting that adjusts how "random" or "crafty" its responses are. Maybe its a matter of being able to tweak it to get more constant results.

**Comment by sandiemann** [comment]
@SameerGargCMS This is well known hallucination where the provided dataframe is overridden by the code generated by the LLM.  
Here is the example to reproduce & check the generate code returned:
```
import pandas as pd
df2 = pd.DataFrame({
  ...:     "names": ["Jack", "June", "Steve", "Mark", "Andy", "Grame", "Grant", "Tyler", "Shi", "Wen"],
  ...:     "marks": [24, 51, 67, 24, 22, 11, 345, 22, 11, 4]
  ...: })
  ...: 

response = pandas_ai.run(df2, "plot the histogram for bottom 3 marks getter, having marks on y-axis and names on x-axis")
Running PandasAI with openai LLM...

Code generated:

import pandas as pd
import matplotlib.pyplot as plt
# Creating the dataframe
data = {'names': ['June', 'Jack', 'Mark', 'Andy', 'Steve', 'Liam', 'Olivia', 'Emma', 'Noah', 'Ava'],
        'marks': [24, 22, 51, 67, 24, 89, 78, 56, 45, 32]}
df = pd.DataFrame(data)
# Sorting the dataframe by marks in ascending order
df = df.sort_values(by='marks')
# Plotting the histogram for bottom 3 marks getter
bottom_3 = df.head(3)
plt.hist(bottom_3['marks'])
plt.title('Histogram of Bottom 3 Marks Getter')
plt.xlabel('Marks')
plt.ylabel('Frequency')
plt.show()
```

This issue was reported [here](https://github.com/gventuri/pandas-ai/issues/139) with a fix. Hopefully, this will be resolved with the next release.

**Comment by gventuri** [comment]
Closing, as the hallucination is now programmatically removed

**Comment by SameerGargCMS** [comment]
Hello @gventuri / @sandiemann  

I am still getting the same issue. It seems like in the background it is taking the different dataframe for  plotting / computing. 

![image](https://github.com/gventuri/pandas-ai/assets/51131929/f7c8706c-b731-465c-bb85-b6cce0bde33e)


Running PandasAI with openai LLM...


                    Code generated:
                    ```
                    import pandas as pd
import matplotlib.pyplot as plt

# create the dataframe
data = {'names': ['Andy', 'Steve', 'June', 'Jack', 'Mark', 'Sarah', 'Tom', 'Lucy', 'Bob', 'Alice'],
        'marks': [51, 24, 22, 22, 24, 45, 67, 89, 90, 87]}
df = pd.DataFrame(data)

# sort the dataframe by marks in ascending order
df = df.sort_values(by='marks')

# get the bottom 3 marks getter
bottom_3 = df.head(3)

# plot the pie chart
plt.pie(bottom_3['marks'], labels=bottom_3['names'], autopct='%1.1f%%')
plt.title('Bottom 3 Marks Getter')
plt.show()
                    ```
                

Code running:
```
data = {'names': ['Andy', 'Steve', 'June', 'Jack', 'Mark', 'Sarah', 'Tom',
    'Lucy', 'Bob', 'Alice'], 'marks': [51, 24, 22, 22, 24, 45, 67, 89, 90, 87]}
bottom_3 = df.head(3)
plt.pie(bottom_3['marks'], labels=bottom_3['names'], autopct='%1.1f%%')
plt.title('Bottom 3 Marks Getter')
plt.show()
```
Answer: None
Conversational answer: I'm sorry, but I cannot plot a pie chart as I am an AI language model and do not have the capability to create visual graphics.
I'm sorry, but I cannot plot a pie chart as I am an AI language model and do not have the capability to create visual graphics.

**Comment by gventuri** [comment]
@SameerGargCMS which version of PandasAI are you using?

**Comment by SameerGargCMS** [comment]
@gventuri  pandasai==0.3.0
