### ISSUE TITLE
Project name is misleading

### ISSUE THREAD

**Issue by iandanforth-alation** [gventuri/pandas-ai#137]
### 🐛 Describe the bug

This project is not affiliated with the pandas project and does not have a disclaimer to announce that fact.

It is ethically questionable to use the pandas name without permission. Without disclaimer it is certainly misleading.

(Also it should be noted that the documentation of this project repeatedly refers to the pandas project as 'Pandas' (capital P) which is incorrect.)

As many researchers, and other project owners have done, using a name which is related to, but distinct from the true pandas project would be preferable. For example the Alpaca project is not called LLaMA 2.

Some alternative ideas are:

 - RedPandaAI
 - BlackAndWhiteAI
 - KumAI
 - DataFrameAI
 - PandaPAI

**Comment by gventuri** [comment]
Thanks a lot @iandanforth-alation, this is indeed a very great point! I started this as a for-fun project, and would have never expected such a traction.

I'll add a disclosure and start a poll for the new name (I really like RedPandaAI).

Thanks a lot for noticing, this is a very great point!

**Comment by gventuri** [comment]
Added a disclaimer mentioning that this project is not backed by the pandas team and reached out to them asking whether they are ok with the name PandasAI!
