### ISSUE TITLE
When ever i tried to run my prompt line (pandas_ai.run(df, prompt='Which are the 5 happiest countries?'))  I'm getting this error (UnicodeEncodeError: 'latin-1' codec can't encode character '\u200b' in position 7: ordinal not in range(256)) and i don't know how to change the latino encoding to UTF or anything else 

### ISSUE THREAD

**Issue by Thiru1814** [gventuri/pandas-ai#142]
### 🐛 Describe the bug

#In Google Colab
```
Python
pandas_ai.run(df, prompt='Which are the 5 happiest countries?')
```

```
error
UnicodeEncodeError: 'latin-1' codec can't encode character '\u200b' in position 7: ordinal not in range(256)
````

**Comment by Thiru1814** [comment]
I cant find a solution for this latino encoding error

**Comment by sandiemann** [comment]
@Thiru1814 Seems like openai is throwing an error when encoding the headers. Can you check if the openai api key in your .env file doesn't have bad characters in it because the character \u200b is a zero-width space.

**Comment by Thiru1814** [comment]
But the API key has no mistakes with it even though I copied and pasted it directly. are you or anyone having this same error?

**Comment by sandiemann** [comment]
@Thiru1814 do you have your env variable surrounded by double quotes? if so, please try removing quotes:
`OPENAI_API_KEY=sk-....` without quotes.
The double quote characters are multi-byte characters, which is probably what's causing this.

**Comment by sandiemann** [comment]
@Thiru1814 did it work? have you tried the steps mentioned?

**Comment by gventuri** [comment]
Closing this! @Thiru1814 feel free to re-open if what @sandiemann suggested doesn't fix the issue!
