### ISSUE TITLE
TypeError: 'PandasAI' object is not callable

### ISSUE THREAD

**Issue by cassin-edwin** [gventuri/pandas-ai#147]
### 🐛 Describe the bug

I tried a sample code in this github repo for pandasai and got this error TypeError: 'PandasAI' object is not callable

Also, my jupyter kernel is not connecting after installing pandasai

**Comment by mspronesti** [comment]
I believe those changes have not been released yet on Pypi. Try to run `PandasAI` calling `run` instead

**Comment by gventuri** [comment]
@cassin-edwin thanks a lot for reporting! Should work now :)
