### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by mehulgupta2016154** [gventuri/pandas-ai#149]
### 🐛 Describe the bug

![image](https://github.com/gventuri/pandas-ai/assets/31255225/cb1240f9-78c6-4594-8465-19dd02d5eefa)
Unable to pip install PandasAI. Says no such package exists

**Comment by sandiemann** [comment]
@mehulgupta2016154 As mentioned in the [pypi](https://pypi.org/project/pandasai/), it Requires: `Python >=3.9, <4.0`

Make sure your installed python satisfies this condition.

**Comment by gventuri** [comment]
@mehulgupta2016154 did it solve your issue?

**Comment by mehulgupta2016154** [comment]
Yes, it worked.
