### ISSUE TITLE
Include show code feature

### ISSUE THREAD

**Issue by johnson-52197** [gventuri/pandas-ai#15]
Hi @gventuri,

I have included a feature that let's the user view the code that was used to generate the answer. A parameter named show_code can be included in the run function which will create a new cell under the prompt and pastes the code in it. Let me know if I can integrate it. 

Thank you
<img width="952" alt="Screenshot 2023-05-01 at 6 34 22 AM" src="https://user-images.githubusercontent.com/58318959/235386591-ff53bc8a-644c-43e2-81b6-2cbbcaf0f9cb.png">

**Comment by gventuri** [comment]
Hey @johnson-52197, definitely a super nice-to-have feature, would love to have it integrated. I've assigned it to you!

P.s. we are launching the discord server, in particular for the contributors, but more in general for everyone interested into playing around with PandasAI!

If you are interested:
https://discord.gg/kF7FqH2FwS
