### ISSUE TITLE
Limit the number of dependencies

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#153]
### 🚀 The feature

The core idea would be to make the user install third party additional dependencies according to the engine LLM they want to use - except OpenAI, installed by default.

### Motivation, pitch

Recently Google Palm has been integrated into PandasAI. As a consequence, `google-generativeai` has been added to this projects deps. Now I'm working on integrating GPT4All and LlamaCpp (this one does not really produce good code though), which require, respectively, `gpt4all` and `llama-cpp-python`. 
In the end, a user interested in using only one engine, say OpenAI, would be forced to install all these unneeded additional deps.

### Proposed solution
The proposed solution would be to let the user install a dependency manually only when needed. Example:
```py
try:
      from gpt4all import GPT4All as GPT4AllModel
      ...
except ImportError:
        raise ...
```
An additional possibility would be to add all of these as extra deps to make pandasai installable as follows
```shell
$ pip install pandasai["llamacpp", "googleai", ...]
```
but I believe this is not really necessary.

If you feel this is a good idea, feel free to assign me to this issue :)

**Comment by avelino** [comment]
Related https://github.com/gventuri/pandas-ai/pull/120#discussion_r1197838107

**Comment by sandiemann** [comment]
@mspronesti Great that you mentioned! I was just about to suggest this. It would be really important feature for future development to limit the dependencies.

**Comment by gventuri** [comment]
Great idea @mspronesti, love it! Does anyone want to pick this task?

**Comment by gventuri** [comment]
Great, thanks a lot! Assigned it to you!

**Comment by Al-aminI** [comment]
i have actually been playing around with it with some data, and it is actually great but when the columns are much, it use to say there is no enough information or so. and one other issue that is bothering me is when i tried to deploy a sample web app with it on render to test somethings, the build is failing by this error,:

ERROR: Could not find a version that satisfies the requirement pandasai (from -r requirements.txt (line 5)) (from versions: none)

or

ERROR: No matching distribution found for pandasai.

and thanks you for building this amazing package, i have actually worked with llms and tabular data by prompt engineering and other methods, i will like to contribute to this project too.

Thanks.

**Comment by iplayfast** [comment]
maybe even a requirements.txt file? I keep getting ImportError: cannot import name 'generativeai' from 'google' (unknown location)
and have no clue

**Comment by mspronesti** [comment]
@iplayfast which version are you using ? the one I'm trying to merge, the one currently available on `main` or the latest release ?
