### ISSUE TITLE
Outdated release version in pyproject.toml

### ISSUE THREAD

**Issue by sandiemann** [gventuri/pandas-ai#158]
### 🐛 Describe the bug

Accourding to the release notes, the version [v0.2.14](https://github.com/gventuri/pandas-ai/releases/tag/v0.2.14) was released on May 20th but the version tag is not updated in `pyproject.toml`

Steps:
- install latest version
```
pip install pandasai
...
Installing collected packages: pandasai
Successfully installed pandasai-0.2.14
```

- build package
```
pip install -e .
....
Successfully built pandasai
Installing collected packages: pandasai
  Attempting uninstall: pandasai
    Found existing installation: pandasai 0.2.14
    Uninstalling pandasai-0.2.14:
      Successfully uninstalled pandasai-0.2.14
Successfully installed pandasai-0.2.13

```

**Comment by gventuri** [comment]
Thanks a lot for reporting @sandiemann, it's more of an issue connected with the fact the CD is not working properly!
