### ISSUE TITLE
(AzureOpenAI) Incorrect output displayed on running the sample code from the documentation for ex. it shows countries outside the given dataframe

### ISSUE THREAD

**Issue by SameerGargCMS** [gventuri/pandas-ai#161]
### 🐛 Describe the bug

This issue is same as https://github.com/gventuri/pandas-ai/issues/133 except for the reason there I was using the OpenAI where here I am trying to use AzureOpenAI.

When I try to access the same data using **AzureOpenAI** , it is picking the data from outside the dataframe.

![image](https://github.com/gventuri/pandas-ai/assets/51131929/de574a7b-2f3e-42b1-9854-94c644fd2abc)

**Comment by victor-hugo-dc** [comment]
can you show the verbose output (the code that pandasai is running)?

**Comment by SameerGargCMS** [comment]
I change few values in happiness_index as below to see output :-
```
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [21400000, 2940000, 2830000, 3870000, 2160000, 1350000, 1780000, 1320000, 516000, 14000000],
    "happiness_index": [7.3, 7.2, 8.5, 7.0, 6.0, 6.3, 7.3, 7.3, 5.9, 8.5]
})
```

Sample Screenshot :- 
![image](https://github.com/gventuri/pandas-ai/assets/51131929/d6f177f4-1619-4244-8a0e-c719fde3927c)
![image](https://github.com/gventuri/pandas-ai/assets/51131929/bb4bf76c-d8ab-4874-b7e1-e101531a172a)


**Verbose Output :-** 

```
Running PandasAI with azure-openai LLM...

Code generated:
```
import pandas as pd

# Creating the dataframe
data = {'country': ['United States', 'France', 'Germany', 'Italy', 'United Kingdom', 'Japan', 'China', 'India', 'Brazil', 'Canada'],
        'gdp': [2160000, 2830000, 2940000, 2160000, 2940000, 5170000, 14300000, 3100000, 2060000, 1790000],
        'happiness_index': [6.0, 7.0, 7.2, 7.0, 6.0, 5.9, 5.4, 4.8, 6.1, 7.3]}
df = pd.DataFrame(data)

# Sorting the dataframe by happiness index in descending order
df_sorted = df.sort_values(by='happiness_index', ascending=False)

# Selecting the top 3 happiest countries
top_3_happiest = df_sorted.head(3)['country'].tolist()

print(top_3_happiest)
```

Code running:
```
data = {'country': ['United States', 'France', 'Germany', 'Italy',
    'United Kingdom', 'Japan', 'China', 'India', 'Brazil', 'Canada'], 'gdp':
    [2160000, 2830000, 2940000, 2160000, 2940000, 5170000, 14300000, 
    3100000, 2060000, 1790000], 'happiness_index': [6.0, 7.0, 7.2, 7.0, 6.0,
    5.9, 5.4, 4.8, 6.1, 7.3]}
df_sorted = df.sort_values(by='happiness_index', ascending=False)
top_3_happiest = df_sorted.head(3)['country'].tolist()
print(top_3_happiest)
```
Answer: ['France', 'China', 'United States']

Conversational answer: According to my data, the top three happiest countries are France, China, and the United States.
According to my data, the top three happiest countries are France, China, and the United States.
```

**Comment by SameerGargCMS** [comment]
Hi @victor-hugo-dc ... I checked and it is giving the correct output. Closing the issue.
