### ISSUE TITLE
pandasai==0.2.15 'Unfortunately, I was not able to answer your question. Please try again. If the problem persists, try rephrasing your question.'

### ISSUE THREAD

**Issue by AkhilSinghRana** [gventuri/pandas-ai#167]
### 🐛 Describe the bug

I am running the default code on the repository. How can I debug the issue?

**Comment by gventuri** [comment]
Can you try to run `print(pandas_ai.last_error)`?
This should print the actual error!

**Comment by AkhilSinghRana** [comment]
You exceeded your current quota, please check your plan and billing details.

**Comment by AkhilSinghRana** [comment]
> Can you try to run `print(pandas_ai.last_error)`? This should print the actual error!

You exceeded your current quota, please check your plan and billing details.

**Comment by gventuri** [comment]
Ok then I expect this is an issue related to your current billing details / your OpenAI key. Please check it out, the error should be fixed if you change the credit card details on your openai account!

**Comment by nelson123-lab** [comment]
So pandasAI can be used only if you are subscribed to chatgpt plus. I tried with my free personal account in the first prompt itself I got 'You exceeded your current quota, please check your plan and billing details.'

**Comment by gventuri** [comment]
@nelson123-lab it's not a matter of being subscribed to ChatGPT pro. OpenAI api key is a separate thing, on a pay-per-use basis, check it out: https://openai.com/pricing

**Comment by sreelal1** [comment]
Unfortunately, I was not able to answer your question, because of the following error:

'question'

I am still getting this error with the latest version of pandasAI which is 0.8.2

**Comment by praveentn** [comment]
> Unfortunately, I was not able to answer your question, because of the following error:
> 
> 'question'
> 
> I am still getting this error with the latest version of pandasAI which is 0.8.2

Getting same error in 0.8.2

Last error: "question"

**Comment by ryanmord** [comment]
> Unfortunately, I was not able to answer your question, because of the following error:
> 
> 'question'
> 
> I am still getting this error with the latest version of pandasAI which is 0.8.2

Getting the same error in version 1.5.19. The question I am sending to the agent when I receive this error doesn't reference the 'question' (or in my case 'Condition') value or field at all. I did receive this same error earlier in the chat when I was asking specifically about the 'question'/'Condition' field, so I suspect this error has something to do with caching?
