### ISSUE TITLE
Unable to install pandasai

### ISSUE THREAD

**Issue by vperrinfr** [gventuri/pandas-ai#173]
### 🐛 Describe the bug

Unable to install on MacOS 13.3.1 (Ventura).

**Command :**` pip install pandasai`

**Response :** 
```
ERROR: Could not find a version that satisfies the requirement pandasai (from versions: none)
ERROR: No matching distribution found for pandasai
```

**Comment by sandiemann** [comment]
@vperrinfr As mentioned in the [pypi](https://pypi.org/project/pandasai/), it Requires: Python >=3.9, <4.0

Make sure your installed python satisfies this condition.

**Comment by marouahamdi** [comment]
hello i m unable to install pandasai in vscode i m getting this error: UPDATING build\lib.win-amd64-cpython-312\pandas/_version.py
      set build\lib.win-amd64-cpython-312\pandas/_version.py to '1.5.3'
      running build_ext
      building 'pandas._libs.algos' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

**Comment by IbrahimAgeel** [comment]
i'm also having the same issue. tried downloading the buildtools from the link provided, but still cannot install pandasai

**Comment by joweywen** [comment]
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41)  also having the same issue. tried downloading the buildtools from the link provided, but still cannot install pandasai

**Comment by radhe271816** [comment]
yes i am facing the same the issue.
plz provide solution for that

**Comment by cjcharrison** [comment]
Same issue

**Comment by anoopramana** [comment]
Same issue with pip install pandasai
Mac Os Sequoia 15.1.1 
pyenv python 3.13.1

error:
...
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
...

**Comment by rashiq-ahmd** [comment]
unable to install pandas ai in mac os

```
        |                                                     ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pandas)

`

**Comment by gdcsinaptik** [comment]
@rashiq-ahmd, @anoopramana, @joweywen, @radhe271816 please use Python3.11 instead of Python3.12 for both 2.4.2 and 3.0. Ensure you have set up a separated virtual environment for PandasAI to handle dependencies issue. 
Docs to 3.0: https://docs.getpanda.ai/v3/getting-started
