### ISSUE TITLE
how to save chart to target path?

### ISSUE THREAD

**Issue by gumplus** [gventuri/pandas-ai#174]
### 🚀 The feature

how to save chart to target path?

### Motivation, pitch

I found the function of draw chart but no save function found.

### Alternatives

fig.canvas.print_figure

### Additional context

fig.canvas.print_figure

**Comment by navneetdesai** [comment]
I added ' Save the figure' to the prompt, and it worked. Did you try that?

**Comment by jonbiemond** [comment]
Related Discord conversation summary:
Add `save_chart` parameter to PandasAI initialization that saves any charts generated to `/exports/charts` . Chart should still be displayed and file names should include a timestamp to differentiate them.
```
pandas_ai = PandasAI(llm, verbose=True, save_charts=True)
```

**Comment by jonbiemond** [comment]
@gventuri I'd be happy to take this one. 😄

**Comment by gventuri** [comment]
@jonbiemond assigned it to you!

**Comment by jonbiemond** [comment]
Charts can now we saved by setting `save_charts` to True during the inital call of PandasAI. e.g. `PandasAI(llm, save_charts=True)`

**Comment by kumarsyamala** [comment]
I Have tried it out but getting error

![image](https://github.com/gventuri/pandas-ai/assets/82040540/569067ef-3ad3-466a-9fae-7cf0ff1b11af)

**Comment by jonbiemond** [comment]
> Yeah it worked but I am getting the pop up of plot also ........ 
> Cant we do just save instead of displaying the plot

I think most of the time the desired behaviour will be to have the chart displayed. What about using a Jupyter Notebook so the charts appear inline instead of as pop-ups?

**Comment by kumarsyamala** [comment]
> > Yeah it worked but I am getting the pop up of plot also ........
> > Cant we do just save instead of displaying the plot
> 
> I think most of the time the desired behaviour will be to have the chart displayed. What about using a Jupyter Notebook so the charts appear inline instead of as pop-ups?

Yeah  but I wanted to create a simple flask api where I can integrate the pandasai. So I want to save the plots not has display

**Comment by kumarsyamala** [comment]
> > I Have tried it out but getting error
> > ![image](https://user-images.githubusercontent.com/82040540/242202979-569067ef-3ad3-466a-9fae-7cf0ff1b11af.png)

> Upgrade pandasai to v0.3.0

I have update the pandasai version and triedit out , but charts didnt got saved as you mentioned [here](https://github.com/gventuri/pandas-ai/pull/188#issue-1729684965)

![image](https://github.com/gventuri/pandas-ai/assets/82040540/bd4196ed-3ade-4f1c-89bc-10ab87f4e90b)

![image](https://github.com/gventuri/pandas-ai/assets/82040540/539f2a67-4b9f-4df6-ae1b-b5ea06dcdf38)

**Comment by kumarsyamala** [comment]
> verbose=True

                pandas_ai = PandasAI(llm, conversational=False,verbose=True,save_charts=True)
                
                df = pd.DataFrame({
                    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
                    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
                    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
                })
                
                prompt = 'plot graph top 5 country with highest gdp '#'and save the figure'
                
                response = pandas_ai.run(df, prompt=prompt)
                
                Running PandasAI with starcoder LLM...

                    Code generated:
                    ```
                    df.sort_values(by='gdp', ascending=False).head(5).plot(x='country', y='gdp', kind='bar')
                    ```
                

                   Code running:
                    ```
                    df.sort_values(by='gdp', ascending=False).head(5).plot(x='country', y='gdp',
                        kind='bar')
                    ```
                    Answer: 
![image](https://github.com/gventuri/pandas-ai/assets/82040540/5fd7b0a9-1a07-416d-aba5-552b263f863d)

**Comment by kumarsyamala** [comment]
> Thank you. PandasAI expects a call to `plt.show()` for it to save any charts. I will open a new issue.

Cant we add a option where we can choose whether to show the charts or to save them.

It will be better if have a option to decide

**Comment by jonbiemond** [comment]
> Cant we add a option where we can choose whether to show the charts or to save them.

@gventuri Thoughts? It would be quite trivial to do. To keep the interface clean we could add an option to set `save_charts='only'` and then the result should be that charts are only saved and not displayed.
