### ISSUE TITLE
Can't use CLI pai

### ISSUE THREAD

**Issue by navneetdesai** [gventuri/pandas-ai#175]
### 🐛 Describe the bug

This issue is not duplicate to this [PR](https://github.com/gventuri/pandas-ai/issues/173), and I faced it after locally incorporating this [fix](https://github.com/gventuri/pandas-ai/pull/170). 
The only way it works is running `poetry run pai --help` :sad

## Steps to reproduce  (macOS Ventura):
- Clone the repo
- Create a venv and activate it `python3 -m venv env` `source...`
- Use poetry to install dependencies `poetry install`
- Run `pai --help`

## Error:

Traceback (most recent call last):lp
  File "Users/navneetdesai/Desktop/Repositories/Opensource/pai/__main__.py", line 3, in <module>
    from pai.__main__ import main
  File "Users/navneetdesai/Desktop/Repositories/Opensource/pai/__main__.py", line 4, in <module>
    import pandas as pd
  File "Users/navneetdesai/Desktop/Repositories/Opensource/pai/env/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "Users/navneetdesai/Desktop/Repositories/Opensource/pandas-ai/pai/env/bin/python"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/navneetdesai/Desktop/Repositories/Opensource/pandas-ai/pai/env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): tried: '/Users/navneetdesai/Desktop/Repositories/Opensource/pandas-ai/pai/env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/navneetdesai/Desktop/Repositories/Opensource/pandas-ai/pai/env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (no such file), '/Users/navneetdesai/Desktop/Repositories/Opensource/pandas-ai/pai/env/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by navneetdesai** [comment]
Thanks for the response @jonbiemond

However, I get this error even if I do not create a separate venv and use poetry directly.

**Comment by jonbiemond** [comment]
@navneetdesai So to clarify it works when you call it using `poetry run pai --help`, but not if you call from the shell?
```
>> poetry shell
>> pai --help
```

**Comment by gventuri** [comment]
@navneetdesai check it out: I tried after https://github.com/gventuri/pandas-ai/pull/170 and seems to work. Let me know!

**Comment by navneetdesai** [comment]
Looks like it started working, I couldnt point out why. Anyway, thanks @jonbiemond  @gventuri
