### ISSUE TITLE
Answer without number

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#18]
Answer without number:

![image](https://user-images.githubusercontent.com/37487002/235523918-25b34d63-feee-4b92-9705-a517a7780e56.png)

**Comment by gventuri** [comment]
Hey @PavelAgurov thanks a lot for reporting! Which LLM did you use? Can you try to run with `verbose=True` and share the log?

**Comment by mac4281** [comment]
Just to add to this, I'm getting the same result.  Using OpenAI and running verbose=True yields the exact same response.  

Also, using your Loan payments data.csv gives me a similar response across all queries.

Note, this is using colab as well, and when starting up a new notebook I got an error when installing pandasai that colab does not support pandas 2.0 for some reason, only 1.5.

Hope that helps!

**Comment by yzaparto** [comment]
After taking an initial look, it looks like it happens when the conversational flag is set to true. This is by default set to true when PandasAi is instantiated.
In the meantime to unblock I would say, use
```
llm = OpenAI(api_token=OPENAI_API_KEY)
pandas_ai = PandasAI(llm, conversational=False)
pandas_ai.run(df, prompt='How many rows in the table?')
```

**Comment by yzaparto** [comment]
This pr should fix the issue :)

https://github.com/gventuri/pandas-ai/pull/25

**Comment by gventuri** [comment]
Well done @yzaparto great job!
