### ISSUE TITLE
Facing issue with new feature "Working with multiple dataframes"

### ISSUE THREAD

**Issue by Chetan-Yeola** [gventuri/pandas-ai#189]
I am trying your new feature "Working with multiple dataframes". but it gives an error. I have tried the same example that you gave.
![image](https://github.com/gventuri/pandas-ai/assets/72593205/6111aed3-2813-4d09-8645-81fc63ce6231)

**Comment by navneetdesai** [comment]
Hello @Chetan-Yeola, I just tested the same example, and it worked. Are you sure you have pulled the latest changes?
Your fork seems to be 24 commits behind, and the code in the screenshot (__init__) seems to be updated in this [commit](https://github.com/gventuri/pandas-ai/commit/be4c717a9b0f07b88ee2aed729b637413df28a51) by @victor-hugo-dc  and @gventuri .

**Comment by Chetan-Yeola** [comment]
Hey Hi, @navneetdesai  it worked.
Thanks

**Comment by gventuri** [comment]
This should't be a issue anymore after upgrading to `v0.3.0`. Please check it out and let me know!
