### ISSUE TITLE
Unfortunately, I was not able to answer your question. Please try again. If the problem persists, try rephrasing your question. 'list' object has no attribute 'head'

### ISSUE THREAD

**Issue by UsNizami** [gventuri/pandas-ai#190]
When I run the code provided in the examples (with_multiple_dataframes.py) and it says: 
>"Unfortunately, I was not able to answer your question. Please try again. If the problem persists, try rephrasing your 

It is realted to #167 but when I run `print(pandas_ai.last_error) ` I get the following response:
>"'list' object has no attribute 'head'"

which is clearaly not due to balance of OpenAI API. Can someone help me to fix it?

**Comment by Chetan-Yeola** [comment]
Hi @UsNizami Are you sure you have pulled the latest changes?

**Comment by UsNizami** [comment]
Yes.  I have done `pip install --upgrade pandasai` and it has still the same issue.

**Comment by navneetdesai** [comment]
Hi @UsNizami , I believe `pip install --upgrade pandasai` will upgrade to [0.2.16](https://pypi.org/project/pandasai/#history) which did not have this feature. If you would like use this feature before the next release, you might have to manually upgrade to the latest commit using repo URL.
