### ISSUE TITLE
Generated code with library not in whitelist fails silently

### ISSUE THREAD

**Issue by jonbiemond** [gventuri/pandas-ai#191]
### 🐛 Describe the bug

When the code generated includes references to a library not in the whitelisted libraries it simply fails with no indication as to why. I would expect something like an ImportError to be raised.

### Example
Generated code:
```python
import pandas as pd
import seaborn as sns

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(
    data=df, x="x", y="y", col="dataset", hue="dataset",
    col_wrap=2, palette="muted", ci=None,
    height=4, scatter_kws={"s": 50, "alpha": 1}
)
```
Results in: `""`

### 🚀 Request
At this point I'll turn my bug report to a feature request. I think it would be great if we have a feature that allows the user to install the missing library, add it to the whitelist and re-run the code.

**Comment by gventuri** [comment]
Yeah, I see 2 different approaches here:
- we enable the most well known libraries (including seaborn)
- we let the user install them (but we need to be very careful, as it could be very risky)

What do you think?

**Comment by jonbiemond** [comment]
> * we enable the most well known libraries (including seaborn)
> * we let the user install them (but we need to be very careful, as it could be very risky)

1. I like this approach, although perhaps we should make them optional to prevent bloat. I like how Pandas handles this: `ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`
2. Since it's up to the user's discretion to take the risk, I think this could be alright.

I prefer number 1: whitelisting the most well known libraries as optional dependencies. And when users encounters a library not on the list that they would like to use they can request it in an issue. More comfortable users can always just install the library and copy the generated code from the log to run themselves.
