### ISSUE TITLE
Add support for LangChain LLMs

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#200]
### 🚀 The feature

We should create a wrapper to support LangChain LLMs, in order to support more models and let PandasAI work in conjunction with LangChain.

* To implement this, we should create a wrapper that extends `llm/base.py` and wraps LangChain models
* We should add langchain as an optional dependency

### Motivation, pitch

Supporting LangChain LLMs makes it easier to integrate with LangChain.

**Comment by AlonXt** [comment]
In my opinion, [llm-client](https://github.com/uripeled2/llm-client-sdk) is a better choice compared to LangChain. It provides a convenient wrapper with standardized parameters, making integration and usage much easier. You won't have to waste time dealing with complex setups or inconsistent configurations.
Another cool thing about the llm-client is that it's specifically designed for seamless integration with LLMs. Unlike LangChain, it doesn't come with a bunch of unnecessary features or dependencies you won't need.
Additionally, the llm-client offers more control over the ClientSession, which opens up possibilities for future asynchronous capabilities.

**Comment by gventuri** [comment]
@AlonXt thanks a lot for the feedback. I think ideally I don't see any con about also supporting [llm-client](https://github.com/uripeled2/llm-client-sdk). Every library is more than welcome if it can improve the experience of who uses the library!
