### ISSUE TITLE
Dataframe is returned as a string

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#201]
### 🐛 Describe the bug

When the model returns a dataframe, it is then converted to a string and cannot be used for further operations. We should make sure that when we return the dataframe we don't convert it to a string.

**Comment by navneetdesai** [comment]
Hi @gventuri, I would like to work on it, if its not taken up yet.

**Comment by gventuri** [comment]
@navneetdesai sure thing, just assigned to you :)

**Comment by navneetdesai** [comment]
I am sorry, I could not join the call. Do we have an example where a data frame is returned by the model?

**Comment by gventuri** [comment]
@navneetdesai For example if you ask to filter the dataframe or similar use cases!

**Comment by jonbiemond** [comment]
I can't replicate this. Is there an example of a prompt that may return the DataFrame as a string?

Here's what I tried:
```python
 In [11]: seattle_sales = pandas_ai(df, "Filter dataframe to only includes rows from Seattle.")

 In [12]: type(seattle_sales)
Out [12]: pandas.core.frame.DataFrame
```

**Comment by gventuri** [comment]
Closing. This only happens if we run the query in conversational mode!
