### ISSUE TITLE
CD is broken

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#202]
### 🐛 Describe the bug

The CD script is currently broken.

Expected behavior: it should deploy when a new tag is created.
Current behavior: the pipeline fails (https://github.com/gventuri/pandas-ai/actions/runs/5112099563/jobs/9189770446).

**Comment by sandiemann** [comment]
@gventuri please assign it to me. I'll have a look later today or tomorrow

**Comment by gventuri** [comment]
@sandiemann just assigned it to you :)
