### ISSUE TITLE
Support for additional HF models

### ISSUE THREAD

**Issue by wenger9** [gventuri/pandas-ai#207]
### 🚀 The feature

Allowing for the use of additional models available via HF.

### Motivation, pitch

Hi, I would like to test models as they are being released on HF for efficacy on a variety of datasets.

### Alternatives

I have tried to create a separate class for each of the additional models I am interested in using. After creating an instance of the "other_model" class, I am instantiating PandasAI. However, when I run a test script with a few sample prompts, it seems to not work at all. The code executes but returns nothing. I can work on this but a little guidance would be helpful!

**Comment by gventuri** [comment]
Hi @wenger9, thanks for reporting. Most of the models are not offered within the HF inference API, so unfortunately they don't work. There's an alternative, which is downloading the models and running them locally, but the inference could take several seconds, based on your hardware.

Could you maybe list the models you are trying to use (ideally sharing the hf url)?

**Comment by mspronesti** [comment]
Related proposal: #208

**Comment by wenger9** [comment]
> Hi @wenger9, thanks for reporting. Most of the models are not offered within the HF inference API, so unfortunately they don't work. There's an alternative, which is downloading the models and running them locally, but the inference could take several seconds, based on your hardware.
> 
> Could you maybe list the models you are trying to use (ideally sharing the hf url)?

Sure, thanks for the quick response! I'm really looking for code generation models but out of curiosity, I am also interested in exploring different types of models. Here's a list:

Run via API Inference:
- https://api-inference.huggingface.co/models/ehartford/Wizard-Vicuna-13B-Uncensored
- https://api-inference.huggingface.co/models/bigcode/santacoder

I believe I would have to use the following models locally:
- https://huggingface.co/tiiuae/falcon-40b-instruct
- https://huggingface.co/TheBloke/guanaco-65B-GPTQ
- https://huggingface.co/TheBloke/MPT-7B-Instruct-GGML
- https://huggingface.co/TheBloke/Wizard-Vicuna-30B-Uncensored-GGML
- https://huggingface.co/timdettmers/guanaco-65b
- https://huggingface.co/TheBloke/guanaco-65B-GGML

**Comment by wenger9** [comment]
> Related proposal: #208

This would be great!

**Comment by gventuri** [comment]
Hi @wenger9, at the moment local models are not supported. However you can use the wrapper around LangChain models and use a local model from LangChain. Check it out: https://pandas-ai.readthedocs.io/en/latest/LLMs/langchain-llms/
