### ISSUE TITLE
Deploy pandas-ai as APIs locally/cloud with langchain-serve

### ISSUE THREAD

**Issue by deepankarm** [gventuri/pandas-ai#21]
Great work with pandas-ai. Opens up lots of possibilities with dataframes.

[langchain-serve](https://github.com/jina-ai/langchain-serve) can help achieve many of the planned Todos (and more) by expanding the current codebase. I understand that pandas-ai doesn't use langchain, but langchain-serve works with any python-based LLM apps. 

👀 See how [pdfGPT](https://github.com/bhaskatripathi/pdfGPT#use-pdfgpt-on-production-using-langchain-serve) integrates with langchain-serve to deploy PDF Q&A bot on production.

Highlights:
- Exposes APIs from function definitions locally as well as on the cloud.
- Very few lines of code changes and ease of development remain the same as local.
- Supports both REST & WebSocket endpoints with custom authorization.
- Serverless/autoscaling endpoints with automatic tls certs on the cloud.
- Real-time streaming, human-in-the-loop support - crucial for chatbots.

Disclaimer: I'm the primary author of langchain-serve. Would be happy to collaborate on this.

**Comment by gventuri** [comment]
Closing, we'll add in the documentation as soon as the documentation will be completed!
