### ISSUE TITLE
How to specify the version of pandas which code is generated by Openai

### ISSUE THREAD

**Issue by wqh17101** [gventuri/pandas-ai#226]
### 🐛 Describe the bug
pandasai generated code below：
Code running:
```
new_df = pd.DataFrame(columns=['Type', 'Count'])
wireless_count = len(df[(df[aaaa'] > 1000) & (df['bbb'] < 95)])
Code running:
new_df = new_df.append({'Type': 'ccccc', 'Count': wireless_count}, ignore_index=True)
```
However `AttributeError: 'DataFrame' object has no attribute 'append'` in pandas 2.0

**Comment by jonbiemond** [comment]
Are there any pandas features needed from `^2.0.0`? Perhaps the dependency should be changed to version `= 1.5.3`, quite a lot got [deprecated with 2.0.0](https://pandas.pydata.org/pandas-docs/version/2.0/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes).

**Comment by gventuri** [comment]
I think OpenAI is trained until 1.5.3, so it makes sense it's not aware of the most recent versions of pandas.
We should definitely support max `1.5.3` version as of now, until we figure out a better way!
