### ISSUE TITLE
Multiple graphs overlapping

### ISSUE THREAD

**Issue by vpurandara** [gventuri/pandas-ai#228]
### 🐛 Describe the bug
version: pandasai==0.3.0

while saving graphs as png image in an API, first image is saving fine but from second images they are ovelaping with past images
![image](https://github.com/gventuri/pandas-ai/assets/110787207/e435961b-19c2-4af3-808f-0fde68251da1)

line of code is like this:
response = pandas_ai.run(analytics_df, prompt=f"{inputQuestion}, as png image with filename as {timestamp}2.png")

**Comment by jonbiemond** [comment]
Are you using the `save_charts` feature? Charts can be saved by setting `save_charts` to True during the inital call of PandasAI. e.g. `PandasAI(llm, save_charts=True)`
This will give each chart a unique name.

**Comment by vpurandara** [comment]
I'm using PandasAI(llm, save_charts=True) as well. My issue is not with saving the chart, except first result every other result graph is overlapping with previous graph

**Comment by jonbiemond** [comment]
Can you please share the log? Also is this happening with successive prompts or only when one prompt results in multiple charts?

**Comment by vpurandara** [comment]
First time graph is giving results fine:
--------------------------------------------------------------------------
![image](https://github.com/gventuri/pandas-ai/assets/110787207/146d94e5-8468-4908-bfe9-6639799f2f59)

Running PandasAI with openai LLM...

                    Code generated:
                    ```
                    import pandas as pd
import matplotlib.pyplot as plt

# read the dataframe from a csv file
df = pd.read_csv('filename.csv')

# plot a bar graph of lead's Sub Source
df['Sub Source'].value_counts().plot(kind='bar')

# set the title and labels for the graph
plt.title("Lead's Sub Source")
plt.xlabel('Sub Source')
plt.ylabel('Count')

# save the graph as a png image with filename as 20230606_1220352.png
plt.savefig('20230606_1220352.png', dpi=300, bbox_inches='tight')
                    ```
                

Code running:
```
df['Sub Source'].value_counts().plot(kind='bar')
plt.title("Lead's Sub Source")
plt.xlabel('Sub Source')
plt.ylabel('Count')
plt.savefig('20230606_1220352.png', dpi=300, bbox_inches='tight')
```
Answer: None
--------------------------------------------------------------------------------------------------------------
but  from second api call onwards the output is overlapping:

![image](https://github.com/gventuri/pandas-ai/assets/110787207/44be420d-038f-4640-ae3b-43ee1917a713)

Running PandasAI with openai LLM...

                    Code generated:
                    ```
                    import pandas as pd
import matplotlib.pyplot as plt

# read the dataframe
df = pd.read_csv('data.csv')

# drop rows with missing values in Sub Source column
df = df.dropna(subset=['Sub Source'])

# count the number of leads for each Sub Source
sub_source_counts = df['Sub Source'].value_counts()

# plot a pie chart
plt.pie(sub_source_counts, labels=sub_source_counts.index)
plt.title("Leads by Sub Source")
plt.savefig('20230606_1221432.png')
                    ```
                

Code running:
```
sub_source_counts = df['Sub Source'].value_counts()
plt.pie(sub_source_counts, labels=sub_source_counts.index)
plt.title('Leads by Sub Source')
plt.savefig('20230606_1221432.png')
```
Answer: None

**Comment by vpurandara** [comment]
this basically happens while using it in a API.

**Comment by jonbiemond** [comment]
The reason the charts are overlapping is because the figures are not getting cleared between prompts. They are typically cleared with `plt.show()`. Also note that the `save_charts` feature currently requires a call to `plt.show()` to recognize a chart is being displayed. I suggest you do not include instructions to save the chart in your prompt, instead set `save_charts=True` and PandasAI will neatly handle that for you.

**Comment by wqh17101** [comment]
I call the code below
```
        plt.show()
        plt.close("all")
```
everytime after i call pandaai's api to resolve this problem

**Comment by gventuri** [comment]
So @wqh17101 you expect that running `plt.close("all")` everytime after `plt.show()` should fix it, right?

**Comment by wqh17101** [comment]
@gventuri Yeah, i am not sure whether  you add plt.show() when you plot.
So i think that after you save picture, you can trigger it.

**Comment by jonbiemond** [comment]
In my experience just adding `plt.show()` should resolve this. A solution then is to always add `plt.show()` whenever there's a call to a plotting library. Are there situations where someone would not want `plt.show()` called? I also see this being difficult with multiple plots. (Could hand it off to the LLM in that case)

**Comment by vpurandara** [comment]
The issue is resolved, if I add plt.close() after every API request:


llm = OpenAI(api_token=OpenAI_ACCESSKEY)
pandas_ai = PandasAI(llm, save_charts=True)

response = pandas_ai.run(analytics_df, prompt=f"{inputQuestion}, as png image with filename as {timestamp}2.png")  
plt.close()

Thanks to @jonbiemond @wqh17101 @gventuri

**Comment by wqh17101** [comment]
@vpurandara i think you maybe you can keep this issue open to make pandasai @gventuri @jonbiemond  add this feature by default.

**Comment by jonbiemond** [comment]
@vpurandara you shouldn't need to add `plt.close()`

>  I suggest you do not include instructions to save the chart in your prompt, instead set save_charts=True and PandasAI will neatly handle that for you.

Have you tried this?

**Comment by jonbiemond** [comment]
> A solution then is to always add plt.show() whenever there's a call to a plotting library. Are there situations where someone would not want plt.show() called?

@wqh17101 Any thoughts on this?

**Comment by wqh17101** [comment]
i think use plt.close(all) is the best choice. Because it means close all the figures. i don't know whether plt.show will always work in this scene. 

One more thing is that is it possible for user to use their own figure and pandasai together? For pandasai exec the generative code in the main process,all the codes will affect the main process context. Maybe we should think about this or tell users to try to avoid using their own plt with pandasai together?

**Comment by gventuri** [comment]
@wqh17101 now it should add `close('all')` automatically (we are gonna release the new version with the changes soon)!
