### ISSUE TITLE
Answer is not using my pandas data

### ISSUE THREAD

**Issue by luisangelico** [gventuri/pandas-ai#242]
### 🐛 Describe the bug

import pandas as pd
from pandasai import PandasAI
from pandasai.llm.azure_openai import AzureOpenAI

df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [21400000, 2940000, 2830000, 3870000, 2160000, 1350000, 1780000, 1320000, 516000, 14000000],
    "happiness_index": [7.3, 7.2, 6.5, 7.0, 6.0, 6.3, 7.3, 7.3, 5.9, 5.0]
})

llm = AzureOpenAI(api_token='', api_base="", api_version="", deployment_name="")
pandas_ai = PandasAI(llm,verbose=True)
pandas_ai(df, prompt='What is Germany GDP?')

Output:
Running PandasAI with azure-openai LLM...

                    Code generated:
                    ```
                    germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].iloc[0]
                    ```
                

Code running:
```
germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].iloc[0]
```
Answer: 
Conversational answer: The GDP of Germany, which represents the total value of goods and services produced in the country, is quite impressive. As of 2021, it's approximately $3.85 trillion.

**Comment by gventuri** [comment]
Hi @luisangelico, thanks a lot for reporting. Can you share the whole log generated?
I'll investigate into this!

**Comment by luisangelico** [comment]
@gventuri, how can I do it? 
I already used 

pandas_ai = PandasAI(llm,verbose=True)

**Comment by gventuri** [comment]
@luisangelico yes, it'd be super helpful to see the whole log, not only the `code running part`. Can you run and copy/paste the whole log from the console?

**Comment by luisangelico** [comment]
@gventuri, that's all I have on console:


Running PandasAI with azure-openai LLM...

                    Code generated:
                    ```
                    germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].values[0]
                    ```
                

Code running:
```
germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].values[0]
```
Answer: 
Conversational answer: The GDP of Germany is quite impressive! As of 2021, it's approximately $3.85 trillion, making it one of the largest economies in the world.

**Comment by luisangelico** [comment]
@gventuri, I made different questions in the prompt and suddenly it's working. Maybe it's an allucination as you mentioned. Thanks for the support.

Running PandasAI with azure-openai LLM...

                    Code generated:
                    ```
                    germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].values[0]
germany_gdp
                    ```
                

Code running:
```
germany_gdp = df.loc[df['country'] == 'Germany', 'gdp'].values[0]
germany_gdp
```
Answer: 3870000
Conversational answer: The GDP of Germany is around 3,870,000.
