### ISSUE TITLE
Prompt asking to show a plot returns None

### ISSUE THREAD

**Issue by djoshi153** [gventuri/pandas-ai#245]
### 🐛 Describe the bug

Hi, 

I have a dataset that has 

- categorical variables `category` which has `cat_a` and `cat_b` and `state` which has ten different US states. 
- numerical variables "x" and "y".

I have set up PandasAI object with AzureOpenAI, keeping verbose=True. 

This is the prompt that I am using:
`pandas_ai(
    df,
    "For cat_a, Using the seaborn library, plot the boxplots of x for each state. figure size of 16x9",
)`
This outputs the code and returns `Answer: None` or `Answer: ' '`

I tried running the code that is present in the output in a separate cell and that gives the expected plot. 

Am I doing something wrong here?

**Comment by jonbiemond** [comment]
@djoshi153 Thanks for reporting! Can you please share the output? Generated and run code would be great.

**Comment by djoshi153** [comment]
Here you go
Prompt: 
`pandas_ai(df_other, "For cat_a, Using the seaborn library, plot the boxplots of x for each state. figure size of 24x12", )`

output: 
`
                        Code generated:
                        ```
                        import seaborn as sns

cat_a = df[df['Category'] == 'cat_a']
sns.set(rc={'figure.figsize':(24,12)})
sns.boxplot(x='State', y='x', data=cat_a)
                        ```
                    

Code running:
```
import seaborn as sns
cat_a = df[df['Category'] == 'cat_a']
sns.set(rc={'figure.figsize': (24, 12)})
sns.boxplot(x='State', y='x', data=cat_a)
```
Answer: 
''
`

**Comment by jonbiemond** [comment]
Thank you. For the chart to be displayed there needs to be a call to `plt.show()`. I think we should add it whenever we notice it's missing from the generated code. Related issue: #205

**Comment by cloudui** [comment]
I'm getting the same bug, where running the code in a separate cell does indeed work. However, I just wanted to see what the code did when running it, so I ran the code:
```
pai.run_code(pai.last_run_code, df) # and
pai.run_code(pai.last_run_code, df, use_error_correction_framework=False)
```
and I see this import error:
```
ImportError                               Traceback (most recent call last)
Cell In[37], line 1
----> 1 pai.run_code(pai.last_run_code, df, use_error_correction_framework=False)

File ~/miniforge3/envs/pandasai/lib/python3.10/site-packages/pandasai/__init__.py:473, in PandasAI.run_code(self, code, data_frame, use_error_correction_framework)
    471 except Exception as e:  # pylint: disable=W0718 disable=C0103
    472     if not use_error_correction_framework:
--> 473         raise e
    475     count += 1
    477     if multiple:

File ~/miniforge3/envs/pandasai/lib/python3.10/site-packages/pandasai/__init__.py:468, in PandasAI.run_code(self, code, data_frame, use_error_correction_framework)
    465 while count < self._max_retries:
    466     try:
    467         # Execute the code
--> 468         exec(code_to_run, environment)
    469         code = code_to_run
    470         break

File <string>:1

ImportError: __import__ not found
```
Is this a bug, or is there something wrong on my end?

**Comment by jonbiemond** [comment]
Jupyter Notebooks have a feature where they display plots inline. PandasAI however does not return the figure object, which is why it works when you run the code in it's own cell but not using PandasAI. I will dig into why PandasAI does not return the figure object, maybe it should.

**Comment by jonbiemond** [comment]
It definitely should be returning the figure object, but it's actually failing to import `seaborn`. Working on a fix.
