### ISSUE TITLE
Enh: Change pylint to ruff as default linter

### ISSUE THREAD

**Issue by alejohz** [gventuri/pandas-ai#247]
Hey,

So ruff is 100 times faster than pylint and has in other projects been replaced with ease. Also, ruff can replace isort and pylint in the dev package requirements. This would let the dev dependencies like this:
```
[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pre-commit = "^3.2.2"
ruff = "^0.0.270"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"
pytest-env = "^0.8.1"
click = "^8.1.3"
```

Additionally, the pre-commit only uses black and isort, we can also force a ruff revision, instead of isort for faster linting and checks.

Pylint vs Ruff is [widely mentioned](https://beta.ruff.rs/docs/faq/#how-does-ruff-compare-to-pylint) and Ruff developers stated that: Despite these differences, many users have successfully switched from Pylint to Ruff, especially those using Ruff alongside a [type checker](https://beta.ruff.rs/docs/faq/#how-does-ruff-compare-to-mypy-or-pyright-or-pyre), which can cover some of the functionality that Pylint provides.

I would be willing in working on a PR that addresses this. Please let me know if this is of interest.

**Comment by gventuri** [comment]
Sounds like a good improvement! Just assigned it to you 😄

**Comment by jonbiemond** [comment]
A quick check returns ~100 errors when I check the repo with `ruff` using default config. These will need to be resolved before we can migrate right?
