### ISSUE TITLE
Import statements in run code fail

### ISSUE THREAD

**Issue by jonbiemond** [gventuri/pandas-ai#253]
### 🐛 Describe the bug

Import statements in the generated code that make it into the run code fail. 

### To Replicate
Run any code that imports an optional library through `pandasai.run_code()`.
For example:
```python
code = "import seaborn as sns\nprint(sns.__version__)"
pandasai.run_code(code, pd.DataFrame())
```
Returns: `""`

### Proposed Solution
I haven't figured out why but it seems that functions `exec` and `eval` aren't able to import libraries even though they're installed in the virtual environment. One solution would be to add any optional dependencies from the generated code to the environment passed to `exec`.

Related issues: #245, #238

**Comment by gventuri** [comment]
@jonbiemond I guess the solution you mentioned is definitely the way to go! We should just figure out the cleanest approach to do that. I guess this could be a very nice candidate to be done in pair programming. What do you think @jonbiemond?

**Comment by jonbiemond** [comment]
Yes, agreed! A clean and well designed approach is important, and might take some more time to do. So I think having extra minds would be awesome. If anyone is interested, join the discord! https://discord.gg/kF7FqH2FwS
