### ISSUE TITLE
Using logging instead of print to log

### ISSUE THREAD

**Issue by wqh17101** [gventuri/pandas-ai#255]
### 🐛 Describe the bug

![image](https://github.com/gventuri/pandas-ai/assets/26429138/b2f77f96-9be9-4930-a968-6e6bd62e9ed3)

**Comment by sandiemann** [comment]
noted. we'll add the logger.

**Comment by jonbiemond** [comment]
This will also make it easy to store the log in a text file.

**Comment by jonbiemond** [comment]
Yes, right now save_charts adds it directly to the run code. But including it in the log would be better.

**Comment by jonbiemond** [comment]
@sandiemann I think storing logs would be nice to have, but not urgent.

**Comment by sandiemann** [comment]
update: added file handler to store logs in file & stream handler for console write.

**Comment by wqh17101** [comment]
By the way, i prefer using this `format='%(asctime)s [%(levelname)s] pid: %(process)d %(filename)s-%(lineno)d: %(message)s'` @sandiemann
