### ISSUE TITLE
Create a middleware system to parse the code before executing

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#257]
As mentioned here (https://github.com/gventuri/pandas-ai/discussions/221#discussioncomment-6121423), in some cases we might need to create middlewares to do changes on the code before it gets executed.

For example, when we work with streamlit, having a dedicate middleware that replaces  `plt.show()` with `st.pyplot()` could be very beneficial.

**Comment by jonbiemond** [comment]
Check out `compare_ast()` in the save_chart module. I think it can be helpful for identifying statements in the code. It's actually already used to look for calls to `plt.show()` as part of save_chart.
