### ISSUE TITLE
Possible replacement for pytest over built-in unittest

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#26]
@gventuri, wouldn't using the `pytest` framework for unit testing be better?

`pytest` is also included as a dev dependency but not used.

**Comment by gventuri** [comment]
Let's do it, `pytest` should be the way. Do you want to work on this @HenriqueAJNB?

**Comment by HenriqueAJNB** [comment]
Sure, I'll handle it.

**Comment by gventuri** [comment]
Great, thanks @HenriqueAJNB 🎉
