### ISSUE TITLE
when i tried to predict a time series,  i got this error

### ISSUE THREAD

**Issue by zhuzhuyan93** [gventuri/pandas-ai#260]
### 🐛 Describe the bug

when i tried to predict a time series,  i got this error:

```python
pandas_ai(df_t, prompt="时间序列拟合date和value, 给出拟合值")
```
in which df_t, cols: [date, value]
error:
```
Unfortunately, I was not able to answer your question, because of the following error:

Generated code includes import of datetime which is not in whitelist.
```

**Comment by jonbiemond** [comment]
I guess we should add a constant for `WHITELISTED_STANDARD_LIBRARIES`.

**Comment by gventuri** [comment]
@zhuzhuyan93, you should now be able to use it with version 0.5.1! Let me know if it works for you!
