### ISSUE TITLE
can you do what yolopandas does, i.e. provide pandas code, and return dataframe to assemble a chain of pandas operations?

### ISSUE THREAD

**Issue by cosmosanalytics** [gventuri/pandas-ai#265]
### 🚀 The feature

can you do what yolopandas does (https://github.com/ccurme/yolopandas ), i.e. 
provide pandas code, e.g.
![image](https://github.com/gventuri/pandas-ai/assets/100080151/47e89efa-e664-47c7-8fc7-46735b1a00d5)
and 
return dataframe to assemble a chain of pandas operations, e.g.
"df.llm.query("Group by type and take the mean of all numeric columns.", yolo=True).llm.query("Make a bar plot of the result and use a log scale.", yolo=True)" ?

### Motivation, pitch

the motivation is in https://github.com/ccurme/yolopandas

**Comment by jonbiemond** [comment]
With PandasAI you could do that like so:
```python
df = pandas_ai(df, prompt="Input the type column with random fruits.")
```
Be careful though you will write over you DataFrame. I recommend assigning the result to a new variable.

**Comment by gventuri** [comment]
@cosmosanalytics, as @jonbiemond mentioned, you can do it as if follows:

```
new_df = pandas_ai(df, "Group by type and take the mean of all numeric columns.")
final_df = pandas_ai(new_df, "Make a bar plot of the result and use a log scale.")
```

Please, let us know if you meant something different!
