### ISSUE TITLE
Generated code includes import of jieba which is not in whitelist. {'answer': 'Unfortunately, I was not able to answer your question, because of the following error:\n\nGenerated code includes import of jieba which is not in whitelist.\n'}

### ISSUE THREAD

**Issue by ihorizons2022** [gventuri/pandas-ai#266]
### 🐛 Describe the bug

I suggest provide a flexible way for user to install 3rd package
Generated code includes import of jieba which is not in whitelist.
{'answer': 'Unfortunately, I was not able to answer your question, because of the following error:\n\nGenerated code includes import of jieba which is not in whitelist.\n'}

**Comment by ihorizons2022** [comment]
Thank you for the great work.
Now, i will add 3rd package name to constant.py, and close the issue.
besides, if the project can add analysis function based on returned dataframe and GPT will be great.

**Comment by gventuri** [comment]
@ihorizons2022 currently working on a better 3rd party library management system. We'll probably let you pass custom whitelisted as you instantiate the `PandasAI` object.

If you don't mind sharing the prompt or some prompts causing the issue, feel free to, so that we can improve the overall quality of how we handle packages!

**Comment by gventuri** [comment]
@ihorizons2022 feel free to try again with 

```
pandas_ai = PandasAI(llm, custom_whitelisted_dependencies=["jieba"])
```

This should make the trick!

**Comment by swvajanyatek** [comment]
Should this new parameter work for other packages, such as pandas_ta?

**Comment by gventuri** [comment]
@swvajanyatek there's a typo, try this and let me know:

```
pandas_ai = PandasAI(llm, custom_whitelisted_dependencies=["pandas_ta"])
```

**Comment by swvajanyatek** [comment]
> @swvajanyatek there's a typo, try this and let me know:
> 
> ```
> pandas_ai = PandasAI(llm, custom_whitelisted_dependencies=["pandas_ta"])
> ```

@gventuri - derp, totally missed simple syntax <embarrassing>.  Thank you, it does work as expected.

**Comment by mouradk78** [comment]
@RocketRene  how do you delete the cache? Thanks

**Comment by AklankJain** [comment]
@RocketRene , did networkx whitelisting work, even after adding, I get the same error. 

`sdf = SmartDataframe(df,  config={"llm": llm, "verbose": True, "response_parser": StreamlitResponse}, custom_whitelisted_dependencies=["networkx"])`

```
NameError: name 'nx' is not defined
pandasai.exceptions.BadImportError: Generated code includes import of networkx which is not in whitelist.
```
