### ISSUE TITLE
Replace unit test repetitions with fixtures

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#27]
There are a lot of repetitive calls at unit tests setup. Maybe it would be better to replace them with fixtures. This is even simpler in `pytest` framework.

Check here: https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp

**Comment by Lorenzobattistela** [comment]
I was doing some research on pytest and how could we replace this with fixtures. What do you think on something about this (`test_pandasai.py`)

```py
import pytest

@pytest.fixture
def llm(request):
    return pytest.Mock()

@pytest.fixture
def pandasai(request, llm):
    return PandasAI(llm)

def test_init(pandasai, llm):
    assert pandasai._llm == llm
    assert pandasai._is_conversational_answer is True
    assert pandasai._verbose is False

def test_init_with_llm(pandasai, llm):
    assert pandasai._llm == llm
    assert pandasai._is_conversational_answer is True
    assert pandasai._verbose is False

def test_init_without_llm():
    with pytest.raises(LLMNotFoundError):
        PandasAI()
```

Haven't tested it yet, but I think you meant something in this sense?

**Comment by Lorenzobattistela** [comment]
Let's wait the decision and then we can create a branch to start changing it. I'm willing to contribute

**Comment by gventuri** [comment]
This would definitely help the way we test it, let's go for it. Does anyone of you @HenriqueAJNB  @Lorenzobattistela want to work on it?
Before we pick this one, though, we should work on #26 and have it merged!

**Comment by Lorenzobattistela** [comment]
I want to work on it. I can start working on the fixtures and then if @HenriqueAJNB is picking up #26 we wait for it to be merged to merge this one. Otherwise I can start working on #26 too. Let's wait for his answer

**Comment by gventuri** [comment]
Ok @Lorenzobattistela I'll assign it to you then! 🎉

**Comment by Lorenzobattistela** [comment]
@gventuri @HenriqueAJNB 

Started to work on this, is this the way to go? 

```py
import pytest
from typing import Optional
from unittest.mock import Mock, patch
import pandas as pd
from pandasai import PandasAI
from pandasai.exceptions import LLMNotFoundError
from pandasai.llm.fake import FakeLLM

@pytest.fixture
def llm(output: Optional[str] = None):
    return FakeLLM(output=output)

@pytest.fixture
def pandasai(llm):
    return PandasAI(llm)

def test_init(pandasai):
    assert pandasai._llm is not None
    assert pandasai._is_conversational_answer is True
    assert pandasai._verbose is False

def test_init_without_llm():
    with pytest.raises(LLMNotFoundError):
        PandasAI()

def test_conversational_answer(pandasai, llm):
    result = "2"
    llm._output = result
    assert pandasai.conversational_answer(
        "What is the sum of 1 + 1?", "1 + 1", 2
    ) == result

def test_run(pandasai, llm):
        df = pd.DataFrame()
        llm._output = "1"
        assert pandasai.run(df, "What number comes before 2?") == "1"

def test_run_with_conversational_answer(pandasai, llm):
        df = pd.DataFrame()
        llm._output = "1 + 1"
        assert pandasai.run(
            df, "What is the sum of 1 + 1?", is_conversational_answer=True
        ) == "1 + 1"
```

**Comment by HenriqueAJNB** [comment]
@Lorenzobattistela, as soon as #67 is merged, you are able to go on.

**Comment by gventuri** [comment]
@HenriqueAJNB @Lorenzobattistela merged, feel free to move on! :)
