### ISSUE TITLE
Save charts to folder specified by user

### ISSUE THREAD

**Issue by jonbiemond** [gventuri/pandas-ai#271]
### 🚀 The feature

Allow the user to specify the folder they would like the charts to be saved in.

### Motivation, pitch

This way charts can be saved in a location more relevant to the user. For example if using PandasAI in multiple projects, each project's related charts can be saved in that project's folder. Also requested in https://github.com/gventuri/pandas-ai/issues/212#issuecomment-1577330648

### Alternatives

I see this as primarily a convenience feature. It does work as is.

### Implementation Proposal
One way this could be implemented is by passing the desired directory to the save_charts argument. 
For example: `pandas_ai = PandasAI(llm, save_charts='path/to/folder/')`
This does feel a little overloaded to me, but it keeps the interface neat.

**Comment by jonbiemond** [comment]
Another way to implement this would be to make `save_charts` a method of `PandasAI`.
```python
pandas_ai = PandasAI(llm, verbose=True)
pandas_ai.save_charts(True, path='user/specifed/path')
```

**Comment by mitokic** [comment]
This feature would be helpful when trying to deploy pandasai inside an Azure Function, where by default you cannot easily write files, but might be able to write to a temp directory.

**Comment by amjadraza** [comment]
Strongly agee on this feature. For me, Charts were being saved inside venv folder.

**Comment by amjadraza** [comment]
This feature can easily be extended using the following idea. 

1. Include `save_chart_path` argument. Default to None: Will use current implementation
2. If `save_charts_path` is a valid root path, then save it in this Directory. 

@gventuri if no one has taken this task, I can give it a try. 

Thanks

**Comment by jonbiemond** [comment]
My concern with adding `save_chart_path` as another argument is that it further clutters the interface. By my count it would be the 11th argument that users have to consider, even though it is optional. I think it would be best if we can abstract some of the optional arguments away from the main call to PandasAI so they are only considered when needed. I'm not sure what the pythonic way of resolving this is, but as an idea we could add move charts related arguments to a separate method.

**Comment by gventuri** [comment]
@jonbiemond I think what you pointed out is actually a very good point. We need to figure out a way not to have this many optional params, otherwise things will get out of control
