### ISSUE TITLE
using a scipy and its associated functions does not return an answer or value

### ISSUE THREAD

**Issue by sscwebteam** [gventuri/pandas-ai#273]
### 🐛 Describe the bug

1

response = pandas_ai(csv_data,"correlate radius_mean to texture_mean group by diagnosis")

2

print(f"{response}")

Running PandasAI with starcoder LLM...
Prompt ID: 54560221-27d6-4c74-804c-9ac5fb0670ee
Using cached response

Code running:
```
df.groupby('diagnosis').corr().loc['radius_mean', 'texture_mean']
```
Answer:

**Comment by sscwebteam** [comment]
[data.csv](https://github.com/gventuri/pandas-ai/files/11729613/data.csv)

please refer to the sample dataset. thanks a lot for immediate reply. and, i already temporarily disabled the checking of packages and libraries for development purposes only based on your API.

**Comment by sscwebteam** [comment]
any updates on this issue?thanks

**Comment by sscwebteam** [comment]
![image](https://github.com/gventuri/pandas-ai/assets/1546754/5116d197-0f1b-45f6-8792-9bf30374459c)

**Comment by gventuri** [comment]
@sscwebteam played around with it a little bit and it seems to work fine on my side.
Which queries doesn't work for you and which result would you expect?

**Comment by sscwebteam** [comment]
the answer on cell #9 should be the same on cell #10, would be possible to return the value on the same way as shown on cell #10?

**Comment by sscwebteam** [comment]
is there a possible way that i can run the LLM starcoder on localhost?

**Comment by gventuri** [comment]
@sscwebteam 

1) I suggest you to add "and print the result" at the end of the prompt, it should then work. Unfortunately this is generating the code in a format that we are failing to parse, we are trying to figure out how to fix it asap!
2) unfortunately no, but we have an open issue for that: #187

**Comment by sscwebteam** [comment]
how can i add multiple dataset?

**Comment by gventuri** [comment]
@sscwebteam check out the documentation: https://pandas-ai.readthedocs.io/en/latest/ :)

Here's an example:

```
import pandas as pd
from pandasai import PandasAI

employees_data = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Name': ['John', 'Emma', 'Liam', 'Olivia', 'William'],
    'Department': ['HR', 'Sales', 'IT', 'Marketing', 'Finance']
}

salaries_data = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Salary': [5000, 6000, 4500, 7000, 5500]
}

employees_df = pd.DataFrame(employees_data)
salaries_df = pd.DataFrame(salaries_data)


llm = OpenAI()
pandas_ai = PandasAI(llm)
pandas_ai([employees_df, salaries_df], "Who gets paid the most?")
```

**Comment by sscwebteam** [comment]
okay. got this. thanks a lot
