### ISSUE TITLE
Can you do what yolopandas does (https://github.com/ccurme/yolopandas ), i.e. provide pandas code? (without this, how can you make sure the result is correct?)

### ISSUE THREAD

**Issue by cosmosanalytics** [gventuri/pandas-ai#274]
### 🚀 The feature

Can you do what yolopandas does (https://github.com/ccurme/yolopandas ), i.e. provide pandas code?

For frequent operations, I can just copy the code and define a function and attach the following as post-text after the prompt 

"""
    if prompt as '/volumegap: calculate volume gap in the time period of year2 over year1 by categories such as customer, SBU, plant, generic or raw material', 
    then import funlib to use the function d(df,x,t21,t22,t11,t12), 
    with df being the dataframe, x being the list of categories, t21 and t22 being the start date and end date of time period of year2,  t11 and t12 being the start date and end date of the time period of year1, and return the resulting dataframe,
"""

### Motivation, pitch

This is the motivation:

For frequent operations, I can just copy the code and define a function and attach the following as post-text after the prompt 

"""
    if prompt as '/volumegap: calculate volume gap in the time period of year2 over year1 by categories such as customer, SBU, plant, generic or raw material', 
    then import funlib to use the function d(df,x,t21,t22,t11,t12), 
    with df being the dataframe, x being the list of categories, t21 and t22 being the start date and end date of time period of year2,  t11 and t12 being the start date and end date of the time period of year1, and return the resulting dataframe,
"""

**Comment by gventuri** [comment]
@cosmosanalytics you can get the code with
```
pandas_ai.last_run_code
```

Please, note that for frequent operations, you can reuse the same prompt: the cache will make it super fast and avoid to call the LLM again.

Hope this helps, I'm closing. If you need more help, feel free to reopen!
