### ISSUE TITLE
Error when generating plot for version 0.5.1

### ISSUE THREAD

**Issue by kevin-liu-astrumu** [gventuri/pandas-ai#275]
### 🐛 Describe the bug

The plot does not work when using the pandasAI 

```python
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

pandas_ai(
    df,
    "Plot the histogram of countries showing for each the gdp, using different colors for each bar",
)
```

```bug
"Unfortunately, I was not able to answer your question, because of the following error:\n\nPandas requires version '3.7.3' or newer of 'matplotlib' (version '3.7.1' currently installed).\n"
```

The latest version for matplotlib is 3.7.1

**Comment by jonbiemond** [comment]
@gventuri This error is raised by `import_dependency()`, I think the matplotlib version might be a typo. https://github.com/gventuri/pandas-ai/blob/3f1de8f2a39c436f616ff330dabf76490b5ca5a1/pandasai/helpers/_optional.py#L26

Do we need to manually enforce versions for non-optional dependencies? They should be enforced via the package manager.

**Comment by gventuri** [comment]
Should work fine with `0.5.2`! Thanks a lot for reporting @kevin-liu-astrumu and thanks a lot for the prompt fix @jonbiemond!
