### ISSUE TITLE
Prompting

### ISSUE THREAD

**Issue by wenger9** [gventuri/pandas-ai#279]
Is it possible to update chat_completion() in base.py such that the messages array can be filled with example prompts?

```
    def chat_completion(self, value: str) -> str:
        """
        Query the chat completion API

        Args:
            value (str): Prompt

        Returns:
            str: LLM response
        """
        params = {
            **self._default_params,
            "messages": [
                {
                    "role": "system",
                    "content": value,
                }
            ],
        }

        if self.stop is not None:
            params["stop"] = [self.stop]

        response = openai.ChatCompletion.create(**params)

        return response["choices"][0]["message"]["content"]
```

Here is what I would like to do.

```
{"role":"system", "content": "You are an AI Assistant."}
{"role":"user", "content": "Who was the first president?"}
{"role":"assistant", "content": "George Washington was the first president."}
{"role":"user", "content": "Who was the 30th president?"}
{"role":"assistant", "content": "Calvin Coolidge was the 30th president."}
{"role":"user", "content": query}
```

Or perhaps query would be user_message?

A few iterations ago with pandasai, I thought to make those changes in the _instructions template that was in pandasai/__init__.py. However, I believe that has been modified in the current version. Appreciate any help or guidance on this. Thank you!

**Comment by wenger9** [comment]
It could be neater if the preprompts are saved as a prompt_{template_name}.txt file in the /prompts directory? Thinking out loud.

**Comment by gventuri** [comment]
Do you mean something like this #41?

**Comment by wenger9** [comment]
Hey! Yea, that seems to be similar to what I am thinking. However, with preprompting, our messages parameter to ChatCompletion gives the model some "context" on how to respond even with the very first response. I recall reading a tutorial at one point that showed the ability to add "examples" to the model before one would input their very first query.

I hope I'm not being too confusing. I can look to find additional examples if that would be helpful.

**Comment by RobertHH-IS** [comment]
This is essential.  It is both necassary to include explanations of each dataframe - with further description of headers, and also to include examples.  I cannot use pandasai without this.

**Comment by SpookkyMaDookky** [comment]
I believe these are the same... 
#312

**Comment by gventuri** [comment]
Closing! As @SpookkyMaDookky mentioned it's a duplicate. We'll implement this feature as of v1!
