### ISSUE TITLE
Response time is too long to get output.

### ISSUE THREAD

**Issue by ShekarBakkashetty** [gventuri/pandas-ai#280]
### 🐛 Describe the bug

Hi Team,

There are two issues.
1) Sometimes, the response time is too long, even though with Paid API KEY. It is taking more than 5 minutes? Any suggestions to improve performance
2)There is also an observation where the same Python code is executing faster in jupyter notebook than in Pycharm or vs. code studio. Any advices? The same code even with Paid API key.

I am trying to build a web interface to upload the file and start the analysis using Streamlit. But the response time is too long, Please advise any suggestions.
******************************************************************************************************************************
import pandas as pd
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
import time
import warnings
warnings.filterwarnings('ignore')
start_time=time.time()
df = pd.read_csv('titanic.csv')
llm = OpenAI('XXXXXXXXXXXX')

Pandas_ai = PandasAI(llm)
res =Pandas_ai.run(df,prompt = 'plot the bar graph between cout of Passengerids and Survived')
end_time=time.time()
print(res)
total_time=end_time-start_time
print("total time:",total_time,"in seconds")
********************************************************************
Please refer to the below screenshot: In jupyter notebook, It has been executed in Around 14s.

![Screenshot 1](https://github.com/gventuri/pandas-ai/assets/92913631/79871926-04f5-44fa-86fe-42c16defabd4)

Please refer to the below screenshot: In Pycharm, I just got the chart as output, and still running in the background for 8 minutes with no text output.
![Screenshot 2](https://github.com/gventuri/pandas-ai/assets/92913631/fd1a4347-059b-4ba9-9552-e30c85738c80)

Thanks !.
Suggestions and Advises are highly appreciated!!!

**Comment by jonbiemond** [comment]
Thanks for reporting @ShekarBakkashetty. I believe this is the same issue reported in #52. `matplotlib` blocks code execution until the chart is closed. Can you please try the same prompt again and see if it completes after closing the chart popup?

**Comment by ShekarBakkashetty** [comment]
Thanks @jonbiemond. Yes, it works fast after closing the chart. Thank you

**Comment by gventuri** [comment]
Thanks a lot @jonbiemond, closing the issue!
