### ISSUE TITLE
The entire generated code result is not included in the response

### ISSUE THREAD

**Issue by abhishekvarma12345** [gventuri/pandas-ai#288]
### 🐛 Describe the bug

The below prompt generates the code correctly in the `pandasai.log` file with two print statements, but the response returned is only w.r.t to last print statement.

```python
pandas_ai(df, prompt="Find the total inflow and outflow amount for all Transactions?") 

```
***log file code with response***
2023-06-15 16:50:04 [INFO] 
Code running:
```python
total_inflow = df[df['amount'] > 0]['amount'].sum()
total_outflow = df[df['amount'] < 0]['amount'].sum()
print('Total Inflow: ', total_inflow)
print('Total Outflow: ', total_outflow)
```
2023-06-15 16:50:04 [INFO] Answer: ('Total Outflow: ', -366008.31999999995)

**Comment by gventuri** [comment]
Hey @abhishekvarma12345 thanks a lot for responding.
As of now we only catch the last print and display that one, but in this very case it's actually printing twice, which makes it a edge case that we definitely need to address.

Thanks for reporting, will work on it!

**Comment by ihorizons2022** [comment]
thank you for the great package
actually i do not think this is an edge case but urgent case. a few of question are always included in one prompt but only the last printed result returned.
besides, shall we change the generate response prompt not only transform answers into conversational way but also treat all printed answers as context to model to solve more complex questions

**Comment by gventuri** [comment]
Yeah, I agree, I’ll work on it asap.
We can try to capture all the prints and return even multiple results.

I’m not sure I understand the second point about "treating all printed answers as context to model”. Could you make some examples?

Gabriele

**Comment by gventuri** [comment]
Close, as the issue has been fixed
