### ISSUE TITLE
Example of using Azure OpenAI api

### ISSUE THREAD

**Issue by zhh210** [gventuri/pandas-ai#293]
### 🚀 The feature

Most of the tutorials/examples are using the original OpenAI api. Despite having suspiciously similar name, Azure OpenAI api is substantially different (which sucks). Providing an example would greatly expand the usability of the library to corporate environment.

### Motivation, pitch

I was able to follow the recommended [script](https://github.com/gventuri/pandas-ai/blob/main/pandasai/llm/azure_openai.py) , however given there's no example of using Azure OpenAI api, it is not clear to me why my code wasn't going through:
```
from pandasai.llm.azure_openai import AzureOpenAI
llm = AzureOpenAI(api_token=my_openai['key'], api_base=openai.api_base, api_version=openai.api_version, deployment_name='gpt-35-turbo')
pandas_ai = PandasAI(llm)
pandas_ai(df, prompt='Which are the 5 happiest countries?')
```
as it keeps saying

```
Resource not found
'Unfortunately, I was not able to answer your question, because of the following error:\n\nResource not found\n'
```

### Additional context

it seems llm creation was successful as the error happened after the Azure openAI object creation

**Comment by chayanray** [comment]
Hi @zhh210 

Try this:
`llm = AzureOpenAI( deployment_name=deployment_name,   model_name="gpt-35-turbo",api_token=API_KEY , api_base=RESOURCE_ENDPOINT, api_version='2023-03-15-preview')`

Deployment Name and Model Name should be different in AzureOpenAI.

**Comment by adeepmalmotra** [comment]
@chayanray can you please explain the difference between the deployment_name and model_name as I was also facing the similar error and now I am confused between these two terms as previously as I was giving deployment_name as the model I have deployed in azure.
