### ISSUE TITLE
Inability to bypass pandasai.log generation when deploying on production

### ISSUE THREAD

**Issue by amraotkar** [gventuri/pandas-ai#296]
When deploying pandasai on AWS Lambda or in any production environment, the pandasai.log file is being generated, which is undesirable. 

This issue aims to find a solution or workaround to bypass the generation of the pandasai.log file during deployment.

**Comment by gventuri** [comment]
@amraotkar it's now be possible passing `enable_logging=False` as you instantiate PandasAI:

`pandasai = PandasAI(llm=llm, enable_logging=False)`

**Comment by bkhexa** [comment]
@amraotkar  try "save_logs":False
