### ISSUE TITLE
Azure OpenAI shouldn't rely on the (deprecated) `Deployment` API  

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#297]
### 🐛 Describe the bug

When I implemented the Azure OpenAI client, I thought it was a good idea to automate the logic to decide whether to use the completion or the chat completion APIs. This relied on the `openai.Deployment` API which is however no longer supported after version `2023-03-15-preview` [[reference](https://github.com/openai/openai-python/issues/460#issuecomment-1569290683)].

As a result, providing a new version of the api to `AzureOpenAI` raises the following expcetion

```py
InvalidRequestError: Resource not found
```

The new recommended way of doing it is to use `azure-mgmt-cognitiveservices`, as showcased, for instance, in this [example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitiveservices/azure-mgmt-cognitiveservices/generated_samples/get_deployment.py). This migration would require 2 additional deps ( `azure-identity`, `azure-mgmt-cognitiveservices`) and to provide quite some additional info on the Azure cloud subscription.

Given these considerations, we have the following options:
- add an additional parameter to specify whether `deployment_name` corresponds to a chat or a completion model (defaulted to completion) <-- this is my suggestion!
- freeze `api_version` to `2023-03-15-preview` (but this sounds a rather bad idea)
- use the recommended `azure-mgmt-cognitiveservices` (but this worsens the user-experience imho)

**Comment by gventuri** [comment]
@mspronesti thanks a lot for the very detailed ticket! I'd personally go for the 1st solution, as it seems the one that makes more sense!

Do you want me to assign this to you?

**Comment by mspronesti** [comment]
@gventuri gladly :) I will open a PR tomorrow!

**Comment by gventuri** [comment]
@mspronesti sounds great!! Thanks a lot for all the efforts to support Azure OpenAI 🚀

**Comment by mspronesti** [comment]
Done :)
