### ISSUE TITLE
pandas-ai with latest pandas version

### ISSUE THREAD

**Issue by vpurandara** [gventuri/pandas-ai#298]
### 🐛 Describe the bug

Currently latest version of pandas-ai is using pandas==1.5.3 version, but I observed the results are far better if it is using pandas==2.0.2(latest) version.

Please have a look on it

**Comment by sandiemann** [comment]
@vpurandara we have reverted pandas dependency to `1.5.3`.  Please follow [this](https://github.com/gventuri/pandas-ai/issues/226) thread
