### ISSUE TITLE
can't display chinese words while directly codes in juypter can do

### ISSUE THREAD

**Issue by huangzhenhao90** [gventuri/pandas-ai#300]
### 🐛 Describe the bug

I have data in Chinese words，and asked the pandas to draw a chart with seaborn, but the Chinese words can't display. 
But in the same jupyter environment, the Chinese words can display. 

**Below are my data and codes:**
<img width="841" alt="image" src="https://github.com/gventuri/pandas-ai/assets/33592619/4ca7eb33-cb11-4bfd-8cd9-86cdfdeffd14">

**Below is the pandasai plot**
<img width="1023" alt="image" src="https://github.com/gventuri/pandas-ai/assets/33592619/f783f923-b643-4602-9617-36d382bcad72">

**Below is the bar chart I draw in the same jupyter window with plotly which works well**
<img width="375" alt="image" src="https://github.com/gventuri/pandas-ai/assets/33592619/cdad34cd-141d-4204-be96-2318b3e4850a">

**Comment by gventuri** [comment]
From what I realize, it might be a problem of fonts. Could you instantiate PandasAI with `verbose=True` (`pandas_ai = PandasAI(llm, verbose=True)` or run it and then print `pandas_ai.last_code_executed` and share the output, so that I can double check?

**Comment by huangzhenhao90** [comment]
> 
**The output is** 
_**"sns.barplot(x=df.index, y='文章数量', data=df)"**_

**with the code below:** 
pandas_ai = PandasAI(llm,verbose=True)
...
pandas_ai(pivot_number,prompt='以柱状图展示内容，使用seaborn画图',show_code='True')
...
pandas_ai.last_code_executed

**Comment by soaringsoul** [comment]
> I solved the issue with the help of GPT-4, using the codes below to change the chinese fonts into 'Sim-Hei'. Thank you for your attention, gventuri
> 
> `# Set the font for matplotlib
> 
> plt.rcParams['font.sans-serif'] = ['SimHei'] # Use 'Microsoft YaHei' font to display Chinese characters plt.rcParams['axes.unicode_minus'] = False # Ensure the minus sign is displayed correctly`

 "Excuse me, where should the following code be placed? Is it to modify the source code of pandasai?"

**Comment by huangzhenhao90** [comment]
> > I solved the issue with the help of GPT-4, using the codes below to change the chinese fonts into 'Sim-Hei'. Thank you for your attention, gventuri
> > `# Set the font for matplotlib
> > plt.rcParams['font.sans-serif'] = ['SimHei'] # Use 'Microsoft YaHei' font to display Chinese characters plt.rcParams['axes.unicode_minus'] = False # Ensure the minus sign is displayed correctly`
> 
> "Excuse me, where should the following code be placed? Is it to modify the source code of pandasai?"

No,not the source code.Put it in your jupyterlab before other codes.

**Comment by soaringsoul** [comment]
> > > I solved the issue with the help of GPT-4, using the codes below to change the chinese fonts into 'Sim-Hei'. Thank you for your attention, gventuri
> > > `# Set the font for matplotlib plt.rcParams['font.sans-serif'] = ['SimHei'] # Use 'Microsoft YaHei' font to display Chinese characters plt.rcParams['axes.unicode_minus'] = False # Ensure the minus sign is displayed correctly`
> > 
> > 
> > "Excuse me, where should the following code be placed? Is it to modify the source code of pandasai?"
> 
> No,not the source code.Put it in your jupyterlab before other codes.

i see and it worked.
thanks so much!
