### ISSUE TITLE
Google Sheets + Multiple Dataframes

### ISSUE THREAD

**Issue by yassinkortam** [gventuri/pandas-ai#301]
### 🚀 The feature

Given a shareable link to a google sheet, pandas ai will be able to identify all the tables in the spreadsheet, create a data frame for each of them, and answer queries about the google sheet by referencing the appropriate dataframe.

### Motivation, pitch

This use case will bring Pandas AI closer to where a significant number of users' data lives. Instead of downloading a CSV file for each table in a spreadsheet and manually creating dataframes, users can simply share a link with pandas AI and it will work seamlessly.

**Comment by amjadraza** [comment]
Do we have sae feature for Excel file too ?

**Comment by yassinkortam** [comment]
Not yet but it would be straight forward to add support for excel.
