### ISSUE TITLE
Matplotlib Version

### ISSUE THREAD

**Issue by SwannSchilling** [gventuri/pandas-ai#302]
### 🐛 Describe the bug

I am getting Pandas requires version '3.7.3' or newer of 'matplotlib' (version '3.7.1' currently installed).
While 3.7.1 seems to be the newest version.

Also the shortcuts are giving me errors, eg
AttributeError: 'PandasAI' object has no attribute 'impute_missing_values'

**Comment by gventuri** [comment]
@SwannSchilling it seems you are using an old version on `PandasAI`.
Could you please try to update and let us know?

**Comment by SwannSchilling** [comment]
I am on version 0.6.2

**Comment by gventuri** [comment]
@SwannSchilling are you sure you are using the right version?

Try, in your python code, to run the following:

```
import pandasai

print(pandasai.__version__)
```

**Comment by SwannSchilling** [comment]
import pandasai
pandasai.__version__
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-432972af22cd>", line 1, in <module>
    pandasai.__version__
AttributeError: module 'pandasai' has no attribute '__version__'

That is very strange...so it might be the problem that I am running it in Pycharm and not in a notebook?

**Comment by gventuri** [comment]
@SwannSchilling try to use `print(pandasai.__version__)` instead of `pandasai.version`!

**Comment by SwannSchilling** [comment]
```
 print(pandasai.__version__)
AttributeError: module 'pandasai' has no attribute '__version__'
```

I did, I just forgot to format it, sorry!

**Comment by gventuri** [comment]
@SwannSchilling can you try to update to the `0.6.4` and retry with

```
import pandasai

print(pandasai.__version__)
```

I am almost sure this is actually a conflict between venvs or something like that!

**Comment by SwannSchilling** [comment]
I actually deinstalled and reinstalled globally, but will make a global uninstall and just install it to the venv!

**Comment by SwannSchilling** [comment]
It seems to work now on version 0.6.9
