### ISSUE TITLE
Add support for VertexAI models

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#309]
### 🚀 The feature

We should add the support for VertexAI models (i.e. PaLM 2).

### Motivation, pitch

Given this is backed by Google, it will become increasingly important.

### Additional context

* https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-models-overview
* https://medium.com/generative-ai/google-palm-api-generative-models-for-code-generation-275589c5bd71

**Comment by mspronesti** [comment]
Do you plan to support all models or only the code ones?

**Comment by gventuri** [comment]
@mspronesti it's a great question!
Maybe all the models, provided that the non-code ones are good enough at generating code? We should definitely benchmark the quality of each model. What's your thoughts about it @mspronesti?

**Comment by amjadraza** [comment]
Let me find some literature on this, however, code-bison should be the default considering Google much have done some benchmarks already.

**Comment by amjadraza** [comment]
I have one point, should we include this support as it is already supported through LangChain Vertex  Model?

**Comment by gventuri** [comment]
@amjadraza great, totally agree.

Since langchain is an optional dependency, I think supporting the most widespread LLMs "natively" would be a much smoother process. The goal of PandasAI has always be being fast and easy to use, so any unnecessary configuration should be removed imo!

**Comment by amjadraza** [comment]
> @amjadraza great, totally agree.
> 
> Since langchain is an optional dependency, I think supporting the most widespread LLMs "natively" would be a much smoother process. The goal of PandasAI has always be being fast and easy to use, so any unnecessary configuration should be removed imo!

Sure, I can work on this feature. Would as for help if needed.

**Comment by gventuri** [comment]
Would be awesome, assigning it to you! Thanks a lot @amjadraza!

**Comment by amjadraza** [comment]
@gventuri please see the PR against this issue.
