### ISSUE TITLE
Key error with Excel data

### ISSUE THREAD

**Issue by kstevica** [gventuri/pandas-ai#31]
When loading Excel spreadsheet, GPT hallucinates column name (eg., 'HQ Location' or 'Country' instead of 'Location'). If there's vector embedding behind this, column names should be included in the prompt.

**Comment by gventuri** [comment]
@kstevica can you make an example? There's actually no vector embedding behind this, and column names are provided as part of the prompt, so seems more like an hallucination of the LLM.

Could you try to run it like this:
```
pandas_ai = PandasAI(llm, verbose=True)
response = pandas_ai.run(df, "Your question goes here")
```

and share the log? That could help us to figure out why the hallucination happens!

**Comment by gventuri** [comment]
Closing, as should have been fixed. Feel free to re-open if the problem persists
