### ISSUE TITLE
In Streamlit Pandas AI always returns:  No code found in the response

### ISSUE THREAD

**Issue by fabmeyer** [gventuri/pandas-ai#313]
### 🐛 Describe the bug

My imports:
`
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
from pandasai.middlewares.streamlit import StreamlitMiddleware
`

I am using OpenAI API for the LLM.
My model:
`
llm = OpenAI(api_token=os.environ['OPENAI_API_KEY'])
pandas_ai = PandasAI(llm, verbose=True, middlewares=[StreamlitMiddleware()])
`

I have pretty big dataframes with a lot of text data.

Sample row (in JSON):
`
[{'https://automotivelogistics.h5mag.com/electric-vehicles-2020/ev_fvl', 'url_success': True, 'content': 'Risky business\n\nFor one thing, both hybrid and all-electric models utilise significantly higher voltages than combustion vehicles, with voltages reaching 650 volts, clearly giving rise to a risk of fatal exposure. ..., 'authors': [], 'published': None, 'year': None, 'verified_tickers_and_companies': [{'ticker': 'COTS', 'exchange': 'US', 'name': '', 'description': '', 'score': nan}, {'ticker': 'NGDV', 'exchange': 'US', 'name': '', 'description': '', 'score': nan}, {'ticker': 'IRA', 'exchange': 'US', 'name': '', 'description': '', 'score': nan}, {'ticker': 'EIS', 'exchange': 'US', 'name': '', 'description': '', 'score': nan}], 'schema': []}
`

For every single question I ask, it always returns: 
"Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response"

Even for simple questions like "how many entries are in the dataframe?"

I tried the sample code from above in the shell and it worked.

**Comment by gventuri** [comment]
Hey @fabmeyer thanks for reporting.

Can you share the `pandasai.log` file or the log as you run it with `verbose=True`?

**Comment by fabmeyer** [comment]
@gventuri thanks for reaching out to me

Here's the file:

[pandasai.log](https://github.com/gventuri/pandas-ai/files/11879397/pandasai.log)

**Comment by gventuri** [comment]
That's actually weird @fabmeyer. Tried to reproduce it on streamlit and seems to work fine. Could you please share the streamlit code?

**Comment by gventuri** [comment]
@fabmeyer there is a param that you can pass that should actually do that:

```
pandas_ai = PandasAI(llm, verbose=True, conversational=True)
```

Let me know if that works for you!

**Comment by Jaqenzhang** [comment]
@fabmeyer  Hello sir, I  saw you were using an amazing chatbot ui. Could you please kindly share it?
