### ISSUE TITLE
When running with Plot, The Programe does not end but hangs in there. 

### ISSUE THREAD

**Issue by amjadraza** [gventuri/pandas-ai#315]
### 🐛 Describe the bug

I have tried to run the Prompt with below example and the Code is stuck running...

This is happening for me more than once. I had to terminate the code run manually

```
import pandas as pd
import os
from data.sample_dataframe import dataframe

from pandasai import PandasAI
from pandasai.llm.openai import OpenAI

df = pd.DataFrame(dataframe)

llm = OpenAI()

path = os.getcwd()
pandas_ai = PandasAI(llm, save_charts=True,
                     save_charts_path=path,
                     verbose=True)
response = pandas_ai(
    df,
    "Plot the histogram of countries showing for each the gpd,"
    " using different colors for each bar",
)
# Output: check out images/histogram-chart.png
```

>Moreover, when Conversational = True and prompt asks to Generate Plots, It is also a contradiction. The code should not request the Conversational feature again as there is no data to Summarise.

**Comment by jonbiemond** [comment]
Duplicate of #52. See for details on a band-aid solution.

**Comment by amjadraza** [comment]
Closing as it is duplicate of #52
