### ISSUE TITLE
Cannot capture CLI output with new pandas-ai version

### ISSUE THREAD

**Issue by aiakubovich** [gventuri/pandas-ai#322]
### 🐛 Describe the bug

I have the following function:

    def get_agent_response(self, uploaded_file_content, query):
        
        from pandasai import PandasAI
        from pandasai.llm.azure_openai import AzureOpenAI

        llm = AzureOpenAI(
                            api_token = os.environ["OPENAI_API_KEY"], 
                            api_base = os.environ["OPENAI_API_BASE"], 
                            deployment_name = os.environ["OPENAI_API_MODEL_NAME"], 
                            model_name = os.environ["OPENAI_API_MODEL_NAME"]
                            )
        pandas_ai = PandasAI(llm, verbose=True)

        old_stdout = sys.stdout
        sys.stdout = captured_output = StringIO()
        
        response = pandas_ai.run(data_frame = uploaded_file_content, prompt=query)
        fig = plt.gcf()
        if fig.get_axes():
            fig.set_size_inches(12, 6)
            plt.tight_layout()
            buf = BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            st.image(buf, caption="Generated Plot")
        
        sys.stdout = old_stdout

        print("Captured Output:", captured_output.getvalue()) 

        return response, captured_output

For PandasAI v0.2.15,  `captured_output.getvalue()` is CLI output with python code. For newest PandasAI version (0.6.5), `captured_output.getvalue()` is empty. 

I was trying to contextlib to capture output as well but no luck so far.

**Comment by aiakubovich** [comment]
looks like problem started after this update: https://github.com/gventuri/pandas-ai/pull/258

**Comment by gventuri** [comment]
@aiakubovich thanks a lot for reporting. It's actually not a bug. We decided to log using the builtin logger instead of `print`.

Could you please let us know what's the use case for capturing the output? If I understand the use case, we can definitely figure out a way to help :)

**Comment by aiakubovich** [comment]
Hi @gventuri . I am trying to display the agent's thoughts in UI interface of streamlit app.

Here how UI interface look like: 
![img](https://github.com/gventuri/pandas-ai/assets/136030897/1079934f-492b-4486-aa30-acc542fd41a0)

I was able to catch logging output using the following class:

```
class StringIOHandler(logging.Handler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.log_capture_string = StringIO()

    def emit(self, record):
        msg = self.format(record)
        self.log_capture_string.write(msg + "\n")

    def reset(self):
        self.log_capture_string = StringIO()
```

and code in main app:
```
pandas_ai = PandasAI(llm, verbose=True)
log_capture_handler = StringIOHandler()
log_capture_handler.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
log_capture_handler.setFormatter(formatter)
pandas_ai._logger.addHandler(log_capture_handler)  # Add the custom handler to the PandasAI logger
....
log_contents = log_capture_handler.log_capture_string.getvalue()
```

Feel free to close the issue

**Comment by amjadraza** [comment]
@gventuri, I think users should be able to capture the logger INFO and Debug level messages with a custom logger or built-in logger somehow.

**Comment by gventuri** [comment]
@aiakubovich you can now access to it with `pandasai.logs` if you prefer to avoid the workaround!

**Comment by aiakubovich** [comment]
@gventuri  sorry, but how do I use those logs? 

![image](https://github.com/gventuri/pandas-ai/assets/136030897/064830c8-fc8d-46db-8ee2-d18a662c5ae0)

**Comment by ividal** [comment]
With pandasai now being deprecated, what's the advised way to capture the model's thoughts when using a SmartDataFrame?

Thank you very much!
