### ISSUE TITLE
Capitalized Integer dtypes Fail

### ISSUE THREAD

**Issue by BSalita** [gventuri/pandas-ai#327]
### 🐛 Describe the bug

Looks like every capitialized integer dtype (supporting NA) fails (invalid dtype) while uncapitalized works. Using v0.6.7. I was unable to find a list of (un)supported dtypes so I assume this is unexpected behavior.

    df = pd.DataFrame([0,1],columns=['col'],dtype='Int64') # fails but 'int64' works!
    print(type(df),df)
    pandas_ai.clear_cache()
    pandas_ai(df, prompt='Show dataframe') # using openai

**Comment by yassinkortam** [comment]
This may be helpful for this discussion: https://stackoverflow.com/questions/65580052/pandas-does-uppercase-lowercase-mean-anything-in-dtypes

Can you show a copy of your logs for this interaction please? It should include the generated and executed code.

**Comment by BSalita** [comment]
Did you try the code?

Below is the entire log file:
2023-07-02 09:05:54 [INFO] Question: Show dataframe
2023-07-02 09:05:54 [INFO] Running PandasAI with openai LLM...
2023-07-02 09:05:54 [INFO] Prompt ID: b73d00e5-14cd-4ace-bb29-24a1f5d08a39

**Comment by yassinkortam** [comment]
This error is due to the anonymize_dataframe_head function. It seems to do some sort of illegal casting. I will look into it more and make PR.
