### ISSUE TITLE
Fails for DataFrame of One Item

### ISSUE THREAD

**Issue by BSalita** [gventuri/pandas-ai#328]
### 🐛 Describe the bug

A dataframe of one item [0] in list fails ('list index out of range') but two items [0,1] works. One item dataframe is a valid pandas dataframe.

    df = pd.DataFrame([0],columns=['col'],dtype='int64') # [0] fails below but [0,1] works!
    print(type(df),df)
    pandas_ai.clear_cache()
    pandas_ai(df, prompt='Show dataframe') # using openai

**Comment by gventuri** [comment]
Hey @BSalita thanks a lot for reporting. Could you please share more info about the error of the `pandasai.log` file?

**Comment by BSalita** [comment]
The code will duplicate the error.
