### ISSUE TITLE
Explicitly State Location of cache.db

### ISSUE THREAD

**Issue by BSalita** [gventuri/pandas-ai#329]
### 🚀 The feature

Documentation says "The cache is stored in a file called cache.db in the root directory of the project." Where is the root directory? This is unclear in varied environments such as cloud/Linux/Windows or notebooks. It would be better to explicitly state location in documentation or offer a function which returns location.

### Motivation, pitch

Location of cache.db is unclear in some environments.

**Comment by BSalita** [comment]
Looks like the reason I couldn't find cache.db is because it doesn't exists? There's a cache directory with files but no cache.db. Is the documentation obsolete?

**Comment by gventuri** [comment]
@BSalita thanks a lot for reporting. Yes, I confirm, and I've just updated the documentation! Thanks a lot for reporting!
