### ISSUE TITLE
astor.to_source() seems to add a newline in the code when unparsing the AST tree

### ISSUE THREAD

**Issue by psaini-qontigo** [gventuri/pandas-ai#342]
### 🐛 Describe the bug

When any expression or statement in the `code` passed to method [_clean_code()](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L530) is too long, the [astor.to_source()](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L557) method adds a newline within the expression. Which causes the [last_line](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L692) to have incomplete expression. 

here is an controlled example to replicate this issue
```python
import pandas as pd
import ast
import astor

code="""df[(df['SOME_DATAFRAME_COLUMN'] == 'SOME_VALUE_BIG_ENOUGH_TO_MAKE_THIS_EXPRESSION_LONG') & (df['RUN_AT'] == '2023-05-22 15:38:34')]['ANOTHER_DATAFRAME_COLUMN'].values[0]"""

tree = ast.parse(code)
new_body = []
for node in tree.body:
    new_body.append(node)
new_tree = ast.Module(body=new_body)
final_code=astor.to_source(new_tree).strip()
print(repr(final_code))
``` 

This gives an output as:
```
"df[(df['SOME_DATAFRAME_COLUMN'] ==\n    'SOME_VALUE_BIG_ENOUGH_TO_MAKE_THIS_EXPRESSION_LONG') & (df['RUN_AT'] ==\n    '2023-05-22 15:38:34')]['ANOTHER_DATAFRAME_COLUMN'].values[0]"
```

Because of this the [last_line](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L692) becomes `    '2023-05-22 15:38:34')]['ANOTHER_DATAFRAME_COLUMN'].values[0]` and [eval()](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L699) returns empty.

**Comment by psaini-qontigo** [comment]
I think there are two ways to fix this:

1. (Which seems a better way to me) The [_clean_code()](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L530) method, apart from returning the clean code, should also return the last node of the ast tree, which we can use to derive [last_line](https://github.com/gventuri/pandas-ai/blob/330fea823a2a80d787ee01834308574004791ef2/pandasai/__init__.py#L692C9-L692C18) here.
2. We can use [ast.unparse()](https://docs.python.org/3/library/ast.html#ast.unparse) which seems to not introduce newline. Here is the code I tried which works okay:
```python
import pandas as pd
import ast
import astor

code="""df[(df['SOME_DATAFRAME_COLUMN'] == 'SOME_VALUE_BIG_ENOUGH_TO_MAKE_THIS_EXPRESSION_LONG') & (df['RUN_AT'] == '2023-05-22 15:38:34')]['ANOTHER_DATAFRAME_COLUMN'].values[0]"""

tree = ast.parse(code)
new_body = []
for node in tree.body:
    new_body.append(node)
new_tree = ast.Module(body=new_body, type_ignores=tree.type_ignores)
final_code=ast.unparse(new_tree).strip()
print(repr(final_code))
```
Which gives output as(no newlines):
```
"df[(df['SOME_DATAFRAME_COLUMN'] == 'SOME_VALUE_BIG_ENOUGH_TO_MAKE_THIS_EXPRESSION_LONG') & (df['RUN_AT'] == '2023-05-22 15:38:34')]['ANOTHER_DATAFRAME_COLUMN'].values[0]"
```

**Comment by gventuri** [comment]
@psaini-qontigo great catch and thanks for suggesting.

I'd say the first approach would be my preferred one, although we have to be very sure we don't break any other edge case. If it's not to invasive, let's go for that one, otherwise also the second one works great.

I'd love you to make a PR about this, just assigned the issue to you! @psaini-qontigo! Thanks a lot
