### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by gowthaml15** [gventuri/pandas-ai#364]
### 🚀 The feature

Is there a feature that enables to save the code generated after asking the question?

### Motivation, pitch

The reason I am asking this as an feature is sometimes the code generated is not able to run the code with the data.

**Comment by gventuri** [comment]
Hi @gowthaml15 could you be more specific. Do you mean export the actual script genereted or just to display it?

**Comment by gowthaml15** [comment]
Hi @gventuri, I would like a feature that allows for exporting the actual script generated.

**Comment by mspronesti** [comment]
Opened a PR for this @gowthaml15. Check it out :)
