### ISSUE TITLE
Choose a better separator for startCode and endCode

### ISSUE THREAD

**Issue by dSupertramp** [gventuri/pandas-ai#37]
HI,
I'm working on implementing Cohere LLM, and the separator used for startCode and endCode (<startCode> and <endCode>) doesn't work: I'm testing with different characters:
1. -_
2. __
3. ^^

And others

**Comment by gventuri** [comment]
Sounds great! I've assigned the issue to you. Let's make sure it doesn't break other LLMs!

**Comment by gventuri** [comment]
As far as I can see, the current implementation seems to be quite solid, I'm closing it, but feel free to reopen if you make some improvements on this @dSupertramp
