### ISSUE TITLE
Cannot find saved plot

### ISSUE THREAD

**Issue by SwannSchilling** [gventuri/pandas-ai#374]
### 🐛 Describe the bug

I tried the example of saving the plotted chart to the current working directory, but it does not seem to work!
How would I specify a path for saving it?
I tried to be even more specific about the path, but it did not work!

```
import pandas as pd
import os
from data.sample_dataframe import dataframe

from pandasai import PandasAI
from pandasai.llm.openai import OpenAI

df = pd.DataFrame(dataframe)

llm = OpenAI()

user_defined_path = os.getcwd()
save_charts_path = os.path.join(user_defined_path, 'exports', 'charts')

# Create the path if it does not exist
os.makedirs(save_charts_path, exist_ok=True)

pandas_ai = PandasAI(llm, save_charts=True,
                     save_charts_path=save_charts_path,
                     verbose=True)
response = pandas_ai(
    df,
    "Plot the histogram of countries showing for each the gpd,"
    " using different colors for each bar",
)
# Output: check out $pwd/exports/charts/{hashid}/chart.png

```

**Comment by leehanchung** [comment]
It's not saving for me as well. There seems to be some problem with the AST code.  Specifically, here's the log,  I put in two debugging warning log entries:
```bash
2023-07-20 23:19:29 [INFO] 
                        Code generated:
                        ```
                        import matplotlib.pyplot as plt

# Group the data by Position and count the number of people in each position
position_counts = df.groupby('Position')['Employee_Name'].count()

# Plot the histogram
plt.figure(figsize=(12, 6))
position_counts.plot(kind='bar')
plt.xlabel('Position')
plt.ylabel('Number of People')
plt.title('Number of People in Each Position')
plt.xticks(rotation=90)
plt.show()
                        ```
                    
2023-07-20 23:19:29 [WARNING] im in save charts pandasai_exports
2023-07-20 23:19:29 [WARNING] im in save charts pandasai_exports. show count 0
2023-07-20 23:19:29 [INFO] 
Code running:
```
position_counts = df.groupby('Position')['Employee_Name'].count()
plt.figure(figsize=(12, 6))
position_counts.plot(kind='bar')
plt.xlabel('Position')
plt.ylabel('Number of People')
plt.title('Number of People in Each Position')
plt.xticks(rotation=90)
plt.show(block=False)
plt.close('all')
```
```

**Comment by leehanchung** [comment]
This works. Thanks Claude.

```py
import ast
from pandasai.helpers.save_chart import compare_ast

code = """import matplotlib.pyplot as plt

# Group the data by Position and count the number of people in each position
position_counts = df.groupby('Position')['Employee_Name'].count()

# Plot the histogram
plt.figure(figsize=(12, 6))
position_counts.plot(kind='bar')
plt.xlabel('Position')
plt.ylabel('Number of People')
plt.title('Number of People in Each Position')
plt.xticks(rotation=90)
plt.show(block=False)
plt.close('all')"""

tree = ast.parse(code)
count = sum(1 for node in ast.walk(tree) if isinstance(node, ast.Call) and 
            isinstance(node.func, ast.Attribute) and 
            node.func.attr == 'show' and 
            node.func.value.id == 'plt')

print(count) # 1
```
