### ISSUE TITLE
Unnecessary prompt argument passed to GeneratePythonCodePrompt

### ISSUE THREAD

**Issue by gaurang98671** [gventuri/pandas-ai#379]
Hello @gventuri, not really  a bug but there is an unnecessary argument "prompt" passed in GeneratePythonCodePrompt  in `__init__.py` on [line 367](https://github.com/gventuri/pandas-ai/blob/40807f4376ad69f2f851c03306802341987d08e7/pandasai/__init__.py#L367). We dont need this as we are directly concatenating our code generation prompt and query in  ```call``` methods and [GeneratePythonCodePrompt](https://github.com/gventuri/pandas-ai/blob/main/pandasai/prompts/generate_python_code.py) doesn't have ```{prompt}``` placeholder.
Happy to open a PR for this if needed. Thanks!

**Comment by gventuri** [comment]
Great catch @gaurang98671! Sure, feel free to open a PR for that 🚀🚀
