### ISSUE TITLE
Issue with non_default_prompts

### ISSUE THREAD

**Issue by gaurang98671** [gventuri/pandas-ai#382]
PandasAI class allows us to pass [non_default_prompt](https://github.com/gventuri/pandas-ai/blob/40807f4376ad69f2f851c03306802341987d08e7/pandasai/__init__.py#L177C9-L177C9) which will basically use custom user prompts instead of default prompts. Current issue with this is that it doesn't allow users to pass their custom values in that prompt as it will just stuff in [default values](https://github.com/gventuri/pandas-ai/blob/40807f4376ad69f2f851c03306802341987d08e7/pandasai/__init__.py#L366C22-L371C22). These default arguments may seem unnecessary sometimes.

**Solution**

To resolve this issue, we can allow users to pass in a fully made custom prompt(along with custom values) to PandasAI object instead of having to pass just a classname.
It would look something like this
```
#Our custom prompt class
class Test(Prompt):
    text = """This is a test prmpt {vals}"""
vals = {"vals" : "test value"}
custom_prompt = Test(**vals)
pandasai = PandasAI(llm=llm, non_default_prompts={ "generate_python_code" : custom_prompt})

```

Handling this in ```__init__.py```
```
generate_code_instruction = self._non_default_prompts.get(
                        "generate_python_code", GeneratePythonCodePrompt(
                        df_head=df_head,
                        num_rows=data_frame.shape[0],
                        num_columns=data_frame.shape[1],
                    )
                    )
```
Please let me know if there's anything I might have overlooked or if there's a more appropriate way to accomplish this. Thank you!

**Comment by gventuri** [comment]
@gaurang98671 this would definitely make it more powerful. Could you come up with some real world examples for passing custom vars (in addition to the use query)?

Definitely something to consider tho!

**Comment by gaurang98671** [comment]
@gventuri this requirement is similar to #377. Lets say users wants to pass in more info about dataframe this would be really useful feature to have. I started working on this feature and realize there are some prompts where we might need some default arguments. For example in [correct_error_prompt](https://github.com/gventuri/pandas-ai/blob/main/pandasai/prompts/correct_error_prompt.py) we cant pre-populate ```code```, ```question``` and ```error_returned``` arguments as these will be passed in by our code in runtime and can change overtime. To solve this I came up with following solution.

### Dynamic prompts
Dynamic prompts comes with powerful placeholders, instead of statically passing values in prompts these values are computed and passed in run time.

**Override with default values**
All the values with **underscore** as prefix will be overridden by code in runtime. This will be useful in prompts where we can't pre-determine a value. Instead we let our code to pass in that value for us. This will be useful in error correction prompts.
Example : ```prompt = """You generated this python {_code}"""``` here ```_code``` value will be automatically populated with last generated code.

**Populate values in runtime**
Users can set **$** as prefix and call a dataframe object methods. Example ```prompt = """You are provided with a pandas dataframe (df) with {$df.shape[0]} rows"""```. This will allow users to pass in more info about dataframe with very less efforts.

The goal here is to make prompts more powerful so users can just focus on writing prompts and do not have to worry about how everything works under the hood.
