### ISSUE TITLE
Model adds unnecessary "\" in code response

### ISSUE THREAD

**Issue by dgavran** [gventuri/pandas-ai#384]
### 🐛 Describe the bug

Hi there,

I'm currently testing the GPT4ALL models with PandasAI but I encounter some bug, not sure if this has something to do with PandasAI, GPT4ALL or the model itself (I guess it's the latter). But when the model generates the code response it adds unnecessary "\\" everywhere, not sure why. I also added some more context where I said the model should avoid doing this, but it still does. For example, the code response would look like this:

```
<startCode>
import pandas as pd

df = pd.read\_LLaMA: reached the end of the context window so resizing
csv('dataset.csv')

num\_users\_interested\_in\_model = df[df['model\_name'] == 'model'].shape[0]
print(f"Number of users interested in model: {num\_users\_interested\_in\_model}")
<endCode>
```

Note the error that the model has reached the end of the context window. I'm currently using the Vicuna model with 7B parameters.

Do you have any idea what I'm doing wrong?

**Comment by gventuri** [comment]
@dgavran should be a issue related to the LLM. Would you mind sharing the code you are using?

**Comment by dgavran** [comment]
@gventuri thanks for the reply. This is what I already suspected. The code looks something like this:

```python

import pandas as pd
from langchain.llms import GPT4All
from pandasai import PandasAI

if __name__ == "__main__":
    model_name = "ggml-vicuna-7b-1.1-q4_2.bin"
    
    llm = GPT4All(
        model=f"./models/{model_name}.bin", temp=0.0, verbose=True, cache=False
    )
    
    pandas_ai = PandasAI(llm=llm, verbose=True, enable_cache=False)

    df = pd.read_excel("File.xlsx")

    prompt = """
        You are given a multi-column, multi-row data set describing some users and the film they watched. 
        The 'movie' column describes the movie that the user watched.
        When generating the code to solve this task, use pure Python code, no '\' or other weird writing styles.

        Your task is as follows: What is the most popular movie?
    """

    response = pandas_ai(
        df,
        prompt=prompt,
        is_conversational_answer=False,
        show_code=True,
    )

    print("Response:", response)
```

Any idea how to improve this? Or should I just change the model?
