### ISSUE TITLE
Issues while connecting Falcon7b on Huggingface 

### ISSUE THREAD

**Issue by KoolSameer** [gventuri/pandas-ai#387]
### 🐛 Describe the bug

I am using Jupyter plugin in Visual Studio

Below is the code
---------------------
import pandasai as pdai
from pandasai.llm.falcon import Falcon

llm = Falcon(huggingface_api_key="My API Key")
pandas_ai = pdai(llm=llm)
--------------------

got this error
-----------------------
TypeError: __init__() got an unexpected keyword argument 'huggingface_api_key'
---------------------

**Comment by mspronesti** [comment]
the parameter is actually called `api_key` [see [here](https://github.com/gventuri/pandas-ai/blob/68adcf5c59719529ec41d873065304ec56696ed6/pandasai/llm/falcon.py#L38)]. I just opened a PR #388 to fix the documentation. Hope this helps :)

**Comment by KoolSameer** [comment]
I again got the error...

import pandasai as pdai
from pandasai.llm.starcoder import Starcoder

llm = Starcoder(api_key="MyAPIKey")
pandas_ai = pdai(llm=llm)

**Error:**
TypeError: __init__() got an unexpected keyword argument 'api_key'

I tried all different options including using 
**from pandasai.llm.falcon import Falcon**

and using different Keywords like 
**HUGGINGFACE_API_KEY**
**api_token**

but 'am getting errors

**Comment by mspronesti** [comment]
My bad. I linked the right line but wrote the wrong param (`api_key`). The correct name is `api_token` 

This works for me
```py
from pandasai.llm.starcoder import Starcoder

api_token = 'hf-...' # <--- your HF token here

llm = Starcoder(api_token=api_token)
pandas_ai = PandasAI(llm, verbose=True)
```
Would you prefer to have each parameter with the same naming convention of langchain ? e.g. `huggingface_api_key`, `openai_api_key`, `openai_api_base` etc. ? 
I'm about to propose a refactoring of both naming and packages.

**Comment by KoolSameer** [comment]
thanks for the response...

Yes, "I would prefer to have  each parameter with the same naming convention of langchain"
It would help in understanding which model we are using.

However, I am getting error...

I have added following libraries...
import pandasai as pdai
from pandasai.llm.starcoder import Starcoder

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 27
     25 api_token="MyAPIKye"
     26 llm = Starcoder(api_token=api_token)
---> 27 pandas_ai = pdai(llm=llm, verbose=True)

TypeError: 'module' object is not callable
--------------------------------------------------

not sure where I am going wrong.

**Comment by mspronesti** [comment]
I guess you have imported pandasai like this

 ```py
import pandasai as pdai
```

If It is the case you gotta instanciate the `pandas_ai` object like this 

```py
pandas_ai = pdai.PandasAI(llm=llm, verbose=True)
```

`pandasai` is the name of the module. The engine is called `PandasAI`

**Comment by KoolSameer** [comment]
Perfect...

This worked 

Thanks for all the help
