### ISSUE TITLE
Add feedback loop if the code fails to execute

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#4]
We should add a retry mechanism so that if the code fails to be executed and an error occurs, the llm self-improves.
We should also add a max_retry variable that defaults to 3 so that we don't run in infinite loops.

**Comment by yzaparto** [comment]
I can work on this :)

**Comment by gventuri** [comment]
Sounds great @yzaparto, just assigned to you! :)

**Comment by gventuri** [comment]
P.s. @yzaparto, we are launching the discord server, in particular for the contributors, but more in general for everyone interested into playing around with PandasAI!

If you are interested:
https://discord.gg/kF7FqH2FwS
