### ISSUE TITLE
Change parameters for Starcoder

### ISSUE THREAD

**Issue by pst2154** [gventuri/pandas-ai#403]
### 🚀 The feature

I cant figure if you can change the temperature or control the max_new_tokens 

### Motivation, pitch

sometimes the response is too short from the LLM

**Comment by gventuri** [comment]
@pst2154 as far as I know there's no such a param with the inference API by hugging face. Unfortunately, the free version only generates few token at a time, so we basically chain several calls to generate more code. For now the default param is 5, which means it will perform a max of 5 calls. As of https://github.com/gventuri/pandas-ai/commit/7b0ae26966adadf13e820fedcb030ff197e968aa, I've added the chance to increase the params, passing a custom `max_retries=X` when you declare the hugging face model.
Use it carefully, too many calls might cause some issues.
