### ISSUE TITLE
Raise "TypeError" when trying to save cache

### ISSUE THREAD

**Issue by nautics889** [gventuri/pandas-ai#416]
### 🐛 Describe the bug

There is some problem when saving cache for `PandasAI`. This behavior was describe in [comments under issue #400](https://github.com/gventuri/pandas-ai/issues/400#issuecomment-1653987621). So i'll refer to the code, which i've left in those comments.
___

_main.py_:
```python
import pprint

import pandas as pd
from pandasai import PandasAI

# Sample DataFrame
df = pd.DataFrame({
    "house": ["a", "b", "c"],
    "happiness_index": [6.94, 7.16, 6.66],
	"people": [['abby', 'ben'], ['ken'], ['ian']]
})

# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI()

pandas_ai = PandasAI(llm)
pandas_ai.clear_cache()

response = pandas_ai.run(df, prompt='Which house has at least two people?')
print(response)
print("=" * 79)
pprint.pprint(pandas_ai.logs)
```

_Output_:
```
0    a
Name: house, dtype: object
===============================================================================
[{'level': 20, 'msg': 'Question: Which house has at least two people?'},
 {'level': 20, 'msg': 'Running PandasAI with openai LLM...'},
 {'level': 20, 'msg': 'Prompt ID: d468be57-caee-4d34-a246-4d5ec3b857b6'},
 {'level': 20,
  'msg': '\n'
         '                        Code generated:\n'
         '                        ```\n'
         '                        import pandas as pd\n'
         '\n'
         "data = {'house': ['c', 'b', 'a'],\n"
         "        'happiness_index': [7.16, 6.94, 6.66],\n"
         "        'people': [['ken'], ['abby', 'ben'], ['ian']]}\n"
         '\n'
         'df = pd.DataFrame(data)\n'
         '\n'
         "houses_with_two_people = df[df['people'].apply(lambda x: len(x) >= "
         "2)]['house']\n"
         '\n'
         'print(houses_with_two_people)\n'
         '                        ```\n'
         '                    '},
 {'level': 20,
  'msg': '\n'
         'Code running:\n'
         '```\n'
         "data = {'house': ['c', 'b', 'a'], 'happiness_index': [7.16, 6.94, "
         "6.66], 'people': [['ken'], ['abby', 'ben'], ['ian']]}\n"
         "houses_with_two_people = df[df['people'].apply(lambda x: len(x) >= "
         "2)]['house']\n"
         'print(houses_with_two_people)\n'
         '```'},
 {'level': 20, 'msg': 'Answer: 0    a\nName: house, dtype: object'},
 {'level': 20, 'msg': 'Executed in: 5.421868562698364s'}]
Exception ignored in: <function Shelf.__del__ at 0x0000023B2669A7A0>
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 162, in __del__
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 144, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 172, in sync
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _Database.close at 0x0000023B27D17880>
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 275, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable

Process finished with exit code 0
```
To be more accurate, problem is represented by this logs:
```
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 162, in __del__
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 144, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\shelve.py", line 172, in sync
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _Database.close at 0x0000023B27D17880>
Traceback (most recent call last):
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 275, in close
  File "***\AppData\Local\Programs\Python\Python311\Lib\dbm\dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
```
___

_Notes:_

1. The problem was found by me and @AlexandreSajus. And there is a common thing in the contexts: Win platform. So, perhaps, it could be related to how the `shelve` module works on Windows.
2. The problem can be avoided by passing `enable_cache=False` flag to `PandasAI` class when instantiating.

**Comment by nautics889** [comment]
According to logs the problem arises from dbm's [`_commit()`](https://github.com/python/cpython/blob/main/Lib/dbm/dumb.py#L121) method. It is unable to access `unlink()` of os module since it's None. And it's quite interesting that in dbm the `os` and the `io` packages from stdlib ain't imported "as usual", rather be [bound to the class of Database](https://github.com/python/cpython/blob/main/Lib/dbm/dumb.py#L42) to  avoid references for global context.
Well, that seems too deep for resolving the issue. Anyway, if the problem occures only when shelve's `__del__()` and `close()` method are called, perhaps it should be fixed by modifying our [`close()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/helpers/cache.py#L59) and [`clear()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/helpers/cache.py#L64) (from cache.py helper) somehow. But i'm stucked with that — have been playing around for an hour, out of ideas.

_Notes:_ 
* As was mentioned, appears only on Win platform (tested on WSL with Ubuntu 22 and baremetal with Debian, working correctly)
* Exceptions are not raised when running with debug mode. This one blowed my mind most. Have tried debugger of PyCharm and python's `pdb`, error not caught in those cases (as well as no error logs).

:/

**Comment by gventuri** [comment]
@nautics889 thanks a lot for the investigation. I think we should either figure out in which cases this happen, to see if there's a easy fix or evaluate migrating to a different library.

**Comment by nautics889** [comment]
I've noticed there appeared a new implementation of caching mechanism with `duckdb` ([`cache.py`](https://github.com/gventuri/pandas-ai/blob/0eca724461843a272eeac929df042d4db52160be/pandasai/helpers/cache.py)). I guess this should repair a problem of the thread. Will check it AFAIK, if everything is OK, the current issue can be closed.

**Comment by gventuri** [comment]
Yes, I hope this should be enough to fix it, but unfortunately I cannot reproduce it. If anyone affected could check it out and let me know, then we can close the issue :)

**Comment by nautics889** [comment]
@gventuri 
I haven't seen this `TypeError` since that update with duckdb (neither with `enable_cache=True`, nor with `enable_cache=False`), i guess we can close the issue.
Thank you!
