### ISSUE TITLE
Enforce privacy doesn't work when sending multiple dataframes

### ISSUE THREAD

**Issue by adzafirov** [gventuri/pandas-ai#418]
### 🐛 Describe the bug

Apologies in advance, this is my first time raising issues on github, please feel free to give me pointers.

I was testing the package with enforce_privacy = True, which worked fine when sending a single dataframe.

However, it doesn't work for multi dataframes , this is because of this part of the code doesn't take into account rows_to_display when anonymize_df=True:

```
  if multiple: 
                    heads = [
                        anonymize_dataframe_head(dataframe)
                        if anonymize_df
                        else dataframe.head(rows_to_display)
                        for dataframe in data_frame
                    ]

```

Even when you run it with anonymize_df=False, it describes dataframes as having 0 rows to the LLM, unlike in the single dataframe case. This results in poor answers. Changing this:

```
Dataframe df{i}, with {row} rows and {col} columns.
This is the metadata of the dataframe df{i}:
{dataframe}"""
```

to this:

```
This is the metadata of the dataframe df{i}:
{dataframe.to_csv(index=False)}"""
```
so it's closer to the single dataframe case solves the problem.

**Comment by gventuri** [comment]
@adzafirov thanks a lot for reporting! Do you by chance want to pick this issue and submit a PR to fix it or you prefer us to work on it?

**Comment by adzafirov** [comment]
Sure, I made the PR with two simple changes.
