### ISSUE TITLE
Support for AzureOpenAI

### ISSUE THREAD

**Issue by bhishanpdl** [gventuri/pandas-ai#434]
### 🚀 The feature

Recently I came across this project and decided to play with it. Currently, I only have the AzureOpenAI subscription, and not the OpenAI subscription.

Can we pass the `llm` parameter as a instance of `AzureChatOpenAI` instead of default `OpenAI` llm model?

### Motivation, pitch

Motivation: I have only the AzureOpenaAI subscription, and the LLM created there does not work well with pandasai.

**Comment by gventuri** [comment]
@bhishanpdl sure, we support several LLMs.

You can find more info about how to implement Azure in the documentation:
https://pandas-ai.readthedocs.io/en/latest/llms/#azure-openai

If you have any questions, just let me know!

**Comment by bhishanpdl** [comment]
Thanks a lot, I can see AzureOpenAI, is there also AzureChatAI?

I have successfully used llm with AzureChatAI, but somehow AzureOpenAI is giving me API key not found in this pandas-ai case:

```python
from pandasai import PandasAI
from pandasai.llm.azure_openai import AzureOpenAI

llm = AzureOpenAI(
    api_key=config['openai_api_key'],
    api_base=config['openai_api_base'],
    api_version=config['openai_api_version'],
    deployment_name=config['openai_deployment_name']
)
```

Is there something like:
```
from langchain.chat_models import AzureChatOpenAI
```

**Comment by bhishanpdl** [comment]
This works perfectly. Thanks @Omarelsherif010 We can close the issue.

Here is the full code that works:

```python
# imports
import pandas as pd
from pandasai import PandasAI
from pandasai.llm.azure_openai import AzureOpenAI

# sample data
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# get config dictionary
config = {'required keys': 'required values'}

# Instantiate a LLM
llm = AzureOpenAI(
    api_token=config['openai_api_key'],
    api_base=config['openai_api_base'],
    api_version=config['openai_api_version'],
    deployment_name=config['openai_deployment_name']
)


pandas_ai = PandasAI(llm)
pandas_ai(df, prompt='Which are the 5 happiest countries?')
```
