### ISSUE TITLE
_is_df_overwrite function only checks the first target of assignments

### ISSUE THREAD

**Issue by aymanehachcham** [gventuri/pandas-ai#435]
### 🐛 Describe the bug

Hello,

I've been working with the `pandasai` package and noticed a potential oversight in the `_is_df_overwrite` function.

Here's the function for reference:

```python
def _is_df_overwrite(self, node: ast.stmt) -> bool:
    """
    Remove df declarations from the code to prevent malicious code execution.

    Args:
        node (object): ast.stmt

    Returns (bool):
    """

    return (
        isinstance(node, ast.Assign)
        and isinstance(node.targets[0], ast.Name)
        and re.match(r"df\d{0,2}$", node.targets[0].id)
    )
```

The issue arises here: 
```python
and isinstance(node.targets[0], ast.Name)
```

In the current implementation, only the first target is checked, potentially missing other assignments that could overwrite the DataFrame variable. I also experienced that with some prompts, where the output code still has a reassignment, it also contributes to higher API overhead. I would also suggest to  check for targets with different variable names than ```df```.  

I would suggest an implementation where all targets in an assignment statement are checked, ensuring that no potential DataFrame overwrites are missed. An example could be the following:
```python
def _is_df_overwrite(self, node: ast.stmt) -> bool:
    """
    Remove df declarations from the code to prevent malicious code execution.

    Args:
        node (object): ast.stmt

    Returns (bool):

    """
    if not isinstance(node, ast.Assign):
        return False

    for target in node.targets:
        if isinstance(target, ast.Name) and re.match(r"(df\d{0,2}|data)$", target.id):
            return True

    return False
```

I can create a PR for that, please let me know.

**Comment by gventuri** [comment]
@aymanehachcham that's a very good point! Thanks a lot for pointing that out. Would love if you could open a PR 🙏

**Comment by aymanehachcham** [comment]
Thanks for the reply, I'm on it.
