### ISSUE TITLE
Unfortunately, I was not able to answer your question, because of the following error:  'question'  I am still getting this error with the latest version of pandasAI which is 0.8.2

### ISSUE THREAD

**Issue by praveentn** [gventuri/pandas-ai#437]
### 🐛 Describe the bug

Using pandasai default code for question answering from multiple dataframes. Using OpenAI models. Getting this error -

Unfortunately, I was not able to answer your question, because of the following error:

'question'

I am still getting this error with the latest version of pandasAI which is 0.8.2.

Last error: "question"

**Comment by gventuri** [comment]
@praveentn @carpenterandy could you share the log? To do so, you can either run it with `verbose=True` or by checking the `pandasai.log` file!

**Comment by Omarelsherif010** [comment]
Hi
I have replicated your code on my machine and it worked well, so can you try updating pandasai version to the last one and try again to see if the error continues to appear?

The current version I am using is 0.8.3

**Comment by carpenterandy** [comment]
Can confirm it now works with 0.8.3 for both OpenAI and Azure OpenaAI. Thank you!

**Comment by gventuri** [comment]
Great, thanks a lot for letting us know @carpenterandy! Closing!
