### ISSUE TITLE
data type 'Int64' not understood

### ISSUE THREAD

**Issue by alikhanak123** [gventuri/pandas-ai#438]
### 🐛 Describe the bug

so for this code 

import os
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI

llm = OpenAI(api_token="sk-Zyq9QxxMZQtFRQQwEHGUT3Blb")

pandas_ai = PandasAI(llm)

import pandas as pd

df = pd.read_csv(r"D:\netflix.csv", index_col=0)
df.head(3)

pandas_ai.run(df, prompt='What are 5 highest user ratinglevel')

I get this error "data type 'Int64' not understood
"Unfortunately, I was not able to answer your question, because of the following error:\n\ndata type 'Int64' not understood\n""

i checked my data type its this 

rating         object
ratinglevel    object
dtype: object

Please help me with this

**Comment by Omarelsherif010** [comment]
Hi @alikhanak123 
I tried to replicate your code to solve the error but when I run the code, it works well on collab. I used this [dataset ](https://github.com/datacamp/community-groupby/blob/master/data/chasewillden-netflix-shows/data/netflix.csv)

So please try again and if the error continues to appear, kindly send me the data you are using.

**Comment by alikhanak123** [comment]
> Hi @alikhanak123 I tried to replicate your code to solve the error but when I run the code, it works well on collab. I used this [dataset ](https://github.com/datacamp/community-groupby/blob/master/data/chasewillden-netflix-shows/data/netflix.csv)
> 
> So please try again and if the error continues to appear, kindly send me the data you are using.

I don't know I am unable to understand, what could be different on my machine. I am Using jupyter notebook, i also tried Pc charm but still got same error. 😐

**Comment by alikhanak123** [comment]
> 



> Hi @alikhanak123 I tried to replicate your code to solve the error but when I run the code, it works well on collab. I used this [dataset ](https://github.com/datacamp/community-groupby/blob/master/data/chasewillden-netflix-shows/data/netflix.csv)
> 
> So please try again and if the error continues to appear, kindly send me the data you are using.

Hello @Omarelsherif010 ,  I once again used your dataset, earlier also I had used the same. I have the same error. refer to screenshot I am attaching. I am using Jupyter notebook. I tried PC charm as well. I may have to try a different laptop and see if it has anything to do with my laptop.

![Screenshot 2023-08-13 073056](https://github.com/gventuri/pandas-ai/assets/80671468/cc0ceb1a-bcc2-47ea-a357-852b1e2d0f1a)

**Comment by Omarelsherif010** [comment]
I think you may be using an older version of the pandasai so try to update your version and then try your code again.

You can write this command directly on your Jupyter Notebook `! pip install --upgrade pandasai`

**Comment by alikhanak123** [comment]
> I think you may be using an older version of the pandasai so try to update your version and then try your code again.
> 
> You can write this command directly on your Jupyter Notebook `! pip install --upgrade pandasai`
> 
> let me know if this will solve it🤝

I upgraded pandasai but no difference , I will try on a different machine thats the last thing left to do.

![image](https://github.com/gventuri/pandas-ai/assets/80671468/6a6098b2-2da3-4aba-9842-9fadd645b8f2)

**Comment by alikhanak123** [comment]
I reinstalled my anaconda and python and the error got resolved. Thanks @Omarelsherif010 for your efforts to help me.
