### ISSUE TITLE
Add graph support for gradio

### ISSUE THREAD

**Issue by arian81** [gventuri/pandas-ai#449]
### 🚀 The feature

Similar to streamlit, gradio needs a middleware to be able to output graphs. 

### Motivation, pitch

Support for gradio

**Comment by arian81** [comment]
I already have the code for this. I created the issue to link it to the pr

**Comment by Giovo17** [comment]
Any news?

**Comment by arian81** [comment]
> Any news?

They changed the entire structure of graph generation and now it stores the file locally. Having a middleware doesn't really make sense anymore.
