### ISSUE TITLE
question with current date

### ISSUE THREAD

**Issue by Ink6220** [gventuri/pandas-ai#45]
hi there, I was playing around with your project it's amazing but found some problems when using it with scheduled data  

when I try to ask questions that relate to the current time like "What is today's work"," Who has work tomorrow", and "Who had a shift yesterday"

I try to use prompts like "today date is 4/22/2023........" or  "use datetime.now() to know current DateTime..."
it works well sometimes but sometimes it gives me a hallucination answer 

so, it might be a great idea if you add this feature to your project

**Comment by QuantumPickleJar** [comment]
Interesting, will play with some more chronological questions.  
If you wrap the date with something, (e.g { }, [ ], ( ), " ", ' ') does that help curb hallucinations?

**Comment by Ink6220** [comment]
Regrettably, That doesn't seem to help much. I think we have to change the inside prompt
```python
prompt = """

There is a dataframe in pandas (python).
The name of the dataframe is `df`.
This is the result of `print(df.head(0))`:
Empty DataFrame
Columns: []
Index: [].
Return the python code (do not import anything) and make sure to prefix the python code with <startCode> exactly and suffix the code with <endCode> exactly 
to get the answer to the following question: """
```

**Comment by gventuri** [comment]
@Ink6220 sounds like a very important feature to have. We'll add it asap, thanks for suggesing!

**Comment by gventuri** [comment]
Fixed by https://github.com/gventuri/pandas-ai/commit/48ee6758682a135e2f2ed117d3c1de9712dd2f7a, closing
