### ISSUE TITLE
cannot instantiate PandasAI()

### ISSUE THREAD

**Issue by kchusam** [gventuri/pandas-ai#453]
### 🐛 Describe the bug

After the update to v1.0.1 and v1.0.2, I'm trying to instantiate PandasAI class and I'm getting the following error.

`pandas_ai = PandasAI(llm)

pandas_ai.run(df, prompt='Which are the 5 happiest countries?')`

`--->  pandas_ai = PandasAI(llm)
     

TypeError: Can't instantiate abstract class PandasAI with abstract method chat`

why is this not possible anymore or is it a bug?

Thank you!

**Comment by ivanyou028** [comment]
I'm getting the exact same error

**Comment by leehanchung** [comment]
It's too much of a breaking change. But either way, try to do this

```py
from langchain.chat_models import ChatOpenAI
from pandasai.llm import LangchainLLM

langchain_llm = ChatOpenAI()
llm = LangchainLLM((langchain_llm=langchain_llm)
pandas_ai = PandasAI(
    llm=llm,
    <rest of the old interface>>
)

pandas_ai.run(
    data_frame=df,
    prompt="this is a prompt"
)
```
```

**Comment by kchusam** [comment]
Hi, thank you very much and sorry for the late reply. I just instantiated pandasai class on pandasai 1.1.2 and it worked.
