### ISSUE TITLE
Hugging Face not working in PandasAI

### ISSUE THREAD

**Issue by AkashRajpuria** [gventuri/pandas-ai#454]
### 🚀 The feature

According to the official Documentation ,I tried to use Falcon with PandasAI it gave the following error

### Motivation, pitch

from pandasai import SmartDataframe
from pandasai.llm import Starcoder, Falcon

llm = Falcon(api_token="hf_VKiZuUwWDummyZkxG")

df = SmartDataframe("emp_recs_dontchange.csv", config={"llm": llm})

df.chat("what is the average salary")

### Additional context

"""
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 293, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 197, in execute_code
    return analyze_data(self._get_original_dfs())
TypeError: 'NoneType' object is not callable
Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n
"""
Anybody can help me with this

**Comment by gventuri** [comment]
@AkashRajpuria should have been fixed now with 1.0.4.
It's still very slow, but we are working on possible ways to optimize it!
