### ISSUE TITLE
Crash if I ask to generate some graph

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#463]
### 🐛 Describe the bug

I use typical titanik csv for testing (but attached to have the same version).
[titanic.csv](https://github.com/gventuri/pandas-ai/files/12385617/titanic.csv)

load data:
    df = pd.read_csv('./data_examples/titanic.csv')

LLM is turbo-3.5:
  MODEL_NAME = "gpt-3.5-turbo"
  llm = OpenAI(api_token= LLM_OPENAI_API_KEY, model = MODEL_NAME, temperature=0, max_tokens=2000)

ask data:
111            pandas_ai = PandasAI(llm)
112            result = pandas_ai.run(df, prompt="Plot the histogram of age and class")

and I have exception:

Error: list indices must be integers or slices, not str. Track: Traceback (most recent call last): File "C:\DiskD\GptPOCs\AskYourDataPOC\main.py", line 112, in <module> result = pandas_ai.run(df, prompt="Plot the histogram of age and class") File "d:\Anaconda3\lib\site-packages\pandasai_init_.py", line 195, in run return self.dl.chat(prompt) File "d:\Anaconda3\lib\site-packages\pandasai\smart_datalake_init.py", line 327, in chat self.add_result_to_memory(result) File "d:\Anaconda3\lib\site-packages\pandasai\smart_datalake_init.py", line 335, in _add_result_to_memory if result["type"] == "string": TypeError: list indices must be integers or slices, not str

When I use new code:

       smart_df = SmartDataframe(df, config={
                        "llm": llm, 
                        "conversational": False, 
                        "enable_cache": False
                    })
        result = smart_df.chat(question)

I just have None as result.

**But** - I have temp_chart.png in folder `exports/charts`.

**Comment by PavelAgurov** [comment]
Please find test here https://colab.research.google.com/drive/15WniinCDUd_tL_z6APwEqQTXcbD9nVq2?usp=sharing

**Comment by PavelAgurov** [comment]
![image](https://github.com/gventuri/pandas-ai/assets/37487002/55a5d501-067d-46e7-a8d9-d06171c2d68a)

**Comment by PavelAgurov** [comment]
When I run it second time - it works.

**Comment by PavelAgurov** [comment]
And crashed when I ask other request with the same error.

![image](https://github.com/gventuri/pandas-ai/assets/37487002/0b35e056-b895-4515-91dc-fe13e1e046c6)

**Comment by gventuri** [comment]
@PavelAgurov this was to a bug related to multiturn feature causing hallucinations. We've now fixed it by temporarily disabling the feature! Should work now, closing!
