### ISSUE TITLE
Bug in Logger

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#464]
### 🐛 Describe the bug

Field _logs is defined as list of string:

class Logger:
    """Logger class"""

    _logs: List[str]

but in fact it's list of dict:

        self._logs.append({"msg": message, "level": level})

Also property save_logs has not the best name as it's verb. I read it as "save logs to some storage". I guess better call it "get_save_logs_flag" or "save_logs_flag"

**Comment by gventuri** [comment]
@PavelAgurov thanks a lot for reporting, I've fixed it (5703303)! :) Closing!
