### ISSUE TITLE
User Defined Path save chart problem

### ISSUE THREAD

**Issue by Ridoy302583** [gventuri/pandas-ai#473]
### 🐛 Describe the bug

when i want to save any chart or plot in my specified path  then Generated code is:
code generated: def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    df = dfs[0]
    age_data = df['Age'].dropna()
    plt.hist(age_data, bins=10)
    plt.xlabel('Age')
    plt.ylabel('Count')
    plt.title('Histogram of Age')
    plt.savefig('exports/charts/temp_chart.png')
    plt.close()
    return {'type': 'plot', 'value': 'exports/charts/temp_chart.png'}

result = analyze_data(dfs)
Answer:None

in here plot saved into  exports/charts/temp_chart.png  here. but i want to save in my specified path. Path 
not created any UUID folder to save this Chart or plot. But i want to save my plot within a UUID folder. when create a plot or chart or sometime answer is None but i need conversational Answer like here is the chart with chart description.

This is my code:
class MyCustomCallback(BaseCallback):
    def on_code(self, response: str):
        print(f"generated code from llm: {response}")

user_defined_path = os.getcwd()
save_charts_path = os.path.join(user_defined_path, 'R', 'r')

df = SmartDataframe(
    "titanic.csv",
    config={
        "llm": llm,
        "save_charts_path": save_charts_path,
        "save_charts": True,
        "conversation": True,
        "enable_cache": False,
        "verbose": False,
        "use_error_correction_framework": True,
        # "callback": MyCustomCallback()
    }

**Comment by gventuri** [comment]
@Ridoy302583 thanks a lot for reporting, this issue has been solved as of `v1.0.8`. Closing!
