### ISSUE TITLE
Create a way in order to customize the parser of the result

### ISSUE THREAD

**Issue by lenard123** [gventuri/pandas-ai#480]
### 🚀 The feature

It would be better if the we are able to return the Actual dictionary result in order to make a customization to the handler of the result instead of just spitting the output.

### Motivation, pitch

I am using pandasai in an API so it would be better if I get the dictionary result in order for me to control the exact output that I want

**Comment by jrcastropy** [comment]
Any new for this one? I kinda need this one too.
