### ISSUE TITLE
Description of each SmartDataFrame in SmartDataLake.

### ISSUE THREAD

**Issue by maksim-melaxtech** [gventuri/pandas-ai#484]
### 🚀 The feature

Pass description of each SmartDataFrame in SmartDataLake _load_dfs function

### Motivation, pitch

Custom Description is implemented in SmartDataFrame but missing in SmartDataLake.

**Comment by gventuri** [comment]
@maksim-melaxtech thanks a lot for reporting. What I recommend is to instantiate multiple smart dataframes and pass them to the lake, like this:

```
users_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "name": ["John", "Emma", "Liam", "Olivia", "William"]
    }
)
users = SmartDataframe(users_df, name="users", description="Lorem ipsum")

photos_df = pd.DataFrame(
    {
        "id": [31, 32, 33, 34, 35],
        "user_id": [1, 1, 2, 4, 5]
    }
)
photos = SmartDataframe(photos_df, name="photos", description="Lorem ipsum")

lake = SmartDatalake([users, photos], config={"llm": llm})
lake.chat("How many photos has been uploaded by John?")
```

Having the datalake accepting this feature might be a little bit "rusty" as an approach, as you'd probably expect a ordered list of description.

Let me know if it makes sense to you and if the current solution works for you!

**Comment by maksim-melaxtech** [comment]
Makes sense, thanks a lot! :)
