### ISSUE TITLE
Adding Dataframe Configuration Loading from SmartDataframe

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#491]
### 🚀 The feature

This issue is related to https://github.com/gventuri/pandas-ai/issues/490

Subject: Feature Enhancement: Load Configuration for Existing Dataframes in SmartDataframe Instantiation

**Issue Description:**
This feature add to the SmartDataframe the chance to load saved configurations for a df. This feature will simplify the process of working with previously saved dataframe configurations and improve the overall user experience.

**Feature Details:**
Currently, SmartDataframe allows users to save dataframe configurations using the `.save()` method, creating a JSON representation of the dataframe's settings. We would like to introduce the ability to load these configurations when a SmartDataframe instance is instantiated, provided that the dataframe's name is specified.

1. **Instantiation with Existing Dataframe Name:**
   When a SmartDataframe is instantiated with a specific name, e.g., `df = SmartDataframe('photo')`, the library should:
   
   - Check if a dataframe with the given name exists in the `saved_dfs` list within the `pandasai.json` file.
   
   - If a match is found:
     - Load the settings from the configuration object, including `_name`, `_description`, and `_sample_head`.
     - Load the dataframe from the `import_path` specified in the configuration.
     - Return a SmartDataframe instance with the loaded settings and dataframe.

2. **Fallback to Regular Instantiation:**
   If no match is found for the given name, the SmartDataframe should be instantiated as usual, without loading any settings or dataframe.

**Example Scenario:**
Assuming a saved configuration in `pandasai.json`:
```json
{
  "name": "photo",
  "description": "Dataframe containing photo metadata",
  "sample": "filename,format,size\nphoto1.jpg,JPEG,1240KB\nphoto2.png,PNG,320KB",
  "import_path": "path/to/photo_data.csv"
}
```

When `df = SmartDataframe('photo')` is called, the settings are loaded, and the dataframe is imported from `"path/to/photo_data.csv"`.

**Implementation Guidelines:**
1. Enhance the SmartDataframe instantiation logic to handle loading configurations based on the provided name.
2. Implement the steps outlined above for loading settings and dataframes.
3. Ensure that when the name is not found, the instantiation process remains unchanged.

**Impact:**
This enhancement will streamline the process of working with previously saved dataframe configurations. Users will be able to quickly instantiate SmartDataframes with the configurations they have saved earlier, promoting ease of use and efficiency.

Reference:
For the exact file path to the pandasai.json file, refer to df_config.py, line 44.

**Note:**
Feel free to provide any additional suggestions or modifications to this proposal. We believe that implementing this feature will add valuable functionality to the SmartDataframe library.

### Motivation, pitch

We need a way to make it easier to save/load the settings of a smart dataframe.

**Comment by henry-on-the-internet** [comment]
Hi @gventuri 
I have a few question about the feature description.

Is the `_sample_head`'s value as the same as the first line in the `sample` field in  `pandasai.json` ?
Take the `photo` as an example, the sample head is `filename,format,size`. Is it correct?

Is it possible that there are multiple saved configurations having the same `name` in the `saved_dfs` list? 
If yes, how will we choose one of them to load the data?

**Comment by gventuri** [comment]
Hi @henry-on-the-internet, _sample_head is actually a string of the csv of the sample dataframe.

There cannot be multiple configurations with the same name and name is case sensitive!

Let's know if you have any further questions 😄
