### ISSUE TITLE
non_default_prompts context and details NOT showing up in pandasai.log

### ISSUE THREAD

**Issue by ronaldsholt** [gventuri/pandas-ai#495]
### 🐛 Describe the bug

I am testing non_default_prompts using SDL and SDF. While running the examples provided in the docs, I noticed the standard prompt instructions are still populating in the pandasai.log. This leads me to believe that my prompt is not being executed, but I have no way to confirm as there are no other errors. 

This is an example of the custom prompt class and code for execution:

```python
    class CustomMarketSharePrompt(Prompt):
        text = """
        You are provided with a dataset that contains sales data by brand across various regions. Here's the metadata for the given pandas DataFrames:

        {dataframes}

        Given this data, please follow these steps:
        1. **Data Analysis**: < custom instructions >
        2. **Opportunity Identification**: < custom instructions >
        3. **Reasoning**: < custom instructions >
        4. **Recommendations**: < custom instructions >
        5. **Output**: Return a dictionary with:
        - type (possible values: "text", "number", "dataframe", "plot")
        - value (can be a string, a dataframe, or the path of the plot, NOT a dictionary)
        Example: {{ "type": "text", "value": "The X region has seen a 20% growth in the last quarter, indicating a potential market for Brand X." }}

        Using the provided dataframes (`dfs`), update the Python code based on the user's query:
        {conversation}

        # Updated code:
        # """
```
And to execute: 

```python
 # Creating SmartDataLake
    sdl = SmartDatalake([sdf_sales_continent], config={"llm": llm, "non_default_prompts": {"generate_python_code": CustomMarketSharePrompt}})
```

Then, when checking the log file I get the standard messaging from the base prompt:

```python
2023-08-26 13:04:30 [INFO] Question: < My query >
2023-08-26 13:04:30 [INFO] Running PandasAI with openai LLM...
2023-08-26 13:04:30 [INFO] Prompt ID: 77133e2b-17f9-4e26-9876-6784d8566394
2023-08-26 13:04:44 [INFO] 
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
```

There are no error messages, and results are generated... So it seems like I am implementing it wrong, or there is a bug not populating the pandasai.log property. Additionally, I test for this would be helpful. Thanks!

**Comment by gventuri** [comment]
Hi @ronaldsholt, thanks a lot for reporting.

I've just released a new version of the custom prompts, as the previous implementation had become too chaotic.

Here's a working example. Hope it helps.

```python
import pandas as pd
from pandasai import SmartDataframe
from pandasai.prompts import Prompt

# # Custom Prompts
class CustomAnalysisPrompt(Prompt):
    text = """
You are provided with a dataset that contains sales data by brand across various regions. Here's the metadata for the given pandas DataFrames:

{dataframes}

Given this data, please follow these steps:
0. Acknowledge the user's query and provide context for the analysis.
1. **Data Analysis**: < custom instructions > 
2. **Opportunity Identification**: < custom instructions > 
3. **Reasoning**: < custom instructions > 
4. **Recommendations**: < custom instructions > 
5. **Output**: Return a dictionary with:
   - type (possible values: "text", "number", "dataframe", "plot")
   - value (can be a string, a dataframe, or the path of the plot, NOT a dictionary)
   Example: {{ "type": "text", "value": < custom instructions > }}
``python
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
   # Code goes here (do not add comments)

# Declare a result variable
result = analyze_data(dfs)
``

Using the provided dataframes (`dfs`), update the Python code based on the user's query:
{conversation}

# Updated code:
# """

df = pd.DataFrame({
    "brand": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "region": ["North America", "North America", "North America", "North America", "North America", "Europe", "Europe", "Europe", "Europe", "Europe"],
    "sales": [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
})

# Creating SmartDataFrames
sdf_sales_continent = SmartDataframe(
    df,
    name="df",
    config={
        "custom_prompts": {
            "generate_python_code": CustomAnalysisPrompt(),
        }
    }
)
res = sdf_sales_continent.chat("What is the average sales by continent?")
```

If you have any questions, just ping me.

**Comment by ronaldsholt** [comment]
Thanks, @gventuri ... I just installed v1.0.11; Posting the log as it related to #425. Hard to verify if your prompt is working if it is not if not in the log. I've use the example above and put in arbitrary instructions to show a sign in the output, but it just doesn't appear to be working (Sorry if missing something!!) 

```python
2023-08-29 20:48:21 [INFO] Question: What is the average sales by continent?
2023-08-29 20:48:21 [INFO] Running PandasAI with azure-openai LLM...
2023-08-29 20:48:21 [INFO] Prompt ID: adb5fce3-75a3-4ca0-b026-55e7bab99182
2023-08-29 20:48:21 [INFO] Using cached response
2023-08-29 20:48:21 [INFO] 
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    df = dfs[0]
    df = df.groupby('region').mean()
    df = df.reset_index()
    return {"type": "dataframe", "value": df}

# Declare a result variable
result = analyze_data(dfs)
print(result['value'])
                    ```
                
2023-08-29 20:48:21 [INFO] 
Code running:
```
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    df = dfs[0]
    df = df.groupby('region').mean()
    df = df.reset_index()
    return {'type': 'dataframe', 'value': df}


result = analyze_data(dfs)
print(result['value'])
        ```
2023-08-29 20:48:21 [INFO] Answer: {'type': 'dataframe', 'value':           region  sales
0         Europe  800.0
1  North America  300.0}
2023-08-29 20:48:21 [INFO] Executed in: 0.011768102645874023s
```

**Comment by ronaldsholt** [comment]
Thank you @gventuri -- Disregard the last note, it's working now. WooHoo! 👍

**Comment by ronaldsholt** [comment]
@gventuri Hey, one more related question... Using the same as above but with SmartDatalake getting an interesting error in v1.2.1

"Unfortunately, I was not able to answer your question, because of the following error:

single positional indexer is out-of-bounds"
