### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by Hemedbz** [gventuri/pandas-ai#5]
I saw on the TODO list that you'd like to add a CLI functionality, I'd like to do that, wanted to make sure it's okay before I start.

**Comment by gventuri** [comment]
@Hemedbz sounds great! I've assigned the task to you 🚀

**Comment by Hemedbz** [comment]
Great. thanks! Will update in a few days.

**Comment by gventuri** [comment]
Looking forward for it!

**Comment by gventuri** [comment]
Hey @Hemedbz, did you have a chance to have a look into it?

**Comment by Hemedbz** [comment]
Hi, sorry it's been a busy week... Working on it, and writing to you maybe
we can schedule a zoom this weekend?

**Comment by gventuri** [comment]
Closing, as it is a duplicate of #104. There is a PR for that (#107)
