### ISSUE TITLE
Google Sheets Feature request

### ISSUE THREAD

**Issue by stikkireddy** [gventuri/pandas-ai#53]
Hey can you use gspread or other frameworks so that we can run some cool prompt based analytics for pandas.

**Comment by gventuri** [comment]
Sounds like a very exciting feature @stikkireddy, will look into it!

**Comment by aryandgandhi** [comment]
Hey @gventuri I would love to look into this

**Comment by gventuri** [comment]
Hey @aryandgandhi, sounds super! Just assigned to you!

**Comment by aryandgandhi** [comment]
Awesome, just wanted to clarify @gventuri and @stikkireddy is the goal to pull in the google sheets data into a dataframe and run specific prompts, Ex. create a graph where each state is a different color?

**Comment by gventuri** [comment]
Yeah, would be a great starting point. Like we pull data from google sheets and convert to a dataframe that then we pass to PandasAI! @aryandgandhi

**Comment by gventuri** [comment]
Closing, we now have a different and more comprehensive issue for this #301
