### ISSUE TITLE
show_code = True

### ISSUE THREAD

**Issue by kchusam** [gventuri/pandas-ai#538]
### 🐛 Describe the bug

I would like to understand the code that pandasai generates but it seems that the argument show_code = True does not work neither for SmartDataFrame or nor for the old "run" method in pandasAI class. When I run the following code, I get the result but no code back. What I can do to view the code?
<img width="1353" alt="image" src="https://github.com/gventuri/pandas-ai/assets/141125520/fc90ed8b-f06f-4664-9354-f571163fc474">

**Comment by mspronesti** [comment]
The param is called `verbose`. If you need to export you code you can also consider using pandasai's `FileCallback`.
Refer to this other [comment](https://github.com/gventuri/pandas-ai/issues/458#issuecomment-1691310790) of mine for more.

**Comment by gventuri** [comment]
@kchusam hope the @mspronesti helped, closing! Feel free to reopen if you have any questions!
