### ISSUE TITLE
How to access logs in case of SmartDataLake ?

### ISSUE THREAD

**Issue by krishnashed** [gventuri/pandas-ai#540]
### 🐛 Describe the bug

While using the new SmartDatalake to query multiple dataframes, how can we get the logs of how the agent has arrived at a particular answer, like how we used to get it with agent.logs in PandasAI ?

**Comment by nautics889** [comment]
[See this](https://github.com/gventuri/pandas-ai/issues/542#issuecomment-1712584571)
