### ISSUE TITLE
Try-catch Yahoo Finance and SQLAlchemy imports

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#558]
### 🐛 Describe the bug

Hi @gventuri,
I've just had a look at the awesome additions of v1.2! I was wondering whether yahoo finance and sqlalchemy are marked as optional dependencies on purpose. If it is the case, we definitely need to try-catch the import and raise the exception to any user attempting to use them without installing the necessary dependency for that connector.

Before opening a PR, I thought it would have made sense to discuss with you - and anybody interested in this community - if this is actually the desired behavior. While I believe yahoo finance should be an optional dependency, I believe sqlalchemy could be a dependency of pandasai.

**Comment by nautics889** [comment]
Hi, @mspronesti !
As for me personally, i've also encountered on `ImportError` after pulling feature/v1.2 and trying to run tests, so i'm definitely in favor of it. Must be reasonable improvement.

**Comment by gventuri** [comment]
@mspronesti @nautics889 sure, sounds like a great idea!
I'd say we can make `sqlalchemy` a necessary dependency (since it's gonna be used in most of the use cases) while keeping yahoo finance as optional!

**Comment by mspronesti** [comment]
@gventuri alright, I will open a PR soon then!
@nautics889 thanks for your valuable feedback, much appreciated!
