### ISSUE TITLE
More Privacy by using local LLM !

### ISSUE THREAD

**Issue by Alias4D** [gventuri/pandas-ai#567]
### Discussed in https://github.com/gventuri/pandas-ai/discussions/566

<div type='discussions-op-text'>

<sup>Originally posted by **Alias4D** September 16, 2023</sup>
Can connect pandasai to local LLM like Llama or falcon ? as show in step below 
1 - deploy and serve local llm on your personal pc using llamaccp or  transformer .
2 - connect pandasai to local llm api created above 
3 - import dataframe and do chat . 

</div>

**Comment by LinyeLi60** [comment]
You can use Text Generation Inference to deploy falcon-7b-instruct, then use the TGI api to create llm.
