### ISSUE TITLE
Code not showing on Databricks notebook

### ISSUE THREAD

**Issue by FrancescoRettondini** [gventuri/pandas-ai#591]
### 🐛 Describe the bug

Hi, you can see in the image below that when I try to use `show_code = True`, there is no code shown in Databricks. 
How could I solve this?

Thanks
Francesco

![image](https://github.com/gventuri/pandas-ai/assets/92798799/8e3e0e00-ee07-4c29-82d3-6923cd7d81de)

**Comment by mspronesti** [comment]
I believe the specific parameter that you need to set is `verbose`.
Besides that, as explained in the warning message that you received, `PandasAI` (class) is deprecated. Use `SmartDataframe` instead.

**Comment by gventuri** [comment]
@FrancescoRettondini does it solve your issue?

**Comment by FrancescoRettondini** [comment]
@gventuri thanks I tried adding verbose into the  config, `sdf = SmartDataframe(df_adp, config={"llm": llm,"verbose": True})` but it didn't really work, it's just showing the output.

I can see the code when using `print(sdf.last_code_generated)`

**Comment by FrancescoRettondini** [comment]
@gventuri @mspronesti do you have any idea on how to solve this?

**Comment by FrancescoRettondini** [comment]
It seems the issue has been solved using in both SmartDataFrame and SmartDataLake the verbose = True. I'll close the issue, thanks!

**Comment by mspronesti** [comment]
@FrancescoRettondini so did `verbose=True` work for you?

**Comment by FrancescoRettondini** [comment]
@mspronesti  yes on both.
