### ISSUE TITLE
Update or delete CLI

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#605]
### 🚀 The feature

Looks like PAI hasn't been updated in months and that the current version is not compatible with pandas-ai >= 1.0. 
I suggest we either update it or remove it. 

I'm personally in favor of the second option, given the fact that not many people have used it since the beginning of this project and nobody has noticed/complained about it not working anymore.

**Comment by gventuri** [comment]
@mspronesti agreed, if no-one complained, this feature might not be needed. I agree we should remove it!
