### ISSUE TITLE
Streaming support for OpenAI responses

### ISSUE THREAD

**Issue by sahanxdissanayake** [gventuri/pandas-ai#612]
### 🚀 The feature

Would it be possible to have the OpenAI response be streamed to the frontend for better interactivity?

### Motivation, pitch

If the query takes long the user is waiting on the frontend without knowing what's happening. I'd like to stream the response ASAP

**Comment by gventuri** [comment]
@sahanxdissanayake thanks for asking. Unfortunately, by the way PandasAI is implemented, there's no such way to have the streaming implemented.
In fact, we need to parse the output before we return the solution, which means we cannot add the streaming feature. What you can do is a workaround where you animate it on the frontend as soon as you get the whole response.

**Comment by sahanxdissanayake** [comment]
Totally @gventuri! In my case the customers are asking to show how to output was created. I think I'm asking for two things here

1. As calculations happen, stream those to the frontend
2. Show users almost instant feedback on their actions

Hoping to build something similar https://www.usechannel.com/ in the end

**Comment by sahanxdissanayake** [comment]
To add more context I'm using the following code where I will need to parse multiple(around 6) data sources and then I need to make sure I clearly communicate how the output is created back to the customer

```
dl = SmartDatalake([employees_df, salaries_df], config={"llm": llm, "verbose": True})
```
