### ISSUE TITLE
In the Prompt head_csv is sent and it should be _sample_head

### ISSUE THREAD

**Issue by mavixRL** [gventuri/pandas-ai#617]
https://github.com/gventuri/pandas-ai/blob/b379d034f7b72c1bc3d2122ff5052222f9385696/pandasai/prompts/base.py#L55C5-L55C13

It should be like this:

```python
if df._sample_head is not None:
                description += f"""
This is the metadata of the dataframe dfs[{index-1}]:
{df._sample_head}</dataframe>"""  # noqa: E501
            elif df._sample_head is  None:
                description += f"""
This is the metadata of the dataframe dfs[{index-1}]:
{df.head_csv}</dataframe>"""  # noqa: E501
```

since it always sends the head by default and omits the user input.

**Comment by gventuri** [comment]
@mavixRL thanks a lot for reporting. Should have been fixed as of 1.3.2. Please check it out and let me know :)
