### ISSUE TITLE
Using with file-based sqlite

### ISSUE THREAD

**Issue by thefrisson** [gventuri/pandas-ai#651]
### Discussed in https://github.com/gventuri/pandas-ai/discussions/650

<div type='discussions-op-text'>

<sup>Originally posted by **thefrisson** October 16, 2023</sup>
The library documentation suggests that connecting to a sqlite database should be easy using SQLConnector (as that's what is given in the example), but I am looking to connect a simple file-based sqlite db, not a server hosted version. I tried to pass the SQLConnector config a filename and it pretty much said all of the parameters that are in the config in the example are required. But it seems like the logical progression for constructing something like this is to work on supporting file based databases first and then do mysql and postgres. I understand that there is a propensity to overlook and oversimplify examples when there's is a lot of functionality to show. So I am wondering if anyone knows of a way to configure the SQLConnector to accept a file that doesn't have a host, port, username, or password?</div>

**Comment by bsab** [comment]
Hey @gventuri 

could we consider closing this issue, given that the SqliteConnector is now available with the desired feature? The SqliteConnector was added in this [commit](https://github.com/gventuri/pandas-ai/commit/5569df04e97334e1f7ff5b1cda9b06c737674792).
