### ISSUE TITLE
Set the preferred visualization library

### ISSUE THREAD

**Issue by gventuri** [gventuri/pandas-ai#660]
### 🚀 The feature

We need to enhance the flexibility of our application by allowing users to choose their preferred data visualization library. This will not only improve the user experience but also make our application more versatile and appealing to a broader audience.

## Proposed Solution:

- Add a Config: Introduce a new configuration parameter in our application settings that allows users to define their preferred data visualization library (`matplotlib`, `seaborn`, or `plotly`). This setting should be easily accessible and modifiable by the user.
- Update the Prompt: Modify the application's user prompt to include a specific instruction.

### Motivation, pitch

At the moment the user has to specify in every prompt which library to use

**Comment by bsab** [comment]
Ciao @gventuri,
do you think that the type of plot depends on the value assumed by the **output_type** variable? If we indicate the type of plot only in the Config, do we then need to forcefully set the output_type to "plot"?

`    def chat(self, query: str, output_type: Optional[str] = None):
        """
        Run a query on the dataframe.

        Args:
            query (str): Query to run on the dataframe
            output_type (Optional[str]): Add a hint for LLM which
                type should be returned by `analyze_data()` in generated
                code. Possible values: "number", "dataframe", "plot", "string":
                    * number - specifies that user expects to get a number
                        as a response object
                    * dataframe - specifies that user expects to get
                        pandas/polars dataframe as a response object
                    * plot - specifies that user expects LLM to build
                        a plot
                    * string - specifies that user expects to get text
                        as a response object
                If none `output_type` is specified, the type can be any
                of the above or "text".

        Raises:
            ValueError: If the query is empty
        """
`

**Comment by gventuri** [comment]
Hey @bsab, not really! The idea is, when asked to generate a prompt, just using the preferred library. So only when plotting a chart, it will then use the provided library!

**Comment by bsab** [comment]
Ok, I'll give it a try and work on it. Thanks for the explanation!

**Comment by gventuri** [comment]
@bsab sounds great, do you want me to assign you the issue?

**Comment by bsab** [comment]
Yes, feel free to assign me the issue


Il giorno mar 24 ott 2023 alle 20:08 Gabriele Venturi <
***@***.***> ha scritto:

**Comment by gventuri** [comment]
@bsab just assigned to you!

**Comment by strangercacaus** [comment]
I'm new here so i might be highlighting something obvious, but pandas .plot() method has a 'backend' parameter that chooses the preffered dataviz library for that specific plot.

In this case it would be similarly defining that value for the whole active session, am i right?

**Comment by HenriqueAJNB** [comment]
@strangercacaus, I don't think it is that simple. The library is passed as a prompt to LLM models. The point is to make these preferable plot options get into a prompt message. There is a lot of full `matplotlib` code in prompts that must be adapted or changed to other types of plots.

Perhaps `matplotlib` should be the default, but the package should be flexible to handle other options in prompts.

**Comment by bsab** [comment]
Hello, I've created a Pull Request that closes issue #660. All tests have passed, but the PR is currently in draft status and requires a review before merging. 
Please take a look and provide feedback.
