### ISSUE TITLE
Fix: Error using enforce_privacy = True

### ISSUE THREAD

**Issue by mavixRL** [gventuri/pandas-ai#662]
https://github.com/gventuri/pandas-ai/blob/87dd966e52c21e6359f2797f80826cd49c6bd40f/pandasai/smart_dataframe/__init__.py#L436C57-L436C57

When using `enforce_privacy = True`
generates an error because it only sends the headers and when using `_truncate_head_columns` it tries to truncate 0 rows

so I propose the following:

```python
         if self.lake.config.enforce_privacy:
            return sampled_head
        else:
            return self._truncate_head_columns(sampled_head)
```
Instead of using:

```python
         return self._truncate_head_columns(sampled_head)
```
This avoids the errors reported by users who use `enforce_privacy = True`

**Comment by gventuri** [comment]
@mavixRL thanks a lot for reporting and for investigating. Do you want to submit a PR for this?

**Comment by ashishdatta** [comment]
hi @mavixRL I can submit a PR for this if needed!

**Comment by mavixRL** [comment]
@ashishdatta muchas gracias por enviar el PR, estuve desconectado durante unos días.
@gventuri ¿Crees que podrías agregarme como colaborador?

**Comment by mavixRL** [comment]
@ashishdatta thank a lot for submit the PR, I was offline for a few days.
@gventuri Do you think you could add me as a Contributor?
