### ISSUE TITLE
Test failure after initial setup for development

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#663]
### System Info

OS version: Windows 10 Pro
Python version: 3.10.10
PandasAI version: 1.3.3

### 🐛 Describe the bug

After a clean setup for initial development, notice that 2 of the tests are failing:

```bash
================================================================================ short test summary info ================================================================================= 
FAILED tests/test_smartdataframe.py::TestSmartDataframe::test_save_chart_non_default_dir - AssertionError: assert 'exports/char...b180ab5a5.png' == 'exports/char...b180ab5a5.png'
FAILED tests/callbacks/test_file.py::TestFileCallback::test_on_code - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Henrique\\Desktop\\area de trabalho\\pessoal\\repos\\pandas...
================================================================= 2 failed, 248 passed, 2 skipped, 40 warnings in 12.09s =================================================================
```

I'll give extra guidance on both errors.

## `test_on_code`
This is returning `none` for the `self.assertEqual(contents, response)` statements, although the strings compared are equal.

And why are mixed frameworks for testing? There are some tests using the built-in `unittest` module. Shouldn't it be standardized all to `pytest`?

## `test_save_chart_non_default_dir`

This may have a connection with the OS. The test is failing on the following assertion:
```python
        assert (
            plt_mock.savefig.call_args.args[0]
            == f"exports/charts/{smart_dataframe.last_prompt_id}.png"
        )
```

This is the best practice because the path is fixed for Unix-style systems. The problem is precisely in the fixed path variable.

```python
plt_mock.savefig.call_args.args[0] = 'exports/charts\\cf69927e-2ec6-4ae6-a063-0d3d30598328.png'
f"exports/charts/{smart_dataframe.last_prompt_id}.png" = 'exports/charts/cf69927e-2ec6-4ae6-a063-0d3d30598328.png'
```

@gventuri, would you like to let someone work on this? Or can I handle it? I prefer to let new contributors have a chance to work on it, especially the second one, which is a path and OS related problem.

**Comment by gventuri** [comment]
Thanks a lot for reporting @HenriqueAJNB! Is it the same of this? https://github.com/gventuri/pandas-ai/issues/661

What is weird is that the CI on windows is not failing!

**Comment by HenriqueAJNB** [comment]
@gventuri, the tests are failing indeed, see [in this last build](https://github.com/gventuri/pandas-ai/actions/runs/6565665788/job/17834687788#step:7:56). But, because it's being used coverage and not purely running the tests, CI won't fail. Found at [this answer](https://stackoverflow.com/a/52132809/12787236) in SO.

**Comment by HenriqueAJNB** [comment]
@gventuri, I've opened #664 to expose this failure at CI. But still need to fix those...

**Comment by HenriqueAJNB** [comment]
> Thanks a lot for reporting @HenriqueAJNB! Is it the same of this? #661

Yes, it's the same. But this issue mentioned one more test failing.

**Comment by LUCASDNORONHA** [comment]
Hi, I've spoken to @HenriqueAJNB and I'll try to solve this problem, if I can't, I'll let you know. @gventuri all right?

**Comment by gventuri** [comment]
Sure thing, welcome onboard @LUCASDNORONHA, assigned it to you!

**Comment by HenriqueAJNB** [comment]
@gventuri, @LUCASDNORONHA, I've figured out the problem with the first testing `test_on_code`.

The test raises `PermissionError` on tear down when removing the file created by the `FileCallback` class. That happens because the way it is created is unsafe, and the file is still open when removed on tear down.

The error is gone if the file is closed explicitly before being deleted on tear down.

And about the second one, it's an OS-related problem. I suggest replacing the hard-coded path in a string by using `pathlib`, so it can handle the OS's different paths.

@LUCASDNORONHA, got it? I can help you with that if you need to.

**Comment by LUCASDNORONHA** [comment]
@gventuri @HenriqueAJNB I couldn't solve the problem. It's beyond me. I'll leave it to someone else. Thank you for the opportunity.

**Comment by HenriqueAJNB** [comment]
@gventuri, 

> The test raises PermissionError on tear down when removing the file created by the FileCallback class. That happens because the way it is created is unsafe, and the file is still open when removed on tear down.
> 
> The error is gone if the file is closed explicitly before being deleted on tear down.

This worked fine. The test `test_on_code` is now working.

About the other one, `test_save_chart_non_default_dir`. This is a more complex problem, and it has a root cause.

The core problem is that all paths in the project are treated as strings, leading to the test difference.

And I don't know precisely where the `plt.savefig()` mocked in the test is being called to ensure that the path passed as a parameter is a `pathlib. Path` type and not `str`.

Can anyone help me to find this out? 

As a longer alternative, we can transform all path strings to `pathlib.Path`.
