### ISSUE TITLE
Insert a quality gate on CI

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#667]
@gventuri, I've got some options for that.

We can use either [Sourcery](https://docs.sourcery.ai/Welcome/) or [SonarCloud](https://www.sonarsource.com/products/sonarcloud/)

Both are free for open-source projects. A lot of minor issues have already been caught by the SonarLint VSCode extension.

And after solving those that make sense, we should keep track of new codes to control them on the quality gate.

What do you think about it?

We can break this into tasks:
- Resolve SonarLint and/or mypy issues that make sense to solve
- Implement one of the two quality gates. My vote is for Sourcery on CI; it already has a [GitHub Actions](https://github.com/marketplace/actions/sourcery-action)

**Comment by gventuri** [comment]
@HenriqueAJNB 100% agree, let's solve the issues with SonarLint locally and then use Sorcery for the CI!

**Comment by HenriqueAJNB** [comment]
@gventuri, assign this task to me, please.

Can you create the Sourcery token and a new repository secret called `SOURCERY_TOKEN`? 

We will need it for [Sourcery GitHub Actions]( https://github.com/sourcery-ai/action)

**Comment by gventuri** [comment]
@HenriqueAJNB just assigned it to you and added the token :)

**Comment by HenriqueAJNB** [comment]
@gventuri, I want to share this discussion about the quality gate (and code quality in general) in a more collaborative way with other contributors. 

I always have this concern about scalability and quality, and would be nice if we have discussions on this topic. 

Or do you prefer to get things done first (I can easily take front of this) and adjust it as we get an ongoing perspective?

**Comment by gventuri** [comment]
@HenriqueAJNB great point. In general, if it's not super time consuming, I recommend:
- getting things done
- check the outcomes
- if there are some improvements, implement them

That said, at the same time we could already start a more long-term discussion about the code quality with other contributors (we can create a new thread either here on github or on Discord, whatever we prefer)!

Let me know your POV, super open :)
