### ISSUE TITLE
Link at main doc page is pointing to non-existent page

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#670]
The "Edit on GitHub" button on the top of [main doc](https://docs.pandas-ai.com/en/latest/) is pointing to a non-existent page

![2023-10-21_20h09_13](https://github.com/gventuri/pandas-ai/assets/54143210/88e8cc80-0f81-425f-9f3d-62fda00b016e)

Easy fix, just find the link and replace it by pointing to the main branch.

**Comment by HenriqueAJNB** [comment]
@gventuri, please let me solve this issue. I know this is simple, but I intend to make a live on YouTube for Portuguese speakers on how to start contributing. This issue will be the best starting point.

**Comment by camilaccb** [comment]
@HenriqueAJNB estava tentando atuar nesse ponto, mas ainda não encontrei no código

**Comment by camilaccb** [comment]
@gventuri I was checking the docs page  to see if it works after merge, but seems we continue with the problem. 
@HenriqueAJNB Do you have any clue about it? I did what I found in the documentation..

I also saw the compilation got an error, but Im not sure with it has any correlation

![image](https://github.com/gventuri/pandas-ai/assets/98741510/f9f19686-86d8-4998-b0df-d50d642be804)
