### ISSUE TITLE
Use Google Bard's PaLM model as an LLM option

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#674]
### 🚀 The feature

It would be nice to have another LLM model from Google Bard. I don't know if Google Bard has a free API like ChatGPT. We should investigate it.

### Motivation, pitch

This would be a nice comparison between the Open AI models. We could have even tests for the accuracy result from them, using the most accurate response.

**Comment by gventuri** [comment]
@HenriqueAJNB at the moment we are supporting Google models with palm and VertexAI. As far as I know, there's not a "Bard" API! I checked and couldn't find anything!
