### ISSUE TITLE
Add  project dependencies license

### ISSUE THREAD

**Issue by camilaccb** [gventuri/pandas-ai#676]
Create a folder in main tree that storage all dependencies licenses used in the project in order to  maintain transparency and compliance with licensing requirements.

[Example](https://github.com/pandas-dev/pandas/tree/main/LICENSES)

**Comment by camilaccb** [comment]
Yes, sure! You can assign for me!

**Comment by gventuri** [comment]
Done :)

**Comment by camilaccb** [comment]
@ gventuri, I was thinking about how I can address this issue, and I'd like to share my thoughts with you to see if it makes sense. Also, @ HenriqueAJNB, please feel free to contribute your feedback.

The way I'm thinking is to create a script that looks for the pyproject.toml file and checks for any updates in the dependencies. If there are any updates in the dependencies, we should make a request in the GitHub API and attempt to retrieve the notice text for that open-source project.

Since this is something that can dynamically change, I would suggest including it in the pre-commit file so that we can keep these notice licenses up to date during development. I haven't worked with this file before, so I don't know exactly what impact this inclusion may have.

I don't believe this will significantly impact the usage of Pandas AI, but it will be a valuable reference for the community, as this is not a practice followed by all projects. It will also be a great learning experience for me as a contributor.

**Comment by HenriqueAJNB** [comment]
@camilaccb, my suggestion is to add it first manually since we don't have any mention of licences from other third party packages. 

And for automating this process that's another issue that we can open. I love automations and agree completely that this should be done, but in a different issue.

@gventuri, what are your thoughts about it?

**Comment by gventuri** [comment]
Totally agree! Let's make it manual and add a new issue for the automation. Maybe we can implement something either as a pre-commit or in the CI. What do you think?

**Comment by camilaccb** [comment]
Agree with your feedbacks, I'm going to start it manually!

**Comment by camilaccb** [comment]
License folder added
