### ISSUE TITLE
pip install wrong

### ISSUE THREAD

**Issue by pidada** [gventuri/pandas-ai#70]
Hello authors:
        when i installed pandasai, something was wrong in MacOS.i use the code according to the README.md
```python
pip install pandas
```

the wrong is:
```python
ERROR: Could not find a version that satisfies the requirement pandasai (from versions: none)
ERROR: No matching distribution found for pandasai
```

can you help me?

**Comment by gventuri** [comment]
Hey @pidada,
you should install `pandasai`, here's how you can do with pip:

```pip install pandasai```

If the problem persists, try the following:

```
pip install --upgrade pandasai
```

If the problem persists, try the following:

```
pip install pandasai==0.2.5
```

If this doesn't solve it either, could you paste the whole output you get with the attempts?

**Comment by pidada** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已经收到！会马上回复！

**Comment by vishaln15** [comment]
I faced this issue on Python 3.6, however by using **pip3.9** I was able to install pandasai on Raspbian Bullseye (Debian GNU/Linux 11 (bullseye) aarch64) Raspberry Pi 4.

**Comment by sandiemann** [comment]
I also had trouble installing the lib with pip on mac,
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipykernel 6.4.1 requires ipython<8.0,>=7.23.1, but you have ipython 8.13.2 which is incompatible.`

Although, It installed successfully with version `pandasai==0.2.5`

**Comment by RichardPinter** [comment]
I'm getting the following error on Python 3.8.10:
`ERROR: Could not find a version that satisfies the requirement pandasai (from versions: none)
ERROR: No matching distribution found for pandasai`

**Comment by PinkPanther221** [comment]
When I try to install pandasai in jupyter notebook, I'm getting the same problem. Anaconda told me I successfully installed pandasai, but I got an error No module named 'pandasai'

**Comment by Poojan66** [comment]
Same problem is faced for python version 3.8.10.

**Comment by sandiemann** [comment]
@RichardPinter @Poojan66 As mentioned in the pypi,  it Requires: Python >=3.9, <4.0

https://pypi.org/project/pandasai/

**Comment by sandiemann** [comment]
@gventuri on installing `!pip install pandasai` on colab  I get dependencies conflict for incompatible version of ipython & pandas.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipython~=7.34.0, but you have ipython 8.13.2 which is incompatible.
google-colab 1.0.0 requires pandas~=1.5.3, but you have pandas 2.0.1 which is incompatible.
WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Disconnect and delete runtime" from the "Runtime" menu.
WARNING: The following packages were previously imported in this runtime:
  [IPython]`
  
  Could you please fix these versions on setup requirements.txt

**Comment by hunaone** [comment]
Hello, I want to ask, I can't use pip to install, so I downloaded the installation package locally, what should I do next to use it?

**Comment by gventuri** [comment]
Try with `!pip install --upgrade pandas pandasai`, should work! Also updated the default colab.

@hunaone, check out the README for some examples or have a look at the `/examples` folder!

**Comment by ZhijingEu** [comment]
I have the same problem :( I am running on Python 3.13.2 via Anaconda and trying to install this via pip in the conda terminal and it choked as it says it can't find the Rust (?) Toolchain.

(Environment) C:\Users\Myself>pip install pandasai
Collecting pandasai
  Using cached pandasai-2.3.0-py3-none-any.whl.metadata (10 kB)
Collecting astor<0.9.0,>=0.8.1 (from pandasai)
  Using cached astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: duckdb<2.0.0,>=1.0.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (1.2.2)
Collecting faker<20.0.0,>=19.12.0 (from pandasai)
  Using cached Faker-19.13.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: jinja2<4.0.0,>=3.1.3 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (3.1.6)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (3.10.0)
Requirement already satisfied: openai<2 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (1.72.0)
Collecting pandas==1.5.3 (from pandasai)
  Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow<11.0.0,>=10.1.0 (from pandasai)
  Using cached pillow-10.4.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: pydantic<3,>=1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (2.11.3)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (1.1.0)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.9.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (1.15.2)
Requirement already satisfied: sqlalchemy<3,>=1.4 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandasai) (2.0.40)
Collecting sqlglot<26.0.0,>=25.0.3 (from sqlglot[rs]<26.0.0,>=25.0.3->pandasai)
  Using cached sqlglot-25.34.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.21.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandas==1.5.3->pandasai) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandas==1.5.3->pandasai) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pandas==1.5.3->pandasai) (2024.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from jinja2<4.0.0,>=3.1.3->pandasai) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (3.2.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (4.6.2)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (0.9.0)
Requirement already satisfied: sniffio in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from openai<2->pandasai) (4.12.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pydantic<3,>=1->pandasai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pydantic<3,>=1->pandasai) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from pydantic<3,>=1->pandasai) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from requests<3.0.0,>=2.31.0->pandasai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from requests<3.0.0,>=2.31.0->pandasai) (2025.4.26)
Requirement already satisfied: greenlet>=1 in c:\users\zhiji\anaconda3\envs\agentslearning\lib\site-packages (from sqlalchemy<3,>=1.4->pandasai) (3.1.1)
Collecting sqlglotrs==0.3.0 (from sqlglot[rs]<26.0.0,>=25.0.3->pandasai)
  Using cached sqlglotrs-0.3.0.tar.gz (9.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Python reports SOABI: cp313-win_amd64
      Computed rustc target triple: x86_64-pc-windows-msvc
      Installation directory: C:\Users\zhiji\AppData\Local\puccinialin\puccinialin\Cache
      Rustup already downloaded
      Installing rust to C:\Users\zhiji\AppData\Local\puccinialin\puccinialin\Cache\rustup
      warn: It looks like you have an existing rustup settings file at:
      warn: C:\Users\zhiji\.rustup\settings.toml
      warn: Rustup will install the default toolchain as specified in the settings file,
      warn: instead of the one inferred from the default host triple.
      warn: installing msvc toolchain without its prerequisites
      info: profile set to 'minimal'
      info: default host triple is x86_64-pc-windows-msvc
      warn: Updating existing toolchain, profile choice will be ignored
      info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
      info: default toolchain set to 'stable-x86_64-pc-windows-msvc'
      Checking if cargo is installed

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      Rust not found, installing into a temporary directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by pidada** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已经收到！会马上回复！
