### ISSUE TITLE
[Feature] File-system permissions for auxiliary files

### ISSUE THREAD

**Issue by nautics889** [gventuri/pandas-ai#700]
### 🚀 The feature

Inspired by https://github.com/gventuri/pandas-ai/issues/654.

___

### Description

When i was working with initial creating of paths for some auxiliary files i noticed that mostly (or even all) files and directories are being created with the widest possible access (permission equaling to `-rwxrwxrwx`, `777`).

To be accurate this is about the directory containing charts output and the directory containing cache files.

Here are links to the related lines of source code (rev. b91c121c5200e345d6e0d524aa85fc71afc92f94):
1. [`cache.py`, L25](https://github.com/gventuri/pandas-ai/blob/b91c121c5200e345d6e0d524aa85fc71afc92f94/pandasai/helpers/cache.py#L25)
2. [`sql.py`, L186](https://github.com/gventuri/pandas-ai/blob/b91c121c5200e345d6e0d524aa85fc71afc92f94/pandasai/connectors/sql.py#L186)
3. [`smart_datalake/__init__.py`, L155](https://github.com/gventuri/pandas-ai/blob/b91c121c5200e345d6e0d524aa85fc71afc92f94/pandasai/smart_datalake/__init__.py#L155)
4. [`smart_datalake/__init__.py`, L162](https://github.com/gventuri/pandas-ai/blob/b91c121c5200e345d6e0d524aa85fc71afc92f94/pandasai/smart_datalake/__init__.py#L162C30-L162C30)
5. [`yahoo_finance.py`, L87](https://github.com/gventuri/pandas-ai/blob/b91c121c5200e345d6e0d524aa85fc71afc92f94/pandasai/connectors/yahoo_finance.py#L87)

I doubt there is need to be rwx access for user's group members and other user's. As seems to me, the permissions to be set should be 755 or something like this (however i'm not sure that the "exec" permission is needed as well — pandasai only should read and write those files). But this is a point to be discussed anyway.

___

### Suggestion

1. Introduce a variable for file-permission.
2. Set the default file permission `0o755` (_on choice, to be discussed_)
3. (_Optional_) Implement possibility to pass the value for permission via config object.

___

I would be glad if someone else can handle this change request (if the changes sound reasonable of course) and upload a corresponding PR.

### Motivation, pitch

Enhances flexibility, remove hardcode for file permissions.

**Comment by gventuri** [comment]
@nautics889 thanks a lot for reporting. I guess we can use 755 by default. Imho we shouldn't even let the user specify. If they want, they can create these folders with additional permissions in advance. 755 is enough for PandasAI, so I'd say we can stick to that imho!

**Comment by gventuri** [comment]
@nautics889 just checking. Do you want to work on this or you prefer someone else to pick it? :)

**Comment by nautics889** [comment]
@gventuri thanks for the remind :) Sure, please, assign this one to me if it's possible, and i'll upload the update (probably tomorrow)
