### ISSUE TITLE
Setting the seed when instantiating the model

### ISSUE THREAD

**Issue by gamcoh** [gventuri/pandas-ai#708]
### 🚀 The feature

It would be nice to have something like that:
```py
df = SmartDataframe(
    df,
    config={
        "llm": llm,
        "verbose": True,
    },
    seed=26
)
```

### Motivation, pitch

The seed being set in the model of the servers of OpenAI or AzureOpenAI, would allow some deterministic features.
For now my users don't understand why the module gives different answers with the same question (exact same token) when re-logging on the app.

**Comment by gventuri** [comment]
That's a very good point, I love the idea to have to possibility of making the LLM more deterministic. Do you want to work on this @gamcoh or do you prefer someone else to pick it?

**Comment by gamcoh** [comment]
Looks like as of today (2023-11-10) Azure OpenAI does not support the seed in their arguments, on the other hand, OpenAI just released it : https://platform.openai.com/docs/guides/text-generation/reproducible-outputs

> Reproducible outputs (Beta)
> 
> Chat Completions are non-deterministic by default (which means model outputs may differ from request to request). That being said, we offer some control towards deterministic outputs by giving you access to the [seed](https://platform.openai.com/docs/api-reference/completions/create#completions/create-seed) parameter and the [system_fingerprint](https://platform.openai.com/docs/api-reference/completions/object#completions/object-system_fingerprint) response field.
> 
> To receive (mostly) deterministic outputs across API calls, you can:
> 
> Set the [seed](https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed) parameter to any integer of your choice and use the same value across requests you'd like deterministic outputs for.
> 
> Ensure all other parameters (like prompt or temperature) are the exact same across requests.
> 
> Sometimes, determinism may be impacted due to necessary changes OpenAI makes to model configurations on our end. To help you keep track of these changes, we expose the [system_fingerprint](https://platform.openai.com/docs/api-reference/chat/object#chat/object-system_fingerprint) field. If this value is different, you may see different outputs due to changes we've made on our systems.

I think this integration could be better:
```py
llm = AzureOpenAI(
  seed=26,
  temperature=0,
  deployment_name="sandbox-gpt-35-turbo",
  is_chat_model=True,
)
```
Instead of adding the param in the `SmartDataframe` instance.

@gventuri I can try to find time, in the meantime if anybody wants it, knock yourself out

**Comment by gamcoh** [comment]
I think I managed to do it, of course it's not something easy to test, especially for me because I don't have a OpenAI account but a AzureOpenAI one.
@gventuri let me know what you think
