### ISSUE TITLE
Inconsistentb datatype formation

### ISSUE THREAD

**Issue by MuthusivamGS** [gventuri/pandas-ai#721]
### System Info

Please share your system info with us.
OS version:Windows
Python version:3.11
The current version of pandasai being used:1.4

### 🐛 Describe the bug

using DataLake function the output type is in consistent, even after mentioning the output type the output comes as different one 
example 
dl.chat('show count of Codes on basis of year',output_type='DataFrame')

response - 'There were 1809 codes in 2020 and 1336 codes in 2021.'

**Comment by gventuri** [comment]
@MuthusivamGS `output_type` should rather be `dataframe`! This should fix the issue!
