### ISSUE TITLE
accepting description along with dataframe as input

### ISSUE THREAD

**Issue by vikas94** [gventuri/pandas-ai#729]
### 🚀 The feature

PandasAI SmartDataframe and Smart Datalake have to accepts 1-2 lines description of the data aswell at input and it has to be given as context for the AI model along with the df.head()

so that the model performs even better

### Motivation, pitch

It just improves the process.

**Comment by vlasvlasvlas** [comment]
this looks good and could help improve coherence, can we also think like a data dictionary based on atributes-columns of the pandas data frame?

**Comment by vikas94** [comment]
> this looks good and could help improve coherence, can we also think like a data dictionary based on atributes-columns of the pandas data frame?

yeah might be helpful when using tier-2 models/masked columns.

**Comment by gventuri** [comment]
@vikas94 @vlasvlasvlas it's already possible to pass a name and a description for a given dataframe. Basically, when you instantiate a new 'SmartDataframe', you can just pass a description param for that.

**Comment by vlasvlasvlas** [comment]
> @vikas94 @vlasvlasvlas it's already possible to pass a name and a description for a given dataframe. Basically, when you instantiate a new 'SmartDataframe', you can just pass a description param for that.

maybe could be helpful to add an example on the docs? i think that could help a lot :)

**Comment by vikas94** [comment]
> @vikas94 @vlasvlasvlas it's already possible to pass a name and a description for a given dataframe. Basically, when you instantiate a new 'SmartDataframe', you can just pass a description param for that.

how to handle the same in smart data lake when you are adding multiple data frames, how do you add description to each df separately?

**Comment by gventuri** [comment]
@vikas94 in that case, you can just instantiate several `SmartDataframe` with description and pass them to the `SmartDatalake`. Let me know :)

Closing for now, feel free to reopen if you have any questions!

**Comment by vlasvlasvlas** [comment]
if you can add an example with smartdataframe that includes description would be great. thanks!

**Comment by SweetyKhut** [comment]
@gventuri I tried your method still the name and description is getting passed as null
