### ISSUE TITLE
Support OpenAI API v1

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#737]
### 🚀 The feature

Add support for the newest version of the API.

### Motivation, pitch

The old `openai.ChatCompletion` has been replaced by `openai.OpenAI.chat.completions` (a factual class) and `openai.AzureOpenAI.chat.completions` for Azure.

**PR coming soon!**

**Comment by gventuri** [comment]
@mspronesti definitely a must, thanks for reporting. Do you want to work on it?

**Comment by mspronesti** [comment]
Yep, feel free to assign it to me :)

**Comment by mspronesti** [comment]
@gventuri Btw, given that the new API is more class-like and that we need to guarantee backward compatibility, I believe that a unified solution (chat + completion in the same class) would make the codebase a little "heavy" to maintain. Are you against splitting it in 2 classes (+2 for Azure), i.e. `ChatOpenAI`, `OpenAI`, `AzureOpenAIChat`, `AzureOpenAI`?

**More context:**
while before we could do an if-then-else in `call` to decide whether to call the completion or the chat completion API (as they were functions, or used as such), now we need to 
- distinguish if the model is a chat or a completion model
- distinguish which version of the API we are using
  * set a client attribute accordingly (either `openai.Openai(**params).completions`/`openai.Openai(**params).chat.completions` or `openai.Completions`/`openai.ChatCompletions`)
- in  `call`  check again whether we want to call the completions or the chat completion API.

**Comment by homanp** [comment]
@mspronesti any updates on when support for OpenAI v1 will be in? Getting dependency issues when trying to install the package with newer versions of the OpenAI lib. 

```
Because no versions of pandasai match >1.4.8,<1.5.0a1 || >1.5.0a1,<2.0.0
 and pandasai (1.5.0a1) depends on openai (>=0.27.5,<0.28.0), pandasai (>1.4.8,<2.0.0) requires openai (>=0.27.5,<0.28.0).
And because pandasai (1.4.8) depends on openai (>=0.27.5,<0.28.0), pandasai (>=1.4.8,<2.0.0) requires openai (>=0.27.5,<0.28.0).
So, because superagent depends on both openai (^1.1.1) and pandasai (^1.4.8), version solving failed.
```

**Comment by mspronesti** [comment]
@homanp I will open a PR by the end of the day :)
