### ISSUE TITLE
Translate CONTRIBUTING.md to pt-br

### ISSUE THREAD

**Issue by camilaccb** [gventuri/pandas-ai#746]
I want to follow the same idea and arguments of[ issue 744](https://github.com/gventuri/pandas-ai/issues/744).

**Comment by camilaccb** [comment]
@gventuri Im handling this issue! Can you please assign to me?

**Comment by HenriqueAJNB** [comment]
@camilaccb, let's open a major issue and list all docs inside it as tasks. It's best for controlling the whole translation.

**Comment by HenriqueAJNB** [comment]
@gventuri, @camilaccb can handle the `CONTRIBUTING.md`, but my suggestion is to close this issue and concentrate all pt-br translations in https://github.com/gventuri/pandas-ai/issues/747

**Comment by camilaccb** [comment]
Sure! This way its going to be more organized and easy for other people contribution :D

**Comment by camilaccb** [comment]
Sure! This way its going to be more organized and easy for other people contribution :D
