### ISSUE TITLE
Unrecognized request argument supplied: seed

### ISSUE THREAD

**Issue by Timmate** [gventuri/pandas-ai#749]
### System Info

pandasai v1.4.8, openai v0.27.10, Python 3.10

### 🐛 Describe the bug

When trying to `chat()` with a created `SmartDataFrame`, I'm getting the following error:

```
'Unfortunately, I was not able to answer your question, because of the following error:\n\nUnrecognized request argument supplied: seed\n'
```

Apparently, this has to do with v1.4.8 of pandasai and the introduction of the `seed` param in #742. Obviously, a solution could be simply to downgrade to 1.4.7, but was wondering if there is another way. I'm getting this error for any of the below mentioned Azure OpenAI API versions. @gamcoh, do you have any ideas? Thanks in advance!

Here's the full code:
```
from pandasai import SmartDataframe
from pandasai.llm import AzureOpenAI

llm = AzureOpenAI(
    deployment_name="gpt35turbotest",
    model_name="gpt-35-turbo",
    api_token=<token>,
    api_base=<azure endpoint>, 
    # api_version="2023-03-15-preview"
    #api_version="2023-07-01-preview"
    api_version="2023-08-01-preview"
)

sdf = SmartDataframe(df, config={"llm": llm})
df.chat(<question>)
```

**Comment by gamcoh** [comment]
You're right this is a bug, the openai module should have the latest version in order to use the seed param

**Comment by Timmate** [comment]
@gamcoh, got it, thanks for your reply! I guess I'm missing something, but how is it expected to work now if the [openai version ](https://github.com/gventuri/pandas-ai/blob/0712f8418a1fbc86c02cb4614e34573b965b366e/poetry.lock#L2928C20-L2928C20) specified in poetry.lock is 0.27.10? Tried upgrading openai to the latest version, but this broke pandasai

**Comment by mspronesti** [comment]
#753 introduces support for the newest API (for OpenAI only, no Azure OpenAI yet). Feel free to have a look at it :)

**Comment by mspronesti** [comment]
The newest version supports OpenAI v1 and, among the others, `seed`. Feel free to have a look :)

**Comment by gamcoh** [comment]
Great work @mspronesti thanks!

**Comment by Timmate** [comment]
v1.4.10 (with v1.3.3 of `openai`) works just fine for me with the above setup (except `api_base` now is called `azure_endpoint`) for any of the above Azure OpenAI API versions. Haven't tried setting the seed yet, though.

**Closing this as solved anyways.**

Many thanks to @mspronesti!
