### ISSUE TITLE
Adding Issue and Pull Request template

### ISSUE THREAD

**Issue by ambujpawar** [gventuri/pandas-ai#75]
Hi @gventuri , 

I just wanted to congratulate on the excellent work done on pandas-ai. It looks great and seeing it gain so many stars in such a short time is nothing short of just incredible.

However, with increasing popularity of this will result in increasing issues and increasing pull requests. Therefore, it would be a good idea to have some sort of issue template and pull request template which will enable the users to post issues in a manner which will help the maintainers to either debug it or add a new feature better.

Similarly, it would be nicer to add a Pull request template to keep a track of which issues were solved by which PR.

**Comment by gventuri** [comment]
@ambujpawar thanks a lot!

Great catch, this is indeed something I had postponed so far, it's great that you contributed to it, thanks a lot for your support!
