### ISSUE TITLE
Is adding Contributing guidelines still a todo.

### ISSUE THREAD

**Issue by ambujpawar** [gventuri/pandas-ai#77]
Hi,

I see that adding Contributing Guidelines still marked as a TODO.

However, I see that there is a already a Contributing.md present over [here](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md)

Is there something that you want to add to Contributing.md or shall we mark it as completed in the TODO?

**Comment by gventuri** [comment]
Hey @ambujpawar, it's actually something I had started doing very quickly. I'd say it makes sense to either double check if the Contributing.md is missing something important or marking the Todo as completed!
