### ISSUE TITLE
A deprecation warning when openai version < 1.0

### ISSUE THREAD

**Issue by nautics889** [gventuri/pandas-ai#788]
### Context

Python version: 3.11.4
The current version of `pandasai` being used: 1.5.4

___

### Short description

There is a recently merged update [containing upgrade to OpenAI v1](https://github.com/gventuri/pandas-ai/pull/753/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R15).
Therefore, there is some problems running a newest version of pandasai in the same old environment (without upgrading `openai v0.27`>`openai ^1.0`).

___

### Details

Consider this issue more like a topic to discuss: should we add in [`is_open_ai_v1()`](https://github.com/gventuri/pandas-ai/blob/8093e8da58ea6090013eb5a8a73c49c550f8b189/pandasai/helpers/openai.py#L8) utility function a deprecation warning? Or even exception? 
I guess it'd be a plus. Since otherwise it falls with quite obscured traceback, some part of the logs i put below:
```
Generate python code and return full updated code:
2023-11-28 22:54:02 [INFO] Executing Step 2: CodeGenerator
2023-11-28 22:54:02 [ERROR] Pipeline failed on step 2: 'OpenAI' object has no attribute 'api_base'
```
Expl.: in the above case, if we use `openai` < 1.0, `is_openai_v1()` [obviously returns `False`](https://github.com/gventuri/pandas-ai/blob/8093e8da58ea6090013eb5a8a73c49c550f8b189/pandasai/llm/base.py#L257C16-L257C30), and then it [tries to access `self.api_base`](https://github.com/gventuri/pandas-ai/blob/8093e8da58ea6090013eb5a8a73c49c550f8b189/pandasai/llm/base.py#L261) which has never been exists in this turn so far. 

___

### Steps to reproduce

1. Downgrade openai package. (`$ pip uninstall openai && pip install openai==0.*`)
2. Take the very basic example. Like this, for instance:
```python
import pandas as pd
from data.sample_dataframe import dataframe

from pandasai import SmartDataframe
from pandasai.llm import OpenAI

df = pd.DataFrame(dataframe)

llm = OpenAI()
df = SmartDataframe(df=pd.DataFrame(dataframe), config={"llm": llm})
response = df.chat("Calculate the sum of the gdp of north american countries")
print(response)
```

3. Run code.

**Comment by mspronesti** [comment]
Hi @nautics889,
In terms of implementation, pandasai is backward compatible with openai < 1.0.0.
In practice, I made a mistake upgrading the version in the project dependencies. Changing openai's minimum version in pyproject.toml should make pandasai fully compatible with previous version.
I will have a look asap and open a PR :)

**Comment by mspronesti** [comment]
Yep, it seems to be as I said. 

**Steps to reproduce:**
- change `openai` version in pyproject.toml to 0.27.5 (or anything before 1.0.0)
- `pip install openai==0.*`
- `pip install .`  (install pandasai)
- run example above
- `pip install openai>=1.*`
- run example above again

It should work in both cases appropriately.

**Comment by nautics889** [comment]
Hello, @mspronesti,
Thank you for the quick response.

>It should work in both cases appropriately.

Hmm, it's looking strange to me then, because, as I mentioned above, there is no initialization for `api_base` attribute apparentely, in short words, and the code has been failed after entering [this if block](https://github.com/gventuri/pandas-ai/blob/8093e8da58ea6090013eb5a8a73c49c550f8b189/pandasai/llm/base.py#L257) (and then tries to access [`self.api_base`](https://github.com/gventuri/pandas-ai/blob/8093e8da58ea6090013eb5a8a73c49c550f8b189/pandasai/llm/base.py#L261))... 
But I'm still not sure, i guess, it's possible i had missed something. Give me a little more time, please, i'll re-check this.

**Comment by mspronesti** [comment]
> Hmm, it's looking strange to me then, because, as I mentioned above, there is no initialization for api_base attribute apparently,

Not sure I understand what you mean here. With openai >= 1.0.0 you need to pass `azure_endpoint`, with openai < 1, you need to pass `api_base`. In other words, `api_base` is mandatory for `openai` < 1 and ignored for openai >= 1 (where `azure_endpoint` is expected)

**Comment by mspronesti** [comment]
Hi @nautics889,
my bad, I misread your previous message this morning. I think there are essentially 2 problems:
- openai's **minimum** version needs to be downgraded (i.e. latest is preferred, previous versions are supposed to work)
- `api_base` is not set, thus not "accessible" if not passed.

I've just opened a draft PR. Feel free to have a look. As I don't have an OpenAI key at the moment (only an Azure OpenAI) I couldn't test it. It should work though. Feel free to append commits there if it doesn't work for you.

**Comment by nautics889** [comment]
PR #793, LGTM
`api_base` now has a default value

Thank you!
