### ISSUE TITLE
'OpenAI' object has no attribute 'api_base'

### ISSUE THREAD

**Issue by tytung2020** [gventuri/pandas-ai#792]
### System Info

OS windows 11
openai   0.27.10
pandas  1.5.3
pandasai   1.5.4

### 🐛 Describe the bug

`
      
    def pandasai_query(data, question):
        df = pandas.DataFrame(data)  
        llm = OpenAI(api_token=openai.api_key, model= "gpt-4")
        chat_df = SmartDataframe(df, config={"llm": llm})
        answer = chat_df.chat(question)
        return answer
`
response_pdai = pandasai_query(some_data, message)
`

Output:
...
Generate python code and return full updated code:
2023-11-29 21:06:17,509 - pandasai.helpers.logger - INFO - Executing Step 2: CodeGenerator
2023-11-29 21:06:17,513 - pandasai.helpers.logger - ERROR - Pipeline failed on step 2: 'OpenAI' object has no attribute 'api_base'
Unfortunately, I was not able to answer your question, because of the following error:
'OpenAI' object has no attribute 'api_base'

**Comment by nautics889** [comment]
@tytung2020 
Fixed in https://github.com/gventuri/pandas-ai/pull/793 as @mspronesti has mentioned above.
Alternatively you can upgrade `openai` package to the latest version (>=1.0), this will resolve the problem immediately.
