### ISSUE TITLE
"verbose": True not showing the code

### ISSUE THREAD

**Issue by daniel-counto** [gventuri/pandas-ai#803]
### System Info

pandasai 1.5.5

### 🐛 Describe the bug

!pip install pandasai python-dotenv

import os
import openai
from pandasai.llm import OpenAI
from dotenv import load_dotenv
import pandas as pd
from pandasai import SmartDataframe
from pandasai import SmartDatalake

openai.api_key = os.getenv("OPENAI_API_KEY")
llm = OpenAI(api_token=openai.api_key, model="gpt-4")

df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

df = SmartDataframe(df, config={"llm": llm, "conversational": True, "verbose": True})
df.chat('Which are the 5 happiest countries?')

![Screenshot (670)](https://github.com/gventuri/pandas-ai/assets/140989990/5ca73c2c-0063-4dc0-b9ce-51c00de0e290)

**Comment by daniel-counto** [comment]
@nautics889  yeah the code is there in the log:

`[{'level': 'INFO',
  'msg': 'Question: Which are the 5 happiest countries?',
  'source': 'SmartDatalake',
  'time': 3.991454601287842},
 {'level': 'INFO',
  'msg': 'Running PandasAI with openai LLM...',
  'source': 'SmartDatalake',
  'time': 0.16738367080688477},
 {'level': 'INFO',
  'msg': 'Prompt ID: 02f0a547-6fab-4129-b9bb-052304678383',
  'source': 'SmartDatalake',
  'time': 0.01096963882446289},
 {'level': 'DEBUG',
  'msg': '<class '
         "'pandasai.helpers.output_types._output_types.DefaultOutputType'> is "
         'going to be used.',
  'source': 'SmartDatalake',
  'time': 0.026636123657226562},
 {'level': 'DEBUG',
  'msg': '<class '
         "'pandasai.helpers.viz_library_types._viz_library_types.NoVizLibraryType'> "
         'is going to be used.',
  'source': 'SmartDatalake',
  'time': 0.011882781982421875},
 {'level': 'INFO',
  'msg': 'Executing Step 0: CacheLookup',
  'source': 'Pipeline',
  'time': 0.010053873062133789},
 {'level': 'INFO',
  'msg': 'Executing Step 1: PromptGeneration',
  'source': 'Pipeline',
  'time': 0.010262250900268555},
 {'level': 'INFO',
  'msg': 'Using prompt: <dataframe>\n'
         'dfs[0]:10x3\n'
         'country,gdp,happiness_index\n'
         'France,0151356210,6.66\n'
         'United Kingdom,6685853248,7.16\n'
         'United States,4215280690,6.94\n'
         '</dataframe>\n'
         '\n'
         '\n'
         '\n'
         '\n'
         'Update this initial code:\n'
         '```python\n'
         '# TODO: import the required dependencies\n'
         'import pandas as pd\n'
         '\n'
         '# Write code here\n'
         '\n'
         '# Declare result var: type (possible values "string", "number", '
         '"dataframe", "plot"). Examples: { "type": "string", "value": f"The '
         'highest salary is {highest_salary}." } or { "type": "number", '
         '"value": 125 } or { "type": "dataframe", "value": '
         'pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" '
         '}\n'
         '```\n'
         '\n'
         'Q: Which are the 5 happiest countries?\n'
         'Variable `dfs: list[pd.DataFrame]` is already declared.\n'
         '\n'
         'At the end, declare "result" var dict: type (possible values '
         '"string", "number", "dataframe", "plot"). Examples: { "type": '
         '"string", "value": f"The highest salary is {highest_salary}." } or { '
         '"type": "number", "value": 125 } or { "type": "dataframe", "value": '
         'pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" '
         '}\n'
         '\n'
         '\n'
         '\n'
         'Generate python code and return full updated code:',
  'source': 'SmartDatalake',
  'time': 0.013988971710205078},
 {'level': 'INFO',
  'msg': 'Executing Step 2: CodeGenerator',
  'source': 'Pipeline',
  'time': 0.010827064514160156},
 {'level': 'INFO',
  'msg': 'Code generated:\n'
         '            ```\n'
         '            # TODO: import the required dependencies\n'
         'import pandas as pd\n'
         '\n'
         '# Write code here\n'
         'df = dfs[0]\n'
         "df['gdp'] = df['gdp'].astype(int)\n"
         "df_sorted = df.sort_values(by='happiness_index', ascending=False)\n"
         'top_5_happiest_countries = df_sorted.head(5)\n'
         '\n'
         '# Declare result var: type (possible values "string", "number", '
         '"dataframe", "plot"). Examples: { "type": "string", "value": f"The '
         'highest salary is {highest_salary}." } or { "type": "number", '
         '"value": 125 } or { "type": "dataframe", "value": '
         'pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" '
         '}\n'
         'result = { "type": "dataframe", "value": top_5_happiest_countries }\n'
         '            ```\n'
         '            ',
  'source': 'CodeGenerator',
  'time': 17.966498851776123},
 {'level': 'INFO',
  'msg': 'Executing Step 3: CachePopulation',
  'source': 'Pipeline',
  'time': 0.01133418083190918},
 {'level': 'INFO',
  'msg': 'Executing Step 4: CodeExecution',
  'source': 'Pipeline',
  'time': 0.014489889144897461},
 {'level': 'INFO',
  'msg': 'Saving charts to /content/exports/charts/temp_chart.png',
  'source': 'CodeManager',
  'time': 0.009834527969360352},
 {'level': 'INFO',
  'msg': '\n'
         'Code running:\n'
         '```\n'
         'df = dfs[0]\n'
         "df['gdp'] = df['gdp'].astype(int)\n"
         "df_sorted = df.sort_values(by='happiness_index', ascending=False)\n"
         'top_5_happiest_countries = df_sorted.head(5)\n'
         "result = {'type': 'dataframe', 'value': top_5_happiest_countries}\n"
         '        ```',
  'source': 'CodeManager',
  'time': 0.010749340057373047},
 {'level': 'INFO',
  'msg': 'Executing Step 5: ResultValidation',
  'source': 'Pipeline',
  'time': 0.010074615478515625},
 {'level': 'INFO',
  'msg': "Answer: {'type': 'dataframe', 'value':           country             "
         'gdp  happiness_index\n'
         '6          Canada   1607402389504             7.23\n'
         '7       Australia   1490967855104             7.22\n'
         '1  United Kingdom   2891615567872             7.16\n'
         '3         Germany   3435817336832             7.07\n'
         '0   United States  19294482071552             6.94}',
  'source': 'ResultValidation',
  'time': 0.013244390487670898},
 {'level': 'INFO',
  'msg': 'Executed in: 18.309757947921753s',
  'source': 'ResultValidation',
  'time': 0.01150369644165039},
 {'level': 'INFO',
  'msg': 'Executing Step 6: ResultParsing',
  'source': 'Pipeline',
  'time': 0.015304803848266602}]`

I used the following code to extract only the code executed:

`log_data = df.logs
for entry in log_data:
    if 'Code running:' in entry['msg']:
        lines = entry['msg'].split('\n')
        filtered_lines = [line for line in lines if "code" not in line.lower()]
        code = '\n'.join(filtered_lines).strip()
        print(code)`

**Comment by monkeydust** [comment]
Also was struggling to find how to get the code out as a newbie user. 

Its an amazing library but please can you 

a) Document this (suggest it should be part of the getting started guide) and also make it easier 

b) Provide a way to return the actual code (as suggested above) without scanning logs

Will help with real-world adoption as trust will be an issue

**Comment by gventuri** [comment]
@monkeydust thanks a lot for the feedbacks!

a) fair enough, I guess we have quite a few improvements to be done with the documentation. If you want submit a PR for that, it would be great!

b) you can get the code as it follows:
```
result = df.chat("your query")

# get the code
code = result.last_code_generated
```

Hope it helps!
