### ISSUE TITLE
Error 404: Resource Not Found

### ISSUE THREAD

**Issue by adeepmalmotra** [gventuri/pandas-ai#807]
### System Info

platform: windows
python version: 3.11.5
pandasai version: 1.5.5

### 🐛 Describe the bug

I am getting resource not found error, although I am using same key and url for openai api and its working fine. Can you please suggest me the possible reasons for the error? Below is my code: 

```
import pandas as pd
import os
from pandasai import SmartDataframe
from pandasai.llm import AzureOpenAI

llm = AzureOpenAI(
    api_token="",
    api_base = "",
    api_version="2022-12-01",
    deployment_name="my_model",
    is_chat_model=True
)
df = SmartDataframe(pd.read_csv('incident_event_log.csv'), config={"llm": llm})
```

Code is working fine till here but whenever I am trying to execute below line, I am getting the error as Resource Not Found: 

`df.chat('How many incidents are active?')`

**Comment by sumeet-cresen** [comment]
Hi @adeepmalmotra , Could you please do the verbose = True and share the result ?? 

I did get the same error few days ago , The above error is mostly because of the azure api endpoint is not defined , properly.

**Comment by adeepmalmotra** [comment]
Hi @sumeet-cresen  I had updated my code like below but still getting the same error: 
```
llm = AzureOpenAI(
    api_token="xxxxxxxxx",
    api_base = "https://example.com",
    api_version="2022-12-01",
    deployment_name="my_model"
)
df = SmartDataframe(pd.read_csv('data/incident_event_log.csv'), config={"llm": llm, "is_chat_model": True,
                    "enable_cache": False,
                    "max_retries": 10,
                    "use_error_correction_framework": True,
                    "verbose": True,
                    "enforce_privacy": True})
```
 
I have filled endpoint and the same endpoint is working find when I am using it for calling openai api

**Comment by sumeet-cresen** [comment]
Hi @adeepmalmotra , 

llm = AzureOpenAI(
    azure_endpoint = "https://xxxx/",
    api_token= "xxxx",
    deployment_name="xxxx",
    api_version="xxxxx",
    model_name="text-davinci-002"
)

please use the above format and for verbose

**Comment by adeepmalmotra** [comment]
@sumeet-cresen what is the difference between deployment_name and model_name? As I was giving deployment_name as the model deployed in azure.

**Comment by adeepmalmotra** [comment]
@sumeet-cresen  I have updated my code like below but still getting same error: 
```
llm = AzureOpenAI(
    api_token="xxxxxxxxxx",
    api_base = "https://example.com/",
    api_version="2022-12-01",
    deployment_name="my_model",
    model_name="test-davinci-003"
)
pandasai_df = SmartDataframe(df), config={"llm": llm, "verbose": True})
```

**Comment by gventuri** [comment]
@adeepmalmotra can you try to update to 1.5.6? If it doesn't work, could you share the logs? It seems a misconfiguration with the settings of azure, so it cannot find the LLM!

**Comment by adeepmalmotra** [comment]
@gventuri I had updated my pandasai package and I am getting below error:
Unfortunately, I was not able to answer your question, because of the following error:

Resource not found

**Comment by sumeet-cresen** [comment]
@adeepmalmotra , try with these version 1.4.10 , 

If it's still showing the same error , Then its the backend issue

**Comment by adeepmalmotra** [comment]
I was able to run it by changing the app version to 2023-03-15-preview, although the same previous version was working fine for azure openai api. But anyways now, its working fine.
