### ISSUE TITLE
why plot return is None?

### ISSUE THREAD

**Issue by iuiu34** [gventuri/pandas-ai#816]
### System Info

 pandasai==1.5.7, python==3.9

### 🐛 Describe the bug

hi,
when i ran
```py
g = df.chat('plot hist for country')
```

`g` is `None` instead of a pd plot or pyplot. Is this desired behaviour?

thanks

**Comment by MuthusivamGS** [comment]
try df.lastcode_executed you will know the reason it doesnt save any variable it does returns a .png image to a pandasai location

**Comment by iuiu34** [comment]
doesn't work. What am i missing?

```py
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI

df = pd.DataFrame(
    {
        "EmployeeID": [1, 2, 3, 4, 5],
        "Name": ["John", "Emma", "Liam", "Olivia", "William"],
        "Department": ["HR", "Sales", "IT", "Marketing", "Finance"],
    }
)

llm = OpenAI()
df = SmartDataframe(df,
                    config=dict(
                        llm=llm,
                    ))



out = df.chat("plot hist name")
df.lastcode_executed()
```

`out` is None
and `df.lastcode_executed()` raises
```
AttributeError: 'SmartDataframe' object has no attribute 'lastcode_executed'
```

**Comment by iuiu34** [comment]
if it helps, it's `df.last_code_executed`.

That said, i think, in the prompt/system. Would be better to ask gpt to assign the plot in a variable. Instead of running `plt.show()` and `plt.save()`

**Comment by gventuri** [comment]
@iuiu34 should have been fixed with the latest release, and now it returns the path! Hope it works for you :)

Closing!

**Comment by cassidyRonan** [comment]
Does this new change showing the path also apply to agent.chat("")?
