### ISSUE TITLE
Agent rephrase_query Error

### ISSUE THREAD

**Issue by zaranaramani** [gventuri/pandas-ai#821]
### System Info

pandasai version: 1.5.9

### 🐛 Describe the bug

using latest pandasai version(1.5.9) for rephrase_query, i'm getting the below error.

Code Snippet::
```
config = {
    "llm": llm
}
agent= Agent(dfs, config=config, memory_size=10)
response = agent.rephrase_query(question)
print(response)
```

Error::
```
Unfortunately, I was not able to repharse query, because of the following error:
'RephraseQueryPrompt' object has no attribute 'conversation_text'
```

**Comment by eadaradhiraj** [comment]
@zaranaramani May I know what the `question` is this?

**Comment by zaranaramani** [comment]
@eadaradhiraj 
i'm getting error for all questions but here is sample question `How many injuries occurred?`

**Comment by eadaradhiraj** [comment]
@zaranaramani OK What data are you using?

**Comment by zaranaramani** [comment]
@eadaradhiraj with example data and question also i'm getting the same error.

```
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})
```

```
df = Agent(df, config={"llm": llm})

response = df.chat('Calculate the sum of the gdp of north american countries')
print(response)

rephrase = df.rephrase_query("Calculate the sum of the gdp of north american countries")
print(rephrase)
```
**ERROR**
```
Unfortunately, I was not able to repharse query, because of the following error:

'RephraseQueryPrompt' object has no attribute 'conversation_text'
```

**Comment by eadaradhiraj** [comment]
> response = df.chat('Calculate the sum of the gdp of north american countries')
> print(response)

I am assuming this df is a smartdataframe object?

> rephrase = df.rephrase_query("Calculate the sum of the gdp of north american countries")
> print(rephrase)


rephrase_query is not a part of dataframe or smartdataframe. It is part of agent.

**Comment by zaranaramani** [comment]
@eadaradhiraj df is Agent object only
```
df = Agent(df, config={"llm": llm})

response = df.chat('Calculate the sum of the gdp of north american countries')
print(response)

rephrase = df.rephrase_query("Calculate the sum of the gdp of north american countries")
print(rephrase)
```

**Comment by eadaradhiraj** [comment]
OK Understood. The problem is caused [here](https://github.com/gventuri/pandas-ai/blob/5b2d0efe5f7d04fd3245d6d2644b8c09af4c9779/pandasai/prompts/rephase_query_prompt.py#L25). I am trying to understand the intention behind this line of code

**Comment by eadaradhiraj** [comment]
This probably needs an API token to test it out.

**Comment by zaranaramani** [comment]
@gventuri 
can you please take a look?

**Comment by Pranab1011** [comment]
@eadaradhiraj 
What is your expected output? I have found a potential fix to this bug and getting the output shown below. Will raise a PR if this works:

`20901884461056
Calculate the total GDP of North American countries.`

**Comment by zaranaramani** [comment]
@Pranab1011 
the answer is correct but what is this number 20901884461056?
> `20901884461056 Calculate the total GDP of North American countries.`

**Comment by Pranab1011** [comment]
@zaranaramani 
That is the output of the first query when I run:
`df = Agent(df, config={"llm": llm})

response = df.chat('Calculate the sum of the gdp of north american countries')
print(response)

rephrase = df.rephrase_query("Calculate the sum of the gdp of north american countries")
print(rephrase)`

For some reason, the 2 outputs are showing on the same line here.

The output looks something like this:
![Screenshot 2024-01-15 at 6 45 57 AM](https://github.com/gventuri/pandas-ai/assets/47911727/470b3b00-071c-4d21-80a6-4dca46fd050b)

**Comment by zaranaramani** [comment]
@Pranab1011 i think the number is answer of question. Can you verify that?

**Comment by Pranab1011** [comment]
@zaranaramani 
You are right. It is the answer to the question.

**Comment by zaranaramani** [comment]
@Pranab1011 Let me know once fix is added.
