### ISSUE TITLE
Connector-Mysql databse connectotion

### ISSUE THREAD

**Issue by Sana555-Attar** [gventuri/pandas-ai#822]
from pandasai.connectors import MySQLConnector

mysql_connector = MySQLConnector(
    config={
        "host": "localhost",
        "port": 3306,
        "database": "mydb",
        "username": "root",
        "password": "root",
        "table": "loans",
        "where": [
            # this is optional and filters the data to
            # reduce the size of the dataframe
            ["loan_status", "=", "PAIDOFF"],
        ], 
    }
)

df = SmartDataframe(mysql_connector)
df.chat('What is the total amount of loans in the last year?')

In table how can i mention the multiple tables?it is nit taking list of tables.
@gventuri @avelino @nautics889 @victor-hugo-dc

**Comment by gventuri** [comment]
Hi @Sana555-Attar, you should rather have a connector for each table individually, like this:

```
mysql_connector = MySQLConnector(
config={
"host": "localhost",
"port": 3306,
"database": "mydb",
"username": "root",
"password": "root",
"table": "loans",
"where": [
# this is optional and filters the data to
# reduce the size of the dataframe
["loan_status", "=", "PAIDOFF"],
],
}
)

mysql_connector2 = MySQLConnector(
config={
"host": "localhost",
"port": 3306,
"database": "mydb",
"username": "root",
"password": "root",
"table": "loans",
"where": [
# this is optional and filters the data to
# reduce the size of the dataframe
["loan_status", "=", "PAIDOFF"],
],
}
)
```

and then you pass both of them to a SmartDatalake, like this:

```
lake = SmartDatalake(
   [mysql_connector, mysql_connector2]
)
```

**Comment by Sana555-Attar** [comment]
Ok, Thanks! @gventuri
