### ISSUE TITLE
Openai Key error.

### ISSUE THREAD

**Issue by JuneYangF** [gventuri/pandas-ai#85]
### 🐛 Describe the bug

 I can use the key to access openai api while when I used pandas ai it failed

**Comment by JuneYangF** [comment]
use the openai.api_key to set the api_key and don't pass the api_token through OpenAI function solved the problem

**Comment by gventuri** [comment]
Hey @JuneYangF, at the moment there are 2 supported ways to pass the api key to openai:
* you can set OPENAI_API_KEY env variable
* you can pass as you instantiate OpenAI, like this:
```
from pandasai.llm.openai import OpenAI

llm = OpenAI(api_token="YOUR_API_TOKEN")
```
