### ISSUE TITLE
Please support SQLAlchemy 2.0 and other dependency updates

### ISSUE THREAD

**Issue by Josha91** [gventuri/pandas-ai#853]
### 🚀 The feature

It would be very nice if the latest version of some dependencies can be supported. In particular, it would be great if PandasAI can be used with SQLAlchemy 2.0 and Pandas 2.0.

### Motivation, pitch

I'm using Pandas 2.0 / SQLAlchemy 2.0 in my projects and downgrading that is not really an option.

**Comment by leehanchung** [comment]
Opened a PR to relax `sqlalchemy` version. Implemented similar to [Langchain's pyproject.toml](https://github.com/langchain-ai/langchain/blob/4ed3d17c47c0e81ac92bd2fcd368ddd66897eb8a/libs/langchain/pyproject.toml#L18)

@gventuri could we please prioritize this? It's a major blocker.

```toml
[tool.poetry.dependencies]
...
SQLAlchemy = ">=1.4,<3"
```
