### ISSUE TITLE
name 'PandasAI' is not defined

### ISSUE THREAD

**Issue by prajendr** [gventuri/pandas-ai#877]
### System Info

python 3.10.8, in VS Code , padasai 1.5.14, llm AzureOpenAI

### 🐛 Describe the bug

Got "name 'PandasAI' is not defined" error in below code in VS

import pandas as pd
from pandasai.llm.azure_openai import AzureOpenAI
from pandasai import SmartDataframe
llm = AzureOpenAI( deployment_name='',   model_name="",api_token='' , api_base='', api_version='',azure_endpoint = '')
pandas_ai = PandasAI(llm)
pandas_ai(df, prompt='Which are the 5 happiest countries?')

**Comment by gventuri** [comment]
Check out your code, `PandasAI` is indeed not declared: indeed you should use `SmartDataframe`.

Check out the docs: https://docs.pandas-ai.com/en/latest/getting-started/
