### ISSUE TITLE
Add Support for Google Gemini pro api

### ISSUE THREAD

**Issue by osamahnini** [gventuri/pandas-ai#879]
### 🚀 The feature

Add Support for Google Gemini pro api

### Motivation, pitch

Gemini pro has a great potential

**Comment by gventuri** [comment]
Hi @osamahnini, it's already supported via VertexAI, do you have some other API in mind to use with Gemini Pro?

**Comment by osamahnini** [comment]
Thank you @gventuri. I tried to use Google Gemini Pro with Pandas AI, but it seems that it supports only these input parameters in the example code:
`llm = GoogleVertexAI(project_id="generative-ai-training",
                     location="us-central1",
                     model="text-bison@001")`
But I try to use Gemini Pro API as google provide it as following:
'curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Write a story about a magic backpack"}]}]}' \
  -X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=YOUR_API_KEY'

**Comment by gventuri** [comment]
@osamahnini interestingly google always provides so many ways to use their LLM APIs! Sure, then we'll need to do a new wrapper for this too.

If you want to work on it, feel free to do so, otherwise someone else can pick it (I marked it as a good first issue!)

**Comment by Umar-cs** [comment]
Hi @gventuri @osamahnini 
Its simply working by passing api key but not generating charts in streamlit, the visualization bug is already reported above.
**Example**
from pandasai.llm.google_palm import GooglePalm
 llm = GooglePalm(api_key=api_token)
        pandas_ai = SmartDataframe(df, config={"llm": llm, "verbose": True, })
While more enhancement needed.

**Comment by Umar-cs** [comment]
Hi @gventuri 
Both Palm and Gemini now use the same API keys, so you can easily replace previously added Palm LLM with Gemini LLM. However, I think it should be added as a new separate LLM until Palm is officially deprecated by Google itself.

**Comment by gventuri** [comment]
@Umar-cs 100% agree, we need a new connector, and once PaLM will be deprecated, we'll deprecate it too!

**Comment by tytung2020** [comment]
any update on this? It still not able to use Google VertexAI with these parameters:
'''
llm = GoogleVertexAI(
    project_id="some_location", location="us-central1", model="gemini-1.5-flash"
)
'''
