### ISSUE TITLE
Allow using custom heads through Agent

### ISSUE THREAD

**Issue by aaossa** [gventuri/pandas-ai#882]
### 🚀 The feature

Using a custom head [is possible and documented](https://docs.pandas-ai.com/en/latest/custom-head/) for privacy/verbosity reasons when using a `SmartDataframe`. An `Agent` behaves similarly to a `SmartDataframe` or a `SmartDatalake`, so using a custom head seems like should be possible.

### Motivation, pitch

At the moment, I'm working on an `Agent` that uses multiple sources of sensitive data that I don't want to disclose to a third party. I wrote a custom head using fake data, but I'm unable to pass it when using the `Agent` class because there's no way to pass the value to the inner `SmartDatalake`.

The Agent creates its own instance of a `SmartDatalake` here:

https://github.com/gventuri/pandas-ai/blob/3f4b1e5574f52839f7914cc6ec457b1eb358a2ba/pandasai/agent/__init__.py#L45

while `pd.DataFrames` are loaded by the `SmartDatalake` here:

 https://github.com/gventuri/pandas-ai/blob/3f4b1e5574f52839f7914cc6ec457b1eb358a2ba/pandasai/smart_datalake/__init__.py#L173-L191

### Alternatives

The only common object that is passed through both instances (the `Agent` and the `SmartDatalake` is the `Config` instance, which should be available as `self.config` inside the `SmartDatalake._load_dfs` method. This means that we should be able to pass a custom head for each dataframe passed as argument to the `Agent` inside the `config` kwarg of that class. Something like this:

```python
agent = Agent([df1, df2], config={"custom_heads": [custom_head_1, custom_head_2]})
```

Of course, this needs a modification of the `SmartDatalake._load_dfs` method to retrieve the custom heads from the `Config` object:

```python
    def _load_dfs(self, dfs: List[Union[DataFrameType, Any]]):
        """
        Load all the dataframes to be used in the smart datalake.

        Args:
            dfs (List[Union[DataFrameType, Any]]): List of dataframes to be used
        """

        from ..smart_dataframe import SmartDataframe

        smart_dfs = []
        for i, df in enumerate(dfs):
            if not isinstance(df, SmartDataframe):
                smart_dfs.append(
                    SmartDataframe(df, config=self._config, custom_head=self._config.custom_heads[i], logger=self.logger)
                )
            else:
                smart_dfs.append(df)
        self._dfs = smart_dfs
```

**Note**: Maybe a list is not the best data structure, but this seems like it should work (after modifying the `Config` class).

**Comment by gventuri** [comment]
Hi @aaossa great catch! It is indeed possible to do what you need: in fact, you can instantiate a SmartDataframe and then pass it to the Agent as one of the params:

```
sdf = SmartDataframe(..., custom_head=...)
agent = Agent(sf, ...)
```

This should do the trick :) Feel free to reopen in case this solution doesn't fit your need!

**Comment by aayush0419** [comment]
Hi @gventuri, I have the same query but I am unable to follow your trick. Please can you elaborate, if possible?
