### ISSUE TITLE
Minor issue with documentation

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#885]
### System Info

N/A

### 🐛 Describe the bug

Page https://docs.pandas-ai.com/en/latest/examples/, section "Working with Agent".

Code lines:

```
# Chat with the agent
response = agent.chat("Who gets paid the most?")
print(response)

# Get Clarification Questions
questions = agent.clarification_questions()
```

It should be if I understand it correctly:

```
query = "Who gets paid the most?"

# Chat with the agent
response = agent.chat(query)
print(response)

# Get Clarification Questions
questions = agent.clarification_questions(query)
```

clarification_questions has parameter query.

**Comment by gventuri** [comment]
@PavelAgurov thanks a lot, would you mind submitting a PR for that? 🙏

**Comment by PavelAgurov** [comment]
I will try do to it this evening.

**Comment by milind-sinaptik** [comment]
that is correct, let me fix that.
