### ISSUE TITLE
Shortcut_Summarizing Data 

### ISSUE THREAD

**Issue by fatma010** [gventuri/pandas-ai#891]
### 🚀 The feature

Getting an outline at once for a Pandas Dataframe helps saving time. For this purpose a summarization shortcut can be added:

> Summarize data to group for each distinct value in a column

> For each distinct value :
       calculate subtotal of rows 
      calculate the percentage of the total count for each group

It can be applicable to different columns in the dataframe 
There is an example table for student's exam status:

Student ID   Count of Exam          Perc of of Exam    Pass          Perc of pass      Fail     Fail Pec
  1                       10                          0.25                       5               0.17                    4         0.25
  2                      10                          0.25                       10              0.33                   0           0
  3                      20                          0.50                      15              0.5                     12          0.75

### Motivation, pitch

Getting an outline at once for a Pandas Dataframe helps saving time.

**Comment by Pranab1011** [comment]
@gventuri I can take this up.
Let me know how you'd like me to get started
