### ISSUE TITLE
Minor fix in logger for chart

### ISSUE THREAD

**Issue by PavelAgurov** [gventuri/pandas-ai#894]
### System Info

version v1.5.17

### 🐛 Describe the bug

In method execute_code there is a call method add_save_chart when temporary chart is replaced by provided path.
Issue that it show message in the log always, even if I have nothing about chart in my query.
It's because no checking if we need to replace path or not:

```
        code = code.replace("temp_chart.png", save_charts_file.as_posix())
        logger.log(f"Saving charts to {save_charts_file}")

```
I guess if should be something like (but I'm not sure here):

```
   if "temp_chart.png" in code:
        code = code.replace("temp_chart.png", save_charts_file.as_posix())
        logger.log(f"Saving charts to {save_charts_file}")
```

Now we can have message in log only when we have somehing about chart.

Also maybe better to have "temp_chart.png" as const in some place.

There is another way to fix it - just replace message to "New place of chart is xxx"  because in fact we do not save chart in this code, we only replace path.

**Comment by Lorenzobattistela** [comment]
Hey @gventuri , I'm up to picking up this issue. Will investigate it further today. Feel free to assign me. Thanks!

**Comment by gventuri** [comment]
@Lorenzobattistela sure, just assigned to you!
