### ISSUE TITLE
Apply linting

### ISSUE THREAD

**Issue by HenriqueAJNB** [gventuri/pandas-ai#9]
There are a lot of linting issues in the code. They should be analyzed, and the critical ones fixed.

My suggestion is to add `pylint` and `mypy` as main linters.

**Comment by gventuri** [comment]
@HenriqueAJNB, yeah totally! Never tried `mypy`, would you recommend it over `pylint`?

**Comment by gventuri** [comment]
Still some linting errors, re-open

**Comment by HenriqueAJNB** [comment]
@gventuri, `mypy` and `pylint` can be used both, since the first one only checks for type hints and the second one is a statical code analyzer. 

I can handle this issued. We can even be flexible and not so strict, by adding some rules exceptions if it make sense.
