### ISSUE TITLE
Randomly getting incomplete answers

### ISSUE THREAD

**Issue by BenAkko** [gventuri/pandas-ai#90]
### 🐛 Describe the bug

Hi there,

Firstly, I think this is an awesome project, thanks to those who create and maintain it!

I am using this football dataset - https://www.kaggle.com/datasets/rishikeshkanabar/premier-league-player-statistics-updated-daily

My code is exactly as the example suggests.

When I give it a prompt, sometimes it works fine - for instance, asking it "How many nationalities are there? How many occurrences are there of each nationality?" generates a response of 'There are a total of 47 nationalities in the dataset. The number of occurrences for each nationality varies, with England having the highest count at 221 and many other nationalities having only one occurrence.', which is brilliant.

However, when I ask it about players or clubs, it essentially rewords the question and doesn't give an answer. For example:
Prompt = pandas_ai.run(df, prompt="Who has the most offsides?")
Response = 'has the most offsides, did you know that?'

Prompt = pandas_ai.run(df, prompt="Which club has the most red cards?")
Response = 'has the most red cards, did you know that?'

Any idea why this might be happening? 

Edit : I should note, I have only just set up my OpenAI API key, but I'd be surprised if that was a factor in this issue given it works fine some of the time.

**Comment by gventuri** [comment]
Closing as this issue has been fixed
