### ISSUE TITLE
Empty response in starcoder LLM in version 0.2.9

### ISSUE THREAD

**Issue by acnmartens81** [gventuri/pandas-ai#99]
### 🐛 Describe the bug

Hi,

First of all, hats of to this great project! Thanks to all who contribute and maintain it!

I'm using the Starcoder LLM and it seems that version 0.2.9 did break something. 
I ran the code below on version 0.2.9 and 0.2.8

In version 0.2.8 I get a correct response: 
	country	gdp	happiness_index
6	Canada	1607402389504	7.23
7	Australia	1490967855104	7.22
1	United Kingdom	2891615567872	7.16

In version 0.2.9 I don't get an error but just an empty string as response: ''
I'm using Python 3.10.6

P.S. I've used these to commands to switch between the versions. 
```
#install 0.2.8
pip install pandasai==0.2.8

#install 0.2.9
pip install pandasai==0.2.9
```

Thanks,
Alain

```import pandas as pd
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder

df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

llm = Starcoder(api_token=<API_KEY>)
pandas_ai = PandasAI(llm, verbose=False)

prompt_input = "Which 3 countries are happiest?"
response = pandas_ai.run(df, prompt_input, is_conversational_answer=False)
response

**Comment by JeffreyLind22** [comment]
Here is an issue under the same umbrella -- appeared in PandasAI 0.2.9 w/ Starcoder. I get the `Conversational Answer` output as shown in the photo, but it simply restates the question twice.
![Screenshot 2023-05-09 at 10 56 30 AM](https://github.com/gventuri/pandas-ai/assets/124309394/6c53339e-b95e-4c0e-8694-7ee1295b1bcb)

Here is my code with the UI stripped out
```python3
import pandas

from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder
        
dataPrompt = "Make a bar chart of the order qty for all desired ship dates."

llm = Starcoder(api_token="HF_API_TOKEN")

pandasAI = PandasAI(llm)

pandasDataFrame = pandas.read_csv("filename.csv")

response = pandasAI.run(pandasDataFrame, prompt = dataPrompt)

print(response)
```

**Comment by akespresso** [comment]
Same applies to Open AI. I get the following verbose response:

```
Code generated:
```
df.groupby('country').sum().nlargest(3, 'qtd_revenue').index.tolist()
```
Answer: 
```

But it doesn't execute

**Comment by gventuri** [comment]
@acnmartens81 @JeffreyLind22 @akespresso fixed it. Please check it out, it should work now. Unfortunately the security update released yesterday had created this regression.

Thanks a lot for reporting!
